### ISSUE TITLE
Lost performance with neo4j-driver 5.2.0 on the browser

### ISSUE THREAD

**Issue by camorimd** [neo4j/neo4j-javascript-driver#1019]
Hello! I'm really sorry because I really don't know how to state the issue so I'll try to give as more detail as possible.

I have a web-project that uses neo4j-driver to connect to a database neo4j database (currently version 4.4.6) and it works flawlessly.
This is the code in question: 

```javascript
 rxSession.run(
            `MATCH (n:${label}) return n order by toLower(n.Nombre)`
        ).records().pipe(
            map( record => record.get('n')),
            concatWith(rxSession.close())
        ).subscribe({
            next: (data) => {
                this[label].items.push(data);
            },
            complete: () => {
                this[label].saving = false;
                this[label].loading = false;
                if(this[label].selected.identity != -1) this.select(label, this[label].items.find(v => v.identity.toInt() == this[label].selected.identity.toInt()));
            },
            error: (error) => this.errors.push(error)
        });
```

With driver version 4.4.6 and database version 4.4.6 it loads 760 nodes in milliseconds.
Now that I updated the driver to the 5.2.0 version, the same code loads 760 nodes in 5 seconds!

**Comment by bigmontz** [comment]
@camorimd, I will investigate the issue.

**Comment by camorimd** [comment]
Thank you very much, I will try to create a sandbox app replicating the issue to see if that helps to diagnose the problem.

**Comment by bigmontz** [comment]
Hi @camorimd, 

I've found the issue. I will ping here when released.

**Comment by bigmontz** [comment]
Fix released in 5.3.0

**Comment by camorimd** [comment]
Great! I will test it and give some feedback!

**Comment by camorimd** [comment]
Solved, thank you very much!
