### ISSUE TITLE
[Bug] Unable to query relationships with JavaScript driver

### ISSUE THREAD

**Issue by ajmeese7** [neo4j/neo4j-javascript-driver#1021]
I am not able to retrieve relationships with the Neo4j JavaScript driver.

**Neo4j Version:** 5.1.0 Enterprise
**Neo4j Mode**: Single instance
**Driver version**: JS driver 5.2.0
**Operating System:** Zorin 16 Pro

### Steps to reproduce

Run a query for `MATCH (n) RETURN n` with a JavaScript driver session.

### Expected behavior

The same data returned by the Neo4j Browser:

![Neo4j data with relationships](https://user-images.githubusercontent.com/17814535/203881203-64e1b365-df96-4617-b28d-2f509cb696cf.png)

### Actual behavior

No relationships are returned:

```js
[
  {
    "n": {
      "identity": {
        "low": 0,
        "high": 0
      },
      "labels": [
        "Selector"
      ],
      "properties": {
        "notes": "Google DNS resolver",
        "realm": "ipv4",
        "selector": "8.8.8.8",
        "uuid": "15cee84d-b4fc-4d47-9002-f1539d01bf92"
      },
      "elementId": "4:ba878390-d801-48ca-ad97-f4a8046c3a96:0"
    }
  },
  {
    "n": {
      "identity": {
        "low": 1,
        "high": 0
      },
      "labels": [
        "Selector"
      ],
      "properties": {
        "notes": "This is the devil's IP, subleased by Google.",
        "realm": "ipv4",
        "selector": "6.6.6.6",
        "uuid": "a43b2c17-27bf-49b8-a1a6-e74741804f2d"
      },
      "elementId": "4:ba878390-d801-48ca-ad97-f4a8046c3a96:1"
    }
  }
]
```

To get the above data, I used the following code (simplified):

```js
const query = "MATCH (n) RETURN n";
const session = driver.session();
let queryResult;

await session
	.run(query, parameters)
	.then((result) => {
		// The `log` doesn't show anything related to relationships, just `records` and `summary`
		console.log("Result:", result);
		queryResult = result.records.map((record) => record.toObject());
	})
	.catch((error) => {
		throw error;
	})
	.finally(() => {
		session.close();
	});

return queryResult;
```

If you're interested, this is the raw output returned by the `console.log` statement above:

```log
{
  records: [
    Record {
      keys: [Array],
      length: 1,
      _fields: [Array],
      _fieldLookup: [Object]
    },
    Record {
      keys: [Array],
      length: 1,
      _fields: [Array],
      _fieldLookup: [Object]
    }
  ],
  summary: ResultSummary {
    query: { text: 'MATCH (n) RETURN n', parameters: {} },
    queryType: 'r',
    counters: QueryStatistics { _stats: [Object], _systemUpdates: 0 },
    updateStatistics: QueryStatistics { _stats: [Object], _systemUpdates: 0 },
    plan: false,
    profile: false,
    notifications: [],
    server: ServerInfo {
      address: 'localhost:7687',
      agent: 'Neo4j/5.1.0',
      protocolVersion: 5
    },
    resultConsumedAfter: Integer { low: 1, high: 0 },
    resultAvailableAfter: Integer { low: 0, high: 0 },
    database: { name: 'neo4j' }
  }
}
```

**Comment by bigmontz** [comment]
This is not a bug. Browser has a configuration called `Connect result nodes`. With this options enabled, Browser does additional queries to enrich the visualisation with connected data. 

<img width="343" alt="Screenshot 2022-11-25 at 12 54 16" src="https://user-images.githubusercontent.com/1593958/203980827-3c73b46b-8826-482d-a6dd-d1d360f4f05e.png">

**Comment by ajmeese7** [comment]
@bigmontz noted, could you explain how to query relationships with the JavaScript driver then? I want to be able to fetch everything in a query, nodes and relationships alike.

----

**Update:** I know you can use `MATCH (n) MATCH (n)-[r]-() RETURN n,r` to get all the nodes and their relationships from a query, that's not an issue. What I'm hoping is to have the data returned in a format that is compatible with the [HTTP endpoint](https://neo4j.com/developer/javascript/#js-http-endpoint). I have [a library](https://github.com/TargetPackage/neo4jd3#neo4j-data-format) that currently needs the data in the returned HTTP format.

If that's something that I need to make into a separate issue instead of discussing here, I wouldn't mind doing so, just let me know. Sorry for the confusion! :)

**Comment by bigmontz** [comment]
The only way of getting the relationship from the nodes using cypher. The Javascript Driver is responsible for the network communication with the Neo4j Database. For instance, `Browser` and `Bloom` use this driver for communicating with the database.
