### ISSUE TITLE
Setting for returning strings by default instead of neo4j.int

### ISSUE THREAD

**Issue by bryanph** [neo4j/neo4j-javascript-driver#106]
Currently the API returns neo4j.int instances for every numeric result. Converting these to strings before sending it to the user is quite tedious. I was wondering if a default 'string' setting would make sense, this would alleviate a lot of unnecessary mapping.

**Comment by whatSocks** [comment]
or a default low / high setting.

**Comment by whatSocks** [comment]
there's an open PR about this issue https://github.com/neo4j/neo4j-javascript-driver/pull/94

**Comment by pontusmelke** [comment]
We are looking into how we want to go about doing this part more convenient in the API.

Regards,
Pontus

**Comment by zhenlineo** [comment]
Hi, we provides a `InSafeRange` method now to help to decide if the number is safe to cast to int or string. The PR is https://github.com/neo4j/neo4j-javascript-driver/pull/153

Pls let us know if that solves your problem.

**Comment by lutovich** [comment]
@bryanph I hope functionality added in https://github.com/neo4j/neo4j-javascript-driver/pull/153 resolves the issue. Please feel free to post more info.
