### ISSUE TITLE
 time consumed in neo4j browser for a query is ~20ms, while using the driver facing a huge increase in time ~370ms.

### ISSUE THREAD

**Issue by pawanbana** [neo4j/neo4j-javascript-driver#1081]
I am also facing this, using neo4j-driver v5.7.0. the issue is time consumed in neo4j browser for a query is ~20ms, while using the driver facing a huge increase in time ~370ms.

used the console.time and console.timeEnd to still the same time.  
environment is nodejs:v18.

```      
     console.time('test1');
      const result = await session.executeRead((tx) => tx.run(query, variables));

      console.timeEnd('test1');

_Originally posted by @pawanbana in https://github.com/neo4j/neo4j-javascript-driver/issues/818#issuecomment-1514727365_

**Comment by bigmontz** [comment]
@pawanbana, are you using the same method to measure out the performance in browser and node?

**Comment by Apidcloud** [comment]
~~I'm having the same issue, as documented in [https://github.com/neo4j/neo4j-javascript-driver/issues/818](https://github.com/neo4j/neo4j-javascript-driver/issues/818#issuecomment-1514727365_)~~

~~In browser.neo4j the query takes 3-4ms (ran with profile 2x). with the driver, through node 18, it takes around 150-250ms.~~ Check Edit below.

<img width="1118" alt="image" src="https://github.com/neo4j/neo4j-javascript-driver/assets/3720818/184b93b7-dca6-48b8-8f84-93b08629d215">

<img width="548" alt="image" src="https://github.com/neo4j/neo4j-javascript-driver/assets/3720818/7c374975-5e28-41a2-992c-d7045a93fd34">

Some more details:
<img width="242" alt="image" src="https://github.com/neo4j/neo4j-javascript-driver/assets/3720818/f9201c00-b356-46f7-bb68-9ff26f2e8f3e">

node: v18.14.2
neo4j-driver-lite: v5.13.0
client machine specs: Macbook Air M1 (16gb RAM) with Ventura 13.4.1 

Edit:
Actually, we are just comparing and measuring different things. The 3-4ms we see in browser.neo4j is the **resultAvailableAfter** of the Summary. It tells us how long the query actually takes to have a result.

When checking that same value through the js (or go) driver it still takes around the same time. The query itself only takes the 3-4ms to have a result, but it takes time to a) get to the db; and b) to get the result back over the chosen communication protocol.

**Comment by bigmontz** [comment]
Closed since the problem is related to how data is presented in Browser, not in the driver itself (since Browser use the driver).
