### ISSUE TITLE
Different situations on different browser

### ISSUE THREAD

**Issue by Mingaaaaaaa** [neo4j/neo4j-javascript-driver#1084]
Hi,I use your Neovis.js Simple Example HTML to link my neo4j database on my server.And I deploy it on [here](https://ysjy.alplune.top/index.html). and [here](https://stellar-semifreddo-d2866e.netlify.app/)  
But I found out that my Edge、Safari and Firefox work successfully. but in Chrome or on my phone It can't work 
```js
{
neo4j: {
                    serverUrl: "neo4j://ysjy.alplune.top",
                    serverUser: "aaaa",
                    serverPassword: "aaaa",
                    driverConfig: {
                    encrypted: "ENCRYPTION_ON",
                    trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES",
                },
                }
}
```
I read this [article](https://aura.support.neo4j.com/hc/en-us/articles/360041294913-Error-when-connecting-to-Neo4j-Aura-Error-code-ServiceUnavailable-name-Neo4jError-),but did't work
 What I want to do is visit this web via web-view on phone. But It will console the same error :
 

> neovis.js@2.0.2:2 Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1683984347375, routers=[], readers=[], writers=[]]

**Comment by bigmontz** [comment]
@Mingaaaaaaa, can you try to enable driver logs as debug?

```
{
neo4j: {
                    serverUrl: "neo4j://ysjy.alplune.top",
                    serverUser: "aaaa",
                    serverPassword: "aaaa",
                    driverConfig: {
                       encrypted: "ENCRYPTION_ON",
                       trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES",
                       logging: neo4j.logging.console("debug"), // enabling debug log. 
                    },
                }
}
```

This error can be related several root causes and the logs might help to understand the issue. 

See:
https://neo4j.com/docs/api/javascript-driver/5.9/function/index.html#static-function-driver

**Comment by bigmontz** [comment]
Issue closed due inactivity. Please, open again the issue if the error persists and you have more evidences.
