### ISSUE TITLE
How would I connect to a graphenedb neo4j database (version 3.0.3)

### ISSUE THREAD

**Issue by robblovell** [neo4j/neo4j-javascript-driver#114]
Say I have a connection string like so: 

`http://[user]:[pass]@[url]:[port]/[path]`

How would I connect using this driver?

**Comment by robblovell** [comment]
using:

`driver = neo4j.driver('http://[url]:[port]/[path]', neo4j.auth.basic([user], [pass]))`

or

`driver = neo4j.driver('bolt://[url]:[port]/[path]', neo4j.auth.basic([user], [pass]))`

gives:

`Error: 140735243259904:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:`

**Comment by robblovell** [comment]
using:

`driver = neo4j.driver('http://[user]:[pass]@[url]:[port]/[path]')`

gives:

`
{ Error: getaddrinfo ENOTFOUND network network:3
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'network',
  host: 'network',
  port: '3' }
`

**Comment by jgkim** [comment]
@robblovell You should use `bolt` with this driver. It doesn't support `http`.

**Comment by robblovell** [comment]
Thank you, I just saw the bolt connection string on a separate tab in the connections section of graphenedb.  It connects fine with that url.

**Comment by robblovell** [comment]
Thanks, got it working!

r0bb
