### ISSUE TITLE
Add release notes to Github releases

### ISSUE THREAD

**Issue by ryan-dahlia** [neo4j/neo4j-javascript-driver#1165]
# Feature Request
Thank you for this great library! Please consider making your release notes available to Dependabot, so that users can more easily understand the changes for each version update.

I believe it would be sufficient to move your CHANGELOG file to the root of the repo, and/or add release notes in the Github Releases section.

# Pitch
The maintainers do a great job documenting the changes between versions, but Dependabot cannot source them, because they are in a non-standard location. Therefore, Dependabot shows the generic message from the [Releases page](https://github.com/neo4j/neo4j-javascript-driver/releases), instead of the full release notes (see photo).

<img width="416" alt="image" src="https://github.com/neo4j/neo4j-javascript-driver/assets/144152335/f6e812c6-ae46-41c0-8533-51a3472ed447">

**Comment by bigmontz** [comment]
This is a fair point, I will check it out how to do it without duplicate work.

**Comment by ryan-dahlia** [comment]
Great, thank you @bigmontz! I'm not a Dependabot expert but lmk if I can help!

**Comment by ryan-dahlia** [comment]
@bigmontz thank you for incorporating this suggestion, it looks lovely!

<img width="769" alt="image" src="https://github.com/neo4j/neo4j-javascript-driver/assets/144152335/66763bfc-8b08-4989-9e32-0406eca59c30">
