### ISSUE TITLE
Back pressure

### ISSUE THREAD

**Issue by brian-gates** [neo4j/neo4j-javascript-driver#117]
Is there a way to apply back pressure to the driver if the consumer indicates they are not ready to receive a result?

My driver ([cypher-stream](https://github.com/brian-gates/cypher-stream)) presents cypher results as [Node.js object streams](https://nodejs.org/api/stream.html).  Node streams support back pressure and high-watermark levels to allow fine-tuning of memory management.  I'm curious if there's a way to implement this.

**Comment by pontusmelke** [comment]
Currently there is no easy way to do this but it is one of the things we are looking into. Hopefully in a way that makes sense across different drivers.

Regards,
Pontus

**Comment by legraphista** [comment]
+1

Streaming large amounts of data from Neo4j through node into another location (like mongo, or firebase) that might not be able to keep up with the data torrent will result in pressure building up in the node process and, eventually running out of memory and blowing up.

For example, streaming 100M `Integers` from Neo4j at a rate of 300k/s and feeding them into a system that can only accept 10k/s will result in a pressure of 100MBs just after 2M streamed data points, .5GBs after 10M, 1GB after 20M and after 31.7M the system crashes (you could always allocate more memory, but i don't believe that's a good answer).

There are ways to work around this, like a query that would make use of `SKIP` and `LIMIT` for the results, but that just puts a massive strain on the database itself.

**Comment by technige** [comment]
This is something on our roadmap but with no estimation as yet for when we can deliver it since it requires more server work.
