### ISSUE TITLE
Possible to retain Node association when returning a subset of properties?

### ISSUE THREAD

**Issue by brian-gates** [neo4j/neo4j-javascript-driver#129]
```
match (n) return n
```

The above returns Node objects.

```
match (n) return { id: n.id } as n
```

Does not.

Is it possible to retain the association while also minimizing the return payload?

**Comment by pontusmelke** [comment]
I am not sure I completely follow, if you don't need a full node object you should just return the things you need,

```
MATCH (n) RETURN id(n), n.prop1, n.prop2,...
```

or am I missing your point?

**Comment by brian-gates** [comment]
I've essentially done this.  Here is my implementation:

```
return { __isNode: true, id: id(n), labels: labels(n), properties: { id: n.id, name: n.name } } as n
```

This works, but is quite a bit of extra work to re-implement the functionality one gets for free via a bonafide `Node` object.  And I still have to manually reinstate the item's `Node`ness based on what is returned.

I understand _why_ a `Node` isn't returned.  It's a hash.  Who knows what's in it?

Perhaps map projections resolves this?

 https://neo4j.com/blog/cypher-graphql-neo4j-3-1-preview/

**Comment by pontusmelke** [comment]
Ok, now I understand what you mean. No currently there is no magic way of achieving this, we are working on better ways of serializing graph properties both on the server side and in the drivers. Map projections is one of these endeavors that might work for you but you will unfortunately have to wait for 3.1 for that one.

Regards,
Pontus

**Comment by brian-gates** [comment]
Yeah I figured. I'm guessing map projections won't even solve the issue, since I assume they return maps (given the name).

I think what we need is some way to "mask" the output. It sounds like a separate feature to map projections. 

Anyway, I'll close the issue, especially since it sounds like it has nothing to do with this driver specifically.
