### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by Jabher** [neo4j/neo4j-javascript-driver#135]
Hey, just wanted to thank you, guys.

It's definitely awesome that there is an official JS lib for neo4j, and double-awesoming is the fact that it's working over a binary protocol over websockets in a browser.

**Comment by pontusmelke** [comment]
Thanks, glad you like it! I'll keep this issue open if someone else (hopefully) experience the same issue :)

**Comment by technige** [comment]
Closing this issue as we cannot improve on how awesome it is so why even try.
