### ISSUE TITLE
Connection pool returns terminated connections

### ISSUE THREAD

**Issue by GertSallaerts** [neo4j/neo4j-javascript-driver#136]
From time to time, I see this message in the logs of my app.

```
Error: This socket has been ended by the other party
      at Socket.writeAfterFIN [as write] (net.js:286:12)
      at NodeChannel.write (.../node_modules/neo4j-driver/lib/v1/internal/ch-node.js:254:20)
      at Chunker.flush (.../node_modules/neo4j-driver/lib/v1/internal/chunking.js:114:18)
      at Connection.sync (.../node_modules/neo4j-driver/lib/v1/internal/connector.js:488:21)
      at Session._onClose (.../node_modules/neo4j-driver/lib/v1/driver.js:163:14)
      at Session.close (.../node_modules/neo4j-driver/lib/v1/session.js:138:16)
      at .../node_modules/seraph/lib/bolt/seraph.js:191:46
      at _treatParams.then.then.catch (.../node_modules/seraph/lib/bolt/seraph.js:260:31)
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

I am able to reproduce it by following these steps:
1. Start neo4j and my app
2. Make a request to my app, there is now one connection in the pool
3. Restart the neo4j database
4. Make another request to my app

To me, it seems like the connection pool is holding on to these connections that were closed by the server, i.e. the server sent a FIN packet to the socket. I have some code that fixes the issue for me, will submit a PR momentarily.

**Comment by pontusmelke** [comment]
@Gertt I merged your PR, thanks a lot! I'll close this issue, but please reopen or open a new one if you have more issues.

Regards,
Pontus

**Comment by caub** [comment]
Just a question, I see the [internal/pool.js](src/v1/internal/pool.js) file, why isn't it exposed publicly? Or does the `driver.session()` use it?

I guess not since it's asked to close a session as soon as it's used, the session would just a be a client. I think exposing the pool would be convenient

**Comment by lutovich** [comment]
@caub pool is an internal implementation detail of the driver. Users should never directly interact with it. Driver contains a pool of connections and acquires connections from it when session executes query or starts a transaction. Users should only care about opening/closing sessions and transactions.

**Comment by caub** [comment]
@lutovich ah thanks for the precision, so sessions are cheap? I can open and close one per DB request?

Thanks again

**Comment by lutovich** [comment]
@caub yes, it is cheap to open/close session. It will not open/close network connection every time, but will instead use the underlying connection pool. It is recommended to have a single driver per application and open/close session per request.
