### ISSUE TITLE
web browser driver issue with Angular2 2.0.0-rc6

### ISSUE THREAD

**Issue by neilpennell** [neo4j/neo4j-javascript-driver#139]
First of this is great and works with the exception of the following issue I have found.

The issue is using the async pipe.  I have create a simple application to show the issue and it can be found at 
- https://github.com/neilpennell/asyncTest

The async pipe in angular stops working as soon as you import/require the neo4j-web.min.js file.

The version is:
- "neo4j-driver": "1.0.4"

**Comment by pontusmelke** [comment]
Thanks for reporting this, we will look into the issue and get back to you here.

Regards,
Pontus

**Comment by lutovich** [comment]
Hi @neilpennell,

Sorry for such a delayed followup. I tried your application and it indeed does not work with neo4j-driver 1.0.x (tried default 1.0.4 and 1.0.5). However it seems to work with 1.1+ driver (tried 1.1.0, 1.2.0 and 1.3.0). PR to upgrade version is here: https://github.com/neilpennell/asyncTest/pull/1.

It is hard to say which exact commit fixed the problem. Unfortunately there are no error logs from the Angular application. I'll close this issue but please feel free to update it if you are still having issues.

--
Konstantin
