### ISSUE TITLE
Equivalent of resultDataContents["graph"]

### ISSUE THREAD

**Issue by rvazarkar** [neo4j/neo4j-javascript-driver#140]
Is there any plans to include the REST equivalent of resultDataContents["graph"] in the Bolt implementation? Currently, getting data from bolt into something like linkurious requires you to coerce the returned data into the format expected by the graph. Would be useful to simplify the process of displaying the data in common formats, since translating the results of the REST call into the graph format is significantly easier.

**Comment by technige** [comment]
This is not something that we plan to add to the drivers in the short term. This was originally a shortcut for the browser but beyond the scope of low-level drivers.

Longer term, we will probably work towards "returning subgraphs" functionality within Cypher itself which will necessarily require the drivers to expose subgraphs instead of records within a result.

**Comment by brian-gates** [comment]
I'm really interested to know what "returning subgraphs" might look like.

**Comment by technige** [comment]
Unfortunately, we don't have any public information to share on that as yet.

**Comment by jexp** [comment]
As the bolt drivers natively return nodes, relationships and paths, there is much less need for a dedicated output format. Please note that the REST format was only halfway through as it only extracted nodes, rels per row and not per result.

If you need a pure graph result response, you can collect nodes and rels from the entities that are returned.

It would be nice thouhg to have a convenience method on StatementResult.asGraph that would collect and return all distinct nodes and rels for you.

**Comment by technige** [comment]
Closing as wontfix in this form

**Comment by w3villa-anant** [comment]
`Have q query regarding`
