### ISSUE TITLE
Websocket fails if data transmitted is over a certain size

### ISSUE THREAD

**Issue by rvazarkar** [neo4j/neo4j-javascript-driver#142]
Currently using the Papaparse library to parse out a CSV file and commit the data to a neo4j database.

The queries are created using an UNWIND syntax and props are created from the csv file directly. If I use a chunk size of anything greater than approximately 50000 bytes, the application will eventually cease to send any more data to neo4j. Note that, this issue does NOT exist in the node implementation, as the exact same code, copy pasted and run using node ./test.js works flawlessly.

The application is running in electron, so chromium based. No errors are emitted when the application stops sending data, and nothing is returned in the results. All queries are being done using promises.

```
var userQuery = 'UNWIND {props} AS prop MERGE (user:User {name:prop.account}) WITH user,prop MERGE (group:Group {name:prop.group}) WITH user,group MERGE (user)-[:MemberOf]->(group)'
var computerQuery = 'UNWIND {props} AS prop MERGE (computer:Computer {name:prop.account}) WITH computer,prop MERGE (group:Group {name:prop.group}) WITH computer,group MERGE (computer)-[:MemberOf]->(group)'
var groupQuery = 'UNWIND {props} AS prop MERGE (group1:Group {name:prop.account}) WITH group1,prop MERGE (group2:Group {name:prop.group}) WITH group1,group2 MERGE (group1)-[:MemberOf]->(group2)'
var s1 = driver.session()
var s2 = driver.session()
var s3 = driver.session()
console.log(s1)
console.log(s2)
console.log(s3)
var p1
var p2
var p3
p1 = s1.run(userQuery, {props: props.users})
p1.catch(function(err){
    console.log(err)
})
p1.then(function(){
    s1.close()
    p2 = s2.run(computerQuery, {props: props.computers})
    p2.catch(function(err){
        console.log(err)
    })
    p2.then(function(){
        s2.close()
        p3 = s3.run(groupQuery, {props: props.groups})
        p3.catch(function(err){
            console.log(err)
        })
        p3.then(function(){
            s3.close()
            this.setState({progress: Math.floor((sent / count) * 100)})
            console.log('set done')
            console.log(driver)
            parser.resume()
        }.bind(this))
    }.bind(this))
}.bind(this))
```

This is the relevant snippet of code. Depending on the size of the data chunk being submitted, this will either run a few times, or never at all.

Based on testing I've seen the following:
1MB of data will never submit anything
100kb of data will submit exactly twice
60kb of data will submit ~150 times and then fail
50kb of data will happily submit until my file is exhausted. It's entirely possible it would fail on a bigger file, which I'll test

Based on the behavior, by best guess is some sort of buffer being filled and then failing out, but I'm at a loss. The neo4j database log is similarly unenlightening.

**Comment by rvazarkar** [comment]
Just as an update to this, I tested the same code with a 160 MB csv file, and it worked through the entire file with a chunk size of 50000 bytes

**Comment by pontusmelke** [comment]
Thanks for reporting this. Will look into it.

Regards,
Pontus

**Comment by technige** [comment]
Thanks for raising this, we are currently adding more comprehensive load testing to all our drivers. Stay tuned.
