### ISSUE TITLE
Session is lost when Neo4j is restarted

### ISSUE THREAD

**Issue by ayosec** [neo4j/neo4j-javascript-driver#143]
With version 1.0.4, the driver does not reconnect when the server closes its connection. This is an important issue because we have to reinitialize the session if we restart the Neo4j server.

Is it possible to create a new Bolt connection when the current one is lost?

The issue can be reproduced with the following script:

``` javascript
const neo4j = require("neo4j-driver").v1;
const spawn = require("child_process").spawn;
const Socket = require("net").Socket;

var driver = neo4j.driver("bolt://localhost", neo4j.auth.basic("neo4j", "neo4j"));
var session = driver.session();

function waitPort(port, next) {

  var client = new Socket();
  client.on("error", function() {
    setTimeout(function() { waitPort(port, next) }, 300);
  });

  client.connect(port, "localhost", next);

}

// 1) Execute a query

session
  .run("RETURN 1")
  .subscribe({
    onCompleted: function() {},
    onNext: function(record) {

      console.log("Got a record; Restart Neo4j");

      // 2) Restart Neo4j

      spawn("./neo4j-community-3.0.6/bin/neo4j", [ "restart" ])
        .on("close", function() {

          // 3) When Neo4j is ready, execute the next query

          waitPort(7687, function() {

            console.log("Bolt is ready to be used; driver should be able to reconnect");

            session
              .run("RETURN 1")
              .subscribe({
                onCompleted: function() {},

                onNext: function(record) {
                  console.log("It works!");
                }
              });

          });

      })
    }
  })
```

This script produces the following output:

```
Got a record; Restart Neo4j
Bolt is ready to be used; driver should be able to reconnect
Uncaught error when processing result: Error: This socket has been ended by the other party
```

**Comment by pontusmelke** [comment]
The session wraps a connection and the connection is killed when you restart the database. You need to ask the driver for a new session. In general sessions should be short lived, you acquire a session from the driver, perform a task and close the session again. The driver maintains a pool of sessions/connections so reacquiring sessions is cheap.

Regards,
Pontus

**Comment by ayosec** [comment]
Hi @pontusmelke,

> You need to ask the driver for a new session. In general sessions should be short lived, you acquire a session from the driver, perform a task and close the session again.

I added another `var session = driver.session();` before the second query, and it works as you described.

Thanks you. I'm closing the issue.
