### ISSUE TITLE
Neo4J 3.0 overlapping transactions

### ISSUE THREAD

**Issue by cipacda** [neo4j/neo4j-javascript-driver#150]
I am using Neo4j v3.0.6 with neo4j-driver 1.1.0-M2 (BOLT) and am experiencing the following behaviour where everytime two transactions overlap the second one fails. Is that expected behaviour? It looks weird to me given they are also in different session and they access different data.

session1 = db.session()
txn1 = session1.beginTransaction()
session2 = db.session()
txn2 = session2.beginTransaction()
txn1.commit()
txn2.commit() -> Fails with signature 126 and no other message

See also: http://stackoverflow.com/questions/39846438/neo4j-3-0-overlapping-transactions

**Comment by lutovich** [comment]
Hi @cipacda,

Thanks for reporting this. It should definitely be possible to use transactions like this.
I've tried to reproduce the issue using a simple test:

```js
it('should do the thing 2', function (done) {
    var session1 = driver.session();
    var tx1 = session1.beginTransaction();
    var session2 = driver.session();
    var tx2 = session2.beginTransaction();
    tx1.run('CREATE ()').then(function () {
      tx2.run('CREATE ()').then(function () {
        tx1.commit().then(function () {
          tx2.commit().then(function () {
            session1.close();
            session2.close();
            done();
          });
        });
      });
    });
});
```

but it works fine using current 1.1 head. Maybe you have a better test to reproduce?

Thanks in advance!

**Comment by cipacda** [comment]
Hi @lutovich 

I have got past this problem and I think this was either fixed or I just fixed my code.. I don't remember what the resolution was in the end unfortunately. You can close this issue and will let you know if I encounter it again.

Thanks,
Ciprian

**Comment by lutovich** [comment]
@cipacda Thanks!
