### ISSUE TITLE
mention need for driver.close() in README

### ISSUE THREAD

**Issue by ballPointPenguin** [neo4j/neo4j-javascript-driver#151]
Although the README is far from exhaustive and people should be directed to https://neo4j.com/developer/javascript/, a mention of the need to call `driver.close()` would be very helpful.
I could not figure out why my scripts were not cleanly exiting and spent a lot of time debugging `session.close()` looking for answers.

**Comment by zhenlineo** [comment]
Thanks very much for this feedback. We will improve our readme. And you could find more good examples in http://neo4j.com/docs/developer-manual/3.0/drivers/

**Comment by booboothefool** [comment]
@ballPointPenguin @zhenlineo Would this have to do with https://github.com/neo4j/neo4j-javascript-driver/issues/148 at all? I don't have `driver.close()` anywhere...

**Comment by lutovich** [comment]
@booboothefool I guess it could. In node environment absence of `driver.close()` results in the program not being able to exit.
