### ISSUE TITLE
Problem understanding scope of module (comment on the readme)

### ISSUE THREAD

**Issue by erobwen** [neo4j/neo4j-javascript-driver#16]
Hi! 

I am searching for a high performance way to integrate Node.js and Neo4J. I am currently working on using node-java in combination with the native Java API for Neo4J. However, could this be a better alternative? 

The readme makes me confused. It seems like a huge leap to go from node.js module to html directly. HTML is normally something for the client side. What I would like is just a javascript library for accessing a Neo4J database binary, just on the server. Could I see an example of that, without using any html?

**Comment by jakewins** [comment]
@erobwen note that this is alpha-level software targeted for Neo4j 3.0.0, which is not yet released. If you're looking for a NodeJS to access Neo4j from today, have a look at https://www.npmjs.com/package/neo4j

If you're interested in trying this library out, I've updated the readme to highlight that this project works *both* in a browser and in NodeJS. The library is build for NodeJS, with a special bundle to run out of a browser. To use this library from NodeJS, simply install it:

    npm install neo4j-driver

And then import it as per the readme in your NodeJS project:

    var neo4j = require('neo4j-driver').v1;
    var driver = neo4j.driver("bolt://localhost");

Refer to the API docs here for details: http://alpha.neohq.net/docs/javascript-driver/

**Comment by jakewins** [comment]
Please let us know if you end up trying the library out, and if you find it useful or find any issues with it!

**Comment by erobwen** [comment]
As for now I settled for using the Neo4J java API through the node-java interface (https://github.com/joeferner/node-java). I previously tried connecting via seraph (that uses the Cypher Rest API), but it was 3 times as slow as using the native Java api through node-java. 

However, I will keep an eye on this library for the future. I guess it could be even faster to go from javascript to binary Neo4J directly without Java in the middle.
