### ISSUE TITLE
Tagged cypher strings support

### ISSUE THREAD

**Issue by Jabher** [neo4j/neo4j-javascript-driver#169]
Hi! I've encoutered arangoDB yesterday and they have support of template strings in their driver like this: 
```javascript
aql`RETURN ${Date.now()}`
```

I've created similar lib (https://github.com/Jabher/cypher-talker) for doing this in Cypher. I'm totally not against into transfering it into official driver and maintaining it. For now it works like
```javascript
Cypher.tag`
     MERGE (bob:Person {name : ${'Bob'}}) 
     RETURN bob.name
`
.getRawQuery() 
/*=> {
    query: 'MERGE (bob:Person {name : {v0}})      RETURN bob.name',  
    params: { v0: 'Bob' } 
}*/
//or 
Cypher.tag`
     MERGE (bob:Person {${Cypher.literal({name: 'Bob'})}}) 
     RETURN bob.name
`.getRawQuery() 
/*=> { 
    query: 'MERGE (bob:Person {name:{v0_0}})      RETURN bob.name',
    params: { v0_0: 'Bob' } 
}*/
```
But we possibly can figure out better API.

**Comment by jexp** [comment]
HEy @Jabher this sounds like a cool library. would you mind if we listed it on neo4j.com/developer/javascript ?

It currently says *this software is early alpha stage and is not supposed to be used in production*

**Comment by Jabher** [comment]
@jexp for now - yes, it's used in other experimental project only.

I'm feeling like something like base parser support should be brought in in order to drop `Cypher.literal` and `Cypher.raw` usages, but I'm not sure anyone will need it except me. If you sure this can go to developer/javascript, I'll take some time to bring simple parser inside this lib.

**Comment by lutovich** [comment]
Hi @Jabher, @jexp, could this feature be part of https://github.com/neo4j-contrib umbrella project?

**Comment by technige** [comment]
Closing issue on this list but please co-ordinate with us further about a contrib project.
