### ISSUE TITLE
How to pass port no my neo4j is working on port 9494

### ISSUE THREAD

**Issue by ashutosh-akss** [neo4j/neo4j-javascript-driver#182]
I am not able to find documenttion to mention port number , 

my neo4j installation is running on port 9494, and i do not find a way to access it , is there a way we can mention port number ?

Thanks in Advance.

**Comment by lutovich** [comment]
Hi @ashutosh-akss,

You should be able to instantiate driver as described in the [readme](https://github.com/neo4j/neo4j-javascript-driver/blob/1.1/README.md#usage-examples) but with adding port to the uri. Smth like this:
```
var driver = neo4j.driver("bolt://localhost:9494", neo4j.auth.basic("neo4j", "neo4j"));
```

Please note, port in the uri should be bolt port configured on the database sde in `neo4j.conf` file.

See:
http://neo4j.com/docs/developer-manual/3.1/drivers/configure-connect/ for uri formats
http://neo4j.com/docs/operations-manual/3.1/configuration/ports/ for port configs

**Comment by ashutosh-akss** [comment]
@lutovich Thank a ton. I think problem might be with bolt port no. I will figure this out.
