### ISSUE TITLE
Driver exits without error with bad credentials

### ISSUE THREAD

**Issue by rvazarkar** [neo4j/neo4j-javascript-driver#185]
The nodejs driver does not return any sort of error message if bad credentials are provided to the database for authentication.

A simple way to reproduce this is as follows:

```
var neo4j = require('neo4j-driver').v1;

var driver = neo4j.driver('bolt://localhost', neo4j.auth.basic("neo4j", "Ireallyhopethisisntyourpassword"));
var session = driver.session();

session.run('MATCH (n) RETURN n LIMIT 1')
    .subscribe({
        onNext: function(record) {
            console.log(record)
            console.log("onnext")
        },
        onCompleted: function() {
            console.log("complete")
            session.close()
            driver.close()
        },
        onError: function(error) {
            console.log(error)
            console.log("error")
        }
    })
```

If you fix the password provided in the auth.basic, you will correctly get a record (provided you have a record in your db). With an incorrect password, nothing is returned or logged. The driver should ideally at least return some sort of message if the connection was unable to be established due to authentication problems.

**Comment by lutovich** [comment]
Hi @rvazarkar,

Thanks for raising this issue.
It is possible to define `onCompleted` and `onError` callbacks on the driver instance. See these tests:
https://github.com/neo4j/neo4j-javascript-driver/blob/1.1/test/v1/driver.test.js#L78-L89
https://github.com/neo4j/neo4j-javascript-driver/blob/1.1/test/v1/driver.test.js#L63-L76

We definitely need to document them. Please let us know if these callbacks are helpful to you.

**Comment by rvazarkar** [comment]
Thanks for those! I'll play around with them. Eagerly awaiting the January release with the electron fixes!

**Comment by rvazarkar** [comment]
Can confirm that these worked great for me. Thanks!

**Comment by lutovich** [comment]
Thanks @rvazarkar! Callbacks `driver.onCompleted` and `driver.onError` were added to the readme. Closing this issue.
