### ISSUE TITLE
Feature Request for a toJSON method

### ISSUE THREAD

**Issue by ariesshrimp** [neo4j/neo4j-javascript-driver#189]
So far I find this pattern pretty frustrating:

```javascript
// I know I'm getting just one result
session.run(query, params).then(({ records }) => records[0].get(some_key).properties)

// I know I'm getting a list of results
session.run(query, params).then(({ records }) => records.map(r => r.get(some_key).properties)
```

I'm sure there are lots of use cases for all of that other machinery on the response, but a quick "just give me some json that looks like my data" method would be sublimely convenient.

**Comment by legraphista** [comment]
Hi @joefraley, 

There is a method called `.toObject()` coming in `1.1`.
You can find it here: https://github.com/neo4j/neo4j-javascript-driver/blob/1.1/src/v1/record.js#L84-L91

**Comment by lutovich** [comment]
Hi @joefraley,

Thanks for raising this issue. What do you think about the solution suggested/added by @legraphista?

**Comment by ariesshrimp** [comment]
Yeah, that's the idea. Are you open to making the method return a promise instead? A record could be pretty large. I'm thinking of the browser API fetch, whose response object has a json() method that does basically the same thing.

**Comment by lutovich** [comment]
@joefraley method `toObject()` iterates over data that is already in memory, it does not perform network calls and does not fetch things lazily. That is why I think it is reasonable to have it return just an object. What do you think?

**Comment by ariesshrimp** [comment]
That makes sense, I guess the value unwrapping would always happen in a promise chain anyway (after `session.run()`). I think there could be user performance gains by liberating the event loop, but they would only be noticeable for very large records. I think it's fine to leave `toObject()` as a synchronous operation. 👌

**Comment by sean-stanley** [comment]
Actually I tried using your toObject as is and it could benefit from some refinement for easy use still. 

Basically for easy objectifying we want the keys and _fields array zipped together so that 
```
 const keys = { keys: ['n._id', 'n.name'] }
const fields = { _fields: ['123124', 'Joe'] }
``` 

becomes the standard form `{ _id: '123124', name: 'joe' }`

maybe there is a way to get closer to this kind of thing already? I am just learning neo4j and cypher now.

**Comment by lutovich** [comment]
Hi @sean-stanley,

I think you can achieve this using aliases in Cypher.
Presumably your current query looks smth like `MATCH (n) RETURN n._id, n.name`. If you change it to `MATCH (n) RETURN n._id AS _id, n.name AS name` resulting object should be `{_id: ..., name: ...}`.

Hope this helps.

**Comment by jexp** [comment]
Hey @sean-stanley our colleague @oskarhane provided such a function in this demo:

https://jsfiddle.net/oskarhane/amxrwkmo/

**Comment by ariesshrimp** [comment]
@sean-stanley that's exactly what I expected actually, I haven't tried the method yet. 

@lutovich I haven't run into any case where I would rather `RETURN n.name AS name` in my query than simply have the keys and values zipped together by `toObject()`

If you did `RETURN n.name AS name` and `toObject()` had zip behavior, would things break? Maybe that's the problem: being forced to support possible cypher queries of that form.

**Comment by sean-stanley** [comment]
Actually it does behave as expected my bad. I setup a sample case incorrectly. Using the n.name as name method also works well. It's a bit annoying when you need half a dozen fields to do that but for the simple queries it worked well.
