### ISSUE TITLE
Issue with readme inSafeRange

### ISSUE THREAD

**Issue by dalaidunc** [neo4j/neo4j-javascript-driver#194]
On the neo4j namespace there is no `integer`. So this does not work (sadly):

`neo4j.integer.inSafeRange(aSmallInteger)`

**Comment by lutovich** [comment]
Hi @dalaidunc,

Could you please share the code you are having problems with?

This snippet works for me:

```javascript
var neo4j = require('neo4j-driver').v1;
console.log(neo4j.integer.inSafeRange);
```

and prints: `[Function]`.

Thanks!

**Comment by lutovich** [comment]
Hi @dalaidunc,

Do you still have problems with `inSafeRange` function?

**Comment by dalaidunc** [comment]
Yes I still get this problem:
```
var neo4j = require('neo4j-driver').v1;
console.log(neo4j.integer.inSafeRange);
```

TypeError: Cannot read property 'inSafeRange' of undefined

In package.json:
neo4j-driver: ^1.0.5

And node version 6.9.2

**Comment by dalaidunc** [comment]
I've upgraded to version 1.1.0 of the neo4j-driver and it seems to be working now. So the integer object was not being exposed in earlier versions.

**Comment by lutovich** [comment]
@dalaidunc sorry, I forgot to ask which version of the driver you were using. Integer exports different things in 1.0 and 1.1 branches.

In 1.0 it is:

```javascript
export default {
    Integer,
    int,
    isInt
}
```

and in 1.1 it is:

```javascript
export default Integer

export {
    int,
    isInt,
    inSafeRange,
    toNumber,
    toString
}
```

Readme for 1.0 and 1.1 branches also seems correct. Glad you've found the solution. Closing this issue.
