### ISSUE TITLE
neo4j.driver or neo4j.v1.driver

### ISSUE THREAD

**Issue by royipressburger** [neo4j/neo4j-javascript-driver#195]
Hi

I might have missed that, but I cant find any reference to that on the documentation.

What is the differrent between `neo4j.driver` and `neo4j.v1.driver`
What should I use?

Thanks ahead

**Comment by lutovich** [comment]
Hi @royipressburger,

You should use `neo4j.v1.driver`. I do not think it is possible to use just `neo4j.driver` because it is an undefined function.

```javascript
> require('neo4j-driver')
{ v1: { driver: [Function: driver], ... } }
> require('neo4j-driver').v1
{ driver: [Function: driver], ... }
> require('neo4j-driver').v1.driver
[Function: driver]
```

So the suggested usage pattern is:

```javascript
var neo4j = require('neo4j-driver').v1;
var driver = neo4j.driver("bolt://localhost", neo4j.auth.basic("neo4j", "neo4j"));
// ... use driver to create sessions and transactions and execute queries
driver.close(); // close driver when the app shuts down
```

Hope this helps.
