### ISSUE TITLE
Passing an object through params to a SET phrase

### ISSUE THREAD

**Issue by i-am-tom** [neo4j/neo4j-javascript-driver#197]
Hello all!

Firstly, this library is _great_, thank you so much! I've been writing lots of neat little queries like this:

```javascript
run('CREATE (user:User {props}) RETURN user', { props })
```

I have these neat, pre-formatted objects that I can just pass in and everything magically works. However, if I wanted to, for example, update a user's properties, I'd need to do a SET query. Is there a similarly neat way to do this without ugly string-building or creating an entire new node and merging it?

Thanks in advance!

**Comment by legraphista** [comment]
Hi @i-am-tom!
If I understood your question correctly, you can first match the desired user and then update its info like this:
```javascript
run('MATCH (user:User {myUserId: {userId}}) SET user += {props}', { userId, props })
```
This will add the new keys and overwrite old ones that match.
If you want to overwrite **ALL** data on the node, then `SET user = {props}` is what you're looking for.

Hope it helps!

**Comment by i-am-tom** [comment]
Brilliant, that is *exactly* what I wanted! Thank you so much!
