### ISSUE TITLE
Delete Statement does nothing when with UNION ALL

### ISSUE THREAD

**Issue by pentarex** [neo4j/neo4j-javascript-driver#199]
Hey guys, so I am using neo4j since recently and ive never got to write such a big query till now. The cypher looks like

```
MATCH (u:User {username: "test"}) 
OPTIONAL MATCH (u)-[com_rel:COMMENTED]->(com:Comment)-[comOn_rel:COMMENTED_ON]-(post)
WHERE com.uid = 1485635828874
DELETE comOn_rel
SET com_rel.deleted = true
SET com.deleted = true
SET comOn_rel.deleted = true
RETURN com as content
UNION ALL
OPTIONAL MATCH (u)-[sub:SUBMITTED]->(p:Post)<-[comOn_rel:COMMENTED_ON]-(com)<-[com_rel:COMMENTED]-(uu)
WHERE com.uid = 1485635828874
DELETE comOn_rel
SET com_rel.deleted = true
SET com.deleted = true
SET comOn_rel.deleted = true
RETURN com as content
```

Its working when I try on the console (localhost:7474) but it is not working when I am trying it from nodejs.

this is the code on my server 

[Sorry for the JS fiddle paste, I cant format it well](https://jsfiddle.net/wthnzqks/)

It is returning two objects with fields null

Am I doing something wrong or its a bug? P.S. If you find something wrong with my query please do tell me how can I fix it or simplify that monster.
Also i am doing that in the case if someone wants to delete his comment, or the owner of the post wants to delete this user's comment on the particular post

**Comment by lutovich** [comment]
Hi @pentarex,

Could you please share a query or queries to populate database with some test data?
I've tried it locally with data created as in two `OPTIONAL MATCH` clauses and it worked fine.

`UNION ALL` might not be needed here. Could you try smth like this:
```
MATCH (com:Comment {uid: 1485635828874})
OPTIONAL MATCH (user1:User {username: "test"})-[comRel1:COMMENTED]->(com)-[comOnRel1:COMMENTED_ON]-(post1:Post)
OPTIONAL MATCH (user2:User {username: "test"})-[subRel:SUBMITTED]->(post2:Post)<-[comOnRel2:COMMENTED_ON]-(com)<-[comRel2:COMMENTED]-(user3:User)
DELETE comOnRel1, comOnRel2
SET com.deleted = true
SET comRel1.deleted = true, comRel2.deleted = true
SET comOnRel1.deleted = true, comOnRel2.deleted = true
RETURN com AS content
```

Thanks!

**Comment by pentarex** [comment]
Hi thanks for the query. I will give a try. Ive made one two tests today again, and with regret I would like to say "Sorry for losing your time" .... it was my mistake and I feel embarresed. It wasnt working because I was sending string via the rest request and ive never casted contentId to Int.... thats why it wasnt deleting anything... Sorry guys you can close the ticket and @lutovich  thank you again for the query. Looks better than mine for sure :)

**Comment by lutovich** [comment]
Great that you found the problem @pentarex!
