### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by eloyleonardo** [neo4j/neo4j-javascript-driver#20]
How does work transactions in this new version ?
This driver already support transactions or will support ?
I'm question about that because transactions is always a weak point in every neo4j driver in javascript. I already saw some driver that have support (in version 2), but it's very poor compared with Java or other javascript options like sequelize (what is a orm, but do the job very well).

**Comment by jakewins** [comment]
It will support transactions programmatically. For now, you can use a Bolt-specific addon to cypher to run transactions:

    session.run("BEGIN");
    session.run("CREATE .. ")
       .then( function(result) {
         // Do some more work..
         return session.run("MERGE ..");
       })
       .then( function() {
         // And finally commit
         return session.run("COMMIT");
       });

**Comment by jakewins** [comment]
I'll leave this ticket open as a marker for when we've added programmatic transactions

**Comment by jakewins** [comment]
Resolved by https://github.com/neo4j/neo4j-javascript-driver/commit/cdedd344750237154e118b8d32a4ca6179c7d76d
