### ISSUE TITLE
Documentation states string for identity properties when they are actually Integers

### ISSUE THREAD

**Issue by benstevens48** [neo4j/neo4j-javascript-driver#206]
The documentation states that node.identity is a string and similarly for relationship.identity, .start an .end. However they are actually all Integers.

**Comment by lutovich** [comment]
Hi @benstevens48,

You are right, those all have type `Integer` while JSDoc says `string`. I'll create a task for us to fix this.

Thanks!

**Comment by benstevens48** [comment]
Thanks. I did notice somewhere it said Integer was deprecated so maybe there was a plan to change those properties to strings? But it's still necessary to know that they are not strings. I'm calling .toString() on them anyway so hopefully that should cover both cases.

**Comment by lutovich** [comment]
@benstevens48 I think only some functions in `Integer` are deprecated, class itself is quite useful and we do not have close plans to change `identity` to string. It also has integer type in other drivers. Calling `toString()` sounds like a safe solution.
