### ISSUE TITLE
Ability to read a transaction's state

### ISSUE THREAD

**Issue by benstevens48** [neo4j/neo4j-javascript-driver#207]
It would be useful to be able to check what state a transaction is in (or at least whether it is still usable or not). For example if I do something like
```js
let tx = session.beginTransaction();
tx.run(...).then(result =>{
//dostuff
return tx.commit();
}).catch(err => {
return tx.rollback(); //How to tell if I need to do this
});
```
Then how to I tell if I need to rollback my transaction in the catch block - the error could have been caused by some code other than the run statement failing, so I can't assume the transaction has been rolled back. At the moment it seems like the only solution is to add an extra catch to the tx.rollback() call, but this seems a bit messy (and looks even more messy using async await).

**Comment by lutovich** [comment]
Hi @benstevens48,

Both `tx.commit()` and `tx.rollback()` return `Result` which has `then()` and `catch()` methods. Could they be any use to you?

See examples in tests: https://github.com/neo4j/neo4j-javascript-driver/blob/1.1.1/test/v1/transaction.test.js#L215-L230 and https://github.com/neo4j/neo4j-javascript-driver/blob/1.1.1/test/v1/transaction.test.js#L202-L213.

**Comment by benstevens48** [comment]
Hi @lutovich,
Thanks for your reply. I suppose this is Ok, but it seems a bit strange to have to call tx.rollback() even though I know most of the time it will throw an error due to already being rolled back. Also if it throws an error for any other reason it would be more serious and I would like to handle this case differently.

**Comment by benstevens48** [comment]
Hi @lutovich ,
Thanks for the comprehensive fix - the new API looks very useful. Hopefully it can be released to npm as soon as possible.

**Comment by lutovich** [comment]
Hi @benstevens48,

JS driver version 1.2.0-rc1 is released to npm. It is a pre-release version and is available under `next` npm tag so smth like `npm install --save neo4j-driver@next` should get it installed in the project. It would be great if you could try it out and give your feedback!

Here is the changelog entry: https://github.com/neo4j/neo4j-javascript-driver/wiki/1.2-changelog#120-rc1

Thanks.
