### ISSUE TITLE
Cannot check if error is instance of Neo4jError

### ISSUE THREAD

**Issue by GertSallaerts** [neo4j/neo4j-javascript-driver#218]
I would like to check if an error is an instance of `Neo4jError` but using ìnstanceof` does not work.

```js
const { Neo4jError } = require('neo4j-driver').v1;
const e = new Neo4jError('foo');
console.log(e instanceof Neo4jError); // false
```

This seems to be a known issue in babel. For now I've got a workaround that checks if there is a `code` property on the error that starts with `Neo.`.

This babel-transform might be a solution? https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend/blob/master/src/index.js

**Comment by GertSallaerts** [comment]
I also use this library on a few projects but I'm not sure how it will interact with babel: https://github.com/bjyoungblood/es6-error

**Comment by lutovich** [comment]
Hi @Gertt,

Sorry for the delayed response. I tried using babel-plugin-transform-builtin-extend plugin and it seems to work in NodeJS tests but does not work for same tests in PhantomJS. Library es6-error does not seem to work in both.

There exists a standard `Error.name` property https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name. We do nothing with it at the moment but it is probably a good idea to set it to `Neo4jError`. D you think it is worthwhile to do this?
