### ISSUE TITLE
possible typo in stream-observer.js

### ISSUE THREAD

**Issue by flowpl** [neo4j/neo4j-javascript-driver#221]
https://github.com/neo4j/neo4j-javascript-driver/blob/1.2/src/v1/internal/stream-observer.js#L126-L127

_queuedRecords in lines 126-127 should be this._queuedRecords

**Comment by lutovich** [comment]
Hi @flowpl,

You are definitely right. Mentioned PR should fix the problem. Thanks for reporting!
