### ISSUE TITLE
Is neo4j-web.min.js available via any CDN?

### ISSUE THREAD

**Issue by fancellu** [neo4j/neo4j-javascript-driver#226]
As above, just wondering, I'd prefer to link to it externally than pull a copy into my repo

Thanks.

**Comment by fancellu** [comment]
Aha, to answer my own question, you can use rawgit, i.e.

https://cdn.rawgit.com/neo4j/neo4j-javascript-driver/1.2/lib/browser/neo4j-web.min.js

You might want to add that info to the docs

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make minified JS driver file used by browser available more generally via CDN](https://trello.com/c/3JSIS25s/291-make-minified-js-driver-file-used-by-browser-available-more-generally-via-cdn)

**Comment by technige** [comment]
Thanks for the suggestion; we like the idea so we've added it to our future work list to make this available more generally via CDN and to add documentation.

**Comment by akollegger** [comment]
These seem to work:
https://cdn.jsdelivr.net/npm/neo4j-driver@1.5.3/lib/browser/neo4j-web.min.js
https://unpkg.com/neo4j-driver@1.5.3/lib/browser/neo4j-web.min.js
