### ISSUE TITLE
Making the API easier to use with async/await

### ISSUE THREAD

**Issue by nbransby** [neo4j/neo4j-javascript-driver#243]
The current API does not make it possible to await a result, I have the following code in my project to make it easier and believe it should be part of the driver
````js
const neo4j = require('neo4j-driver').v1;
neo4j.types.Result.prototype.promise = function(this: any) {
    this._createPromise();
    return this._p;
}

**Comment by lutovich** [comment]
Hi @nbransby,

Could you please share more details about your project? Do you use driver from NodeJS or browser?

Objects of type `Result` have both `#then()` and `#catch()` functions defined so it should be possible to use `await` for them. We had couple issues like this one https://github.com/neo4j/neo4j-javascript-driver/issues/208 where async-await was used.

I'm able to use async-await in node v7.6.0 and this script:

```javascript
const neo4j = require('neo4j-driver').v1;
const driver = neo4j.driver('bolt://localhost', neo4j.auth.basic('neo4j', 'test'));

async function runQuery() {
  const session = driver.session();
  const result = await session.run(`RETURN 'Hello async-await!'`);
  session.close();
  return result.records[0].get(0);
}

async function test() {
  const queryResult = await runQuery();
  console.log(queryResult);
  driver.close();
}

test();
```

it runs fine and outputs `Hello async-await!`.

**Comment by nbransby** [comment]
Thanks @lutovich! I thought it had to be a promise to work but works fine as you stated
