### ISSUE TITLE
No documentation on Schema creation

### ISSUE THREAD

**Issue by techtolentino** [neo4j/neo4j-javascript-driver#247]
Hello 👋 ,

I'm trying to understand how to use `neo4j-driver` to create a Schema. Based on what I've read in the [Neo4j docs for v 3.1](https://neo4j.com/docs/developer-manual/3.1/cypher/schema/), I'd have to `CREATE INDEX`s on a node with a `:Label`.

For example: I want to create a `Person` schema that indexes a few properties. This is what I attempted:

```
const session = driver.session();
const writeTxPromise = session.writeTransaction(tx =>
  tx.run('CREATE INDEX ON :Person(firstname)');
  tx.run('CREATE INDEX ON :Person(lastname)');
  tx.run('CREATE INDEX ON :Person(email)');

writeTxPromise.then(result => {
  session.close();

  if (result) {
    console.log('Schema created');
  }
});
```

I receive errors in the console saying:
```
/project/neo4j-testing/index.js:16
  tx.run('CREATE INDEX ON :Person(firstname)');
                                             ^
SyntaxError: missing ) after argument list
```

How does one run multiple Cypher statements within a `transaction`?

**Comment by lutovich** [comment]
Hi @techtolentino,

Sorry for the delayed response!
I think your code does not use arrow functions correctly. It is only possible to have a single expression after `=>`. Curly brackets has to be used otherwise. Could you please try the following snippet:

```javascript
const session = driver.session();
const writeTxPromise = session.writeTransaction(tx =>
tx.run('CREATE INDEX ON :Person(firstname)')
   .then(() => tx.run('CREATE INDEX ON :Person(lastname)'))
   .then(() => tx.run('CREATE INDEX ON :Person(email)'))
);

writeTxPromise.then(result => {
    session.close();

    if (result) {
        console.log('Schema created');
    }
});
```

Note that three `tx.run` calls are now chained and form a single expression. It is recommended to do it this way because each `tx.run` call return a promise-like object with defined `then` and `catch` functions.

Alternatively you could write:
```javascript
const session = driver.session();
const writeTxPromise = session.writeTransaction(tx => {
    tx.run('CREATE INDEX ON :Person(firstname)');
    tx.run('CREATE INDEX ON :Person(lastname)');
    return tx.run('CREATE INDEX ON :Person(email)');
});

writeTxPromise.then(result => {
    session.close();

    if (result) {
        console.log('Schema created');
    }
});
```

Note the last `return`. It is needed to make subsequent `if(result)` check pass.

Please let me know if this works.

**Comment by swist** [comment]
Second example is better with Promise.all
```
const session = driver.session();
const writeTxPromise = session.writeTransaction(tx => {
    return Promise.all([
        tx.run('CREATE INDEX ON :Person(firstname)'),
        tx.run('CREATE INDEX ON :Person(lastname)',
        tx.run('CREATE INDEX ON :Person(email)') 
    ]);
});

writeTxPromise.then(result => {
    session.close();

    if (result) {
        console.log('Schema created');
    }
});
```

Otherwise it might resolve when the email index has been created, but first name and last name indices are not. (unless tx has some magic that tracks a call stack and only resolves a promise if all previous run's are done? )

**Comment by lutovich** [comment]
@swist I agree, `Promise.all` makes code express the intention much better.
There is no magic in the driver to handle state of previous queries. It is possible for database to mark transaction as failed on unrecoverable errors. Subsequent queries will fail in such case. However typos and various transient errors can't cause this behaviour.

**Comment by techtolentino** [comment]
Awesome - thank you @lutovich and @swist!

**Comment by lutovich** [comment]
@techtolentino glad it worked for you. Will close this issue now. Please feel free to post more if you experience more problems.
