### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state

### ISSUE THREAD

**Issue by gchokeen** [neo4j/neo4j-javascript-driver#253]
Hi,
I am calling neo4j service from angular 4 application.  I am trying to execure below query. but getting error as **WebSocket is already in CLOSING or CLOSED state**

```
this.db.run(
        'MATCH (n:Person { cognitoId: $cognitoId })\
         MERGE (s:SearchTerm {term:$term})\
         MERGE (n) -[:SEARCHED_FOR]->(s)',
        {cognitoId: this.cognitoId,term: search.term}
      );
```

Error

![image](https://user-images.githubusercontent.com/1717379/27425339-b6373d6c-5755-11e7-8a86-5217820ada15.png)

**Comment by lutovich** [comment]
Hi @gchokeen,

Do you always see this exception or it just pops up once in a while?
Could you maybe come up with a simple app for us to reproduce the problem?

**Comment by gchokeen** [comment]
It worked after **then** part

```this.db.run(
        'MATCH (n:Person { cognitoId: $cognitoId })\
         MERGE (s:SearchTerm {term:$term})\
         MERGE (n) -[:SEARCHED_FOR]->(s)',
        {cognitoId: this.cognitoId,term: search.term}
      ).then(function (result) {
            result.records.forEach(function (record) {
              console.log(record.get('name'));
            });
            $this.db.close();
          })
        .catch(function (error) {
          console.log(error);
        })
```

**Comment by lutovich** [comment]
@gchokeen nice! Just make sure to close the session in `then`. Driver instance should only be closed when app closes. Cheers.
