### ISSUE TITLE
https connection error 

### ISSUE THREAD

**Issue by gchokeen** [neo4j/neo4j-javascript-driver#255]
Hi,

I tried to connect the neo4j from my application it worked well while an application running in **http** protocol, but while changing the protocol to **https**. I am getting the following error.

`neo4j-web.js:29960 WebSocket connection to 'ws://neo4j.host.io:7687/' failed: Connection closed before receiving a handshake response`

I know we need to connect through wss while in https. But don't know how to configure the driver to access https

how to pass **opts.encrypted= true**, can't it switch automatically passed on the application protocol. something like //expample.com

```
    //Allow boolean for backwards compatibility
    if (opts.encrypted === true || opts.encrypted === _util.ENCRYPTION_ON) {
      if (!opts.trust || opts.trust === "TRUST_CUSTOM_CA_SIGNED_CERTIFICATES") {
        scheme = "wss";
      } else {
        this._error = (0, _error.newError)("The browser version of this driver only supports one trust " + "strategy, 'TRUST_CUSTOM_CA_SIGNED_CERTIFICATES'. " + opts.trust + " is not supported. Please " + "either use TRUST_CUSTOM_CA_SIGNED_CERTIFICATES or disable encryption by setting " + "`encrypted:\"" + _util.ENCRYPTION_OFF + "\"` in the driver configuration.");
        return;
      }
    }
    this._url = scheme + "://" + opts.host + ":" + opts.port;

```

**Comment by gchokeen** [comment]
Found this,

`
const driver = neo4j.driver(env.neo4j.host, neo4j.auth.basic(env.neo4j.username, env.neo4j.password), {encrypted: true});`

can't it switch automatically based on application running protocal

**Comment by lutovich** [comment]
Hi @gchokeen,

Does it work for you now with `{encrypted: true}`?
Do you propose driver to check `window.location.protocol` when running in browser, and then switch to `{encrypted: false}` when it is HTTP and switch to `{encrypted: true}` when it s HTTPS?

**Comment by gchokeen** [comment]
`{encrypted: true}` - yes it worked.  If user is not passed entry we may use `window.location.protocol`  to identify application protocal

**Comment by lutovich** [comment]
I think it makes sense. However, it is quite a surface change and I'm not sure we can/should do it in a patch release. We need to think more about this. I'll keep this issue open for now.
