### ISSUE TITLE
Running transaction code (begin, commit & rollback) as a promise

### ISSUE THREAD

**Issue by kmyn** [neo4j/neo4j-javascript-driver#256]
Question: Is there a way I can run the below transaction code using promises?

```javascript
// run statement in a transaction
var tx = session.beginTransaction();
tx.run("MERGE (bob:Person {name : {nameParam} }) RETURN bob.name AS name", {nameParam: 'Bob'})
  .subscribe({
    onNext: function (record) {
      console.log(record.get('name'));
    },
    onCompleted: function () {
      session.close();
    },
    onError: function (error) {
      console.log(error);
    }
  });

//decide if the transaction should be committed or rolled back
var success = false;

if (success) {
  tx.commit()
    .subscribe({
      onCompleted: function () {
        // this transaction is now committed 
      },
      onError: function (error) {
        console.log(error);
      }
    });
} else {
  //transaction is rolled black and nothing is created in the database
  console.log('rolled back');
  tx.rollback();
}
```

Thanks,
Karthik

**Comment by lutovich** [comment]
Hi @kmyn,

Calls `Session#run()` and `Transaction#run()` return a `Result` object. It is a promise-like thing with both `#then()` and `#catch()` functions defined. It can also be consumed lazily with an observer, like in our example.

So it is possible to use promises like this:
```javascript
var promise = tx.run("RETURN 1"); // here promise variable has type Result
promise.then(result => {
    console.log(result.records);
}).catch(error => {
    console.log(error);
});
```

However, it is now recommended to use transaction functions, if you can. They provide automatic retries on transient failures. See "Transaction functions API" section of the [readme](https://github.com/neo4j/neo4j-javascript-driver/blob/1.4/README.md).

Hope this helps.

**Comment by kmyn** [comment]
@lutovich Thanks for the reply.

Let me elaborate a bit, my use case is I'm running hundred's of MERGE queries on the DB and I would like the outcome of queries to have an all or none approach. Additionally, having retries would be a great option in case of network issues. I was thinking of:

BEGIN TRANSACTION
MERGE .... 
MERGE .... 
MERGE .... 
.
.
.
IF NO ISSUES
    COMMIT
ELSE
    ROLLBACK

This is the reason I chose "Explicit transactions API:" option from the readme. But, given the advantages of retries with "Transaction functions API" can I achieve the same thing with these? If yes, how?

**Comment by lutovich** [comment]
@kmyn you could chain promises returned by `Transaction#run()` and commit when the whole chain succeeds. Chaining code could look similar to this:

```javascript
function chainQueries(queries, tx) {
  // chain all queries to run in sequence, also possible to use `Array#reduce()`
  let result = Promise.resolve();
  for(let i = 0; i < queries.length ; i++) {
    const query = queries[i];
    result = result.then(() => tx.run(query));
  }
  return result.then(() => tx.commit())
               .catch(() => tx.rollback());
}
```

Then use this chaining routine in a transaction function or in an explicit transaction.

**Comment by kmyn** [comment]
@lutovich Thanks for the reply. The snippet you provided works perfectly fine.

I was trying to experiment further and tried to parallelize all the MERGE queries as follows:

```javascript
function parallelQueries(queries, tx) {
  // parallelize all queries

  var txMethods = []
  for(let i = 0; i < queries.length ; i++) {
    const query = queries[i];
    txMethods.push(tx.run(query));
  }

  return Promise.all(txMethods)
}

function run(tx) {
     parallelQueries().then((out) =>  { tx.commit() })
           .catch((err) => { tx.rollback() })
 }

run(tx)
```
Two questions:
1. Can you review the above code?
2. For batch MERGE queries, is there any recommended on whether to perform it sequentially or parallely? I would prefer them running parallely but, I'm a bit concerned about locking (deadlocks) internally as all the queries have at least one node in common.

Thanks,

**Comment by lutovich** [comment]
@kmyn code with `Promise#all()` looks good to me. Generally it is beneficial to run queries in parallel but **I think** in your case it might create a lot of contention because of that single common node. It is hard to estimate how much parallelism one can get. The best thing I ca suggest is to measure :)

**Comment by kmyn** [comment]
Thanks @lutovich 

Other than the performance aspect, the difference between the parallel and serial (chainQueries() above) approach I find is that the parallel approach gives back the query result for all the queries exectuted if something is being returned (Ex: MERGE ..... RETURN n). The serial approach does not seem to return anything.

**Comment by lutovich** [comment]
@kmyn serial approach requires you to handle query results manually. You could have an array of results which is updated when promise completes before running the next one. Then this array can be returned after a successful commit.
