### ISSUE TITLE
UnhandledPromiseRejectionWarning in result.js

### ISSUE THREAD

**Issue by Steffen93** [neo4j/neo4j-javascript-driver#257]
Hi,
I'm using the npm package of this neo4j driver in my nodejs application (Node version 7.4.0) and I'm getting the following warning all the time:

`(node:11241) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'call' of undefined`

The warning still appears in the current git version, I just cloned the repo and tested it.
It seems like in [result.js](https://github.com/neo4j/neo4j-javascript-driver/blob/1.4/src/v1/result.js#L119) in the lines 119 and 132, there is no 'catch' for the promises called there and that's why the warning is spit out by node (if your node version is 6.6.0+).

Changing 
```javascript
    self._connectionHolder.releaseConnection().then(() => {
        onCompletedOriginal.call(observer, sum);
    });
```
to 
```javascript
    self._connectionHolder.releaseConnection().then(() => {
        onCompletedOriginal.call(observer, sum);
    }).catch(() => {} );
```
removes the warning for me (tested locally), but I don't know if there is further error handling to do in the catch.

**Comment by lutovich** [comment]
Hi @Steffen93,

Thanks for reporting this problem.
Could you please try fix from https://github.com/neo4j/neo4j-javascript-driver/pull/258?

I believe problem you are seeing is related to absence of "default" value for `onCompleted` callback in the given observer.

**Comment by Steffen93** [comment]
Hi @lutovich,
I can confirm that the issue is fixed for me.
One more thing, in the README.md it says to use `npm build` to build locally, while it is `npm run build` actually. It's just a bit confusing since npm build is still a valid command but doesn't do anything, maybe you can update that some day.

Anyway thanks for the quick fix!
