### ISSUE TITLE
Suggested feature: Make Node and Relationship classes public

### ISSUE THREAD

**Issue by canibanoglu** [neo4j/neo4j-javascript-driver#27]
Hello again,

I hope I'm not irritating you all with these issues. 

One thing that I wish I had access to is the driver's internal types as defined in the `graph-types.js` file. Basically this would allow me to quickly determine the type of a result's parts. Granted, I can now check if the object has a `start` and an `end` field to determine that it is a `Relationship` but this is error prone and is heavily dependent on these classes implementation details. This may be very down the road, but I just wanted to leave a note of it here and perhaps hear your views on it.

Kind regards,

Can

**Comment by jakewins** [comment]
Hey, everything in the `v1` package that isn't under `internal` is public: https://github.com/neo4j/neo4j-javascript-driver/tree/1.0/src/v1 and falls under our commercial backwards compatibility guarantees, meaning there will never be any breaking changes other than in major releases (eg. 2.x.x being the next one). Caveat some insane bug forcing our hand.

Can I ask where you looked to see what was public and not, maybe there's a way we can make this more clear?

**Comment by canibanoglu** [comment]
Oh, I wasn't clear enough. I just meant that I can't get access to them via `require("neo4j-driver")`. For example `int` is exported in `index.js` but not the types that I mentioned.

**Comment by jakewins** [comment]
Ahh, that's a good point. We should indeed add those types to the `v1/index.js` file, so they end up under `require("neo4j-driver").v1.Node`

**Comment by canibanoglu** [comment]
I could prepare a PR if that's alright :)

**Comment by jakewins** [comment]
I'd love you for it! You need to sign our CLA for me to be able to merge it, which basically just says grant us the right to distribute your code, it's a single email so it's pretty quick:  http://neo4j.com/developer/cla/

Happy to review a PR :)

**Comment by canibanoglu** [comment]
Sorry for the late reply, weekend was a bit busy. I have sent the CLA email and will create a PR tomorrow :)

**Comment by canibanoglu** [comment]
#28 is my first attempt. I would be more than happy to change things according to your preferences.

**Comment by oskarhane** [comment]
Fixed with https://github.com/neo4j/neo4j-javascript-driver/pull/28
Thanks @canibanoglu
