### ISSUE TITLE
Session no longer writeable 

### ISSUE THREAD

**Issue by jasperblues** [neo4j/neo4j-javascript-driver#277]
When I turned on causal clustering, I got an issue where sessions would expire as no longer writeable. 

I had a long-lived handle to the driver in an express app, closed when the app closes. Used like this: 

```
const Mapper = require('./Mapper');

class BoltAdapter {

    constructor(driver) {
        this.driver = driver;
        this.mapper = new Mapper()
    }

    cypherQueryAsync(query, params) {

        let self = this;
        return new Promise(function (resolve, reject) {

            let session = self.driver.session();
            session.readTransaction(transaction => {

                transaction.run(query, params).then(result => {
                    session.close();
                    resolve(self.mapper.mapToNative(result.records))
                }).catch(err => {
                    session.close();
                    reject(err)
                })
            })
        })
    }

    writeQueryAsync(query, params) {

        let self = this;
        return new Promise(function (resolve, reject) {

            let session = self.driver.session();
            session.writeTransaction(transaction => {

                transaction.run(query, params).then(result => {
                    session.close();
                    resolve(self.mapper.mapToNative(result.records))
                }).catch(err => {
                    session.close();
                    reject(err)
                })
            })
        })
    }

    close() {
        this.driver.close()
    }
}

module.exports = BoltAdapter;
```

Haven't tested yet, but I'm guessing that if I obtain and close the driver for each transaction each time, it will probably work, however I expected a long lived driver to work, since the driver emits the session.

**Comment by lutovich** [comment]
Hi @jasperblues,

Your code looks correct and uses transaction functions API with retries, so I'd expect transient errors to be retried and not propagated all the way up. Could you please share driver creation code and error that pops up?

**Comment by jasperblues** [comment]
*Driver is passed in to the bolt adapter:*

```javascript
const authToken = neo.auth.basic(process.env.DB_USER, process.env.DB_PW)
const boltAdapter = new BoltAdapter(neo.driver(`bolt://${process.env.DB_HOST}`, authToken))
```

*When the app shuts down:*
```
process.on('exit', () => {
    console.log('\n\nVend shutting down. . .\n')
    boltAdapter.close() //Calls driver.close()
});
```

I should've saved the error message, because I can't find it in the logs now. But it was words to the effect that: Session invalid/expired - host no longer writeable. I'll see if I can find it. 

I have since changed the code above: 

- Inject db_url, user, password. 
- obtain a driver, session, transaction
- on fulfillment or error close the session first, then driver.

**Comment by jasperblues** [comment]
*Not sure if it helps yet, but its like this now:*

```javascript
    cypherQueryAsync(query, params) {

        const self = this;
        return new Promise(function (resolve, reject) {

            const driver = neo.driver(self.url, neo.auth.basic(self.user, self.pass));
            const session = driver.session();
            session.readTransaction(transaction => {

                transaction.run(query, params).then(result => {
                    session.close();
                    driver.close();
                    resolve(self.mapper.mapToNative(result.records))
                }).catch(err => {
                    session.close();
                    driver.close();
                    reject(err)
                })
            })
        })
    }
```

**Comment by lutovich** [comment]
Thanks for sharing the code. Driver creation looks fine. It should not be necessary to recreate the driver on error.

Hard to tell what exactly happened without the error. It might have beed a leader switch, which turns leader from read-write member to read-only member. Do you maybe have database logs from all cluster members for the relevant period?

**Comment by jasperblues** [comment]
Yeah I still have all the logs (though I'm going to discard those instances shortly in favor of larger machines). I'm looking for the relevant parts. Will also attach the whole logs. 

I noticed the error initially in the application (driver side) logs. When it looked like something wasn't write, I dropped back to single instance mode. (This was my first crack at a cluster). 

Gotta step out for a while, will get back to you with more info soon.

**Comment by lutovich** [comment]
Sorry, I think I've missed one problem with your code. It is probably closing sessions too early and thus canceling all retries. `Session#readTransaction()` and `Session#writeTransaction()` return promises and session should be closed when they get resolved or rejected. Closing session within a transaction function cancels retries.

Could you please try the following code:

```javascript
const Mapper = require('./Mapper');

class BoltAdapter {

    constructor(driver) {
        this.driver = driver;
        this.mapper = new Mapper()
    }

    cypherQueryAsync(query, params) {

        let self = this;
        return new Promise(function (resolve, reject) {

            let session = self.driver.session();
            
            const readPromise = session.readTransaction(transaction => transaction.run(query, params))
            
            readPromise.then(result => {
                session.close();
                resolve(self.mapper.mapToNative(result.records))
            }).catch(err => {
                session.close();
                reject(err)
            })
        })
    }

    writeQueryAsync(query, params) {

        let self = this;
        return new Promise(function (resolve, reject) {

            let session = self.driver.session();
            
            const writePromise = session.writeTransaction(transaction => transaction.run(query, params))
            
            writePromise.then(result => {
                session.close();
                resolve(self.mapper.mapToNative(result.records))
            }).catch(err => {
                session.close();
                reject(err)
            })
        })
    }

    close() {
        this.driver.close()
    }
}

module.exports = BoltAdapter;
```

It should make driver properly retry `transaction.run(...)` calls on transient errors like leader switch or network fluctuation.

Hope this helps.

**Comment by jasperblues** [comment]
I see. Will give it a try, thanks a lot @lutovich!

**Comment by jasperblues** [comment]
I'm not sure if it was working. I still saw unhandled promise rejection - "host no longer writeable", but it seemed to obtain a new IP address. 

Had to turn the cluster off again, because it made the app unstable. Let's continue the investigation in a staging environment ;)

**Comment by lutovich** [comment]
@jasperblues did you manage to capture stacktrace and error? It is needed to understand what has happened, as well as database logs from all cluster members.

**Comment by jasperblues** [comment]
@lutovich Sorry, got distracted by other issues. Do you want to leave this ticket open, or close it until I start working on clustering again?

**Comment by lutovich** [comment]
@jasperblues I think we can keep this ticket open for some time. More info is needed for us to investigate. Please update it with more details, when available. Thanks!

**Comment by jasperblues** [comment]
@lutovich Production load is picking up and I'm starting to think about clustering again. I'm guessing this issue might've been caused by attempting a write in a read transaction. Without clustering this will work. 

Will open an issue to fail early on this, so that migration to clustering is easier.

**Comment by lutovich** [comment]
Hi @jasperblues, do you have any updates regarding this issue?

**Comment by jasperblues** [comment]
Sorry, no more info. Clustering plans were paused in favour of other priorities.

**Comment by lutovich** [comment]
Hi @jasperblues,

I'll close this issue for now. Please feel free to update it or open a new one if needed.
