### ISSUE TITLE
How can I install Neo4j typings in my typescript project?

### ISSUE THREAD

**Issue by fer2d2** [neo4j/neo4j-javascript-driver#278]
Hi,

I have a TypeScript 2.0 project (node.js), and I would like to import the typings. There is a library in @types repository (https://www.npmjs.com/package/@types/neo4j), but it is not the official one.

This is my tsconfig.json file:

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "baseUrl": "./src/",
    "lib": ["es6"],
    "types": ["reflect-metadata"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "typeRoots": [
      "./@types",
      "./node_modules/@types"
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```
I've tested this setup with no luck:

```json
    "typeRoots": [
      "./@types",
      "./node_modules/@types",
      "./node_modules/neo4j-driver/types"
    ]
```

As TypeScript is becoming more used (i.e. Angular), this should be added to docs.

**Comment by fer2d2** [comment]
Finally I solved my problem with this *typeRoot* in *tsconfig.json*:

```json
    "typeRoots": [
      "./@types",
      // ...
      "./node_modules/neo4j-driver/types/index.d.ts"
    ]
```

Please, could you include your typings in the @types library or add this to your documentation?

Thanks.

**Comment by lutovich** [comment]
Hi @fer2d2,

Sorry for the delayed response. We will not publish type declarations to DefinitelyTyped for now. They are distributed together with the library on purpose, to not get awfully outdated.

@pocesar how does your usual `tsconfig` look like? Does it also have `typeRoots`?

**Comment by pocesar** [comment]
@lutovich no, `typeRoots` is only used when you neeed to enforce typings order, the solution would @fer2d2 remove the `@types/neo4j` (that vscode installs automatically without asking the user, if that's the case) and use the shipped one. 

and I just noticed a typo in the package.json file, the field for the typings should be `"typings"` and not  `"types"` in https://github.com/neo4j/neo4j-javascript-driver/blob/1.5/package.json#L24

**Comment by lutovich** [comment]
@fer2d2 could you please try the suggested solution?

@pocesar I do not think it's a typo. `types` and `typings` are equivalent, as mentioned by this page https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html.

**Comment by fer2d2** [comment]
@pocesar I'm not using `@types/neo4j`, and it was not installed automatically. I'm using WebStorm.

@lutovich I finally solved my problem without _typeRoots_. The solution was to import the package as a node module, but using the TypeScript syntax, e.g. `import * as Neo4J from "neo4j-driver";`.

Thank you very much!
