### ISSUE TITLE
Properties for `Result` class are not documented.

### ISSUE THREAD

**Issue by 13tales** [neo4j/neo4j-javascript-driver#283]
I've noticed that the `Result` class documentation has some omissions.
There's no documentation of properties, so it's unclear to a newcomer that (for example) `Result.summary.counters` is an instance of `StatisticsSummary`, with the associated convenience methods for returning the number of nodes, relationships, properties modified, etc.

**Comment by lutovich** [comment]
Hi @13tales,

Thanks for reporting this oversight. We will try to fix it for the upcoming 1.5 release.

**Comment by lutovich** [comment]
Hi @13tales,

Please see https://github.com/neo4j/neo4j-javascript-driver/pull/287 for updated docs. Website should get updated after merge. Your review would be super welcome :)
