### ISSUE TITLE
Create Full Node without specifying all params

### ISSUE THREAD

**Issue by gpierrick** [neo4j/neo4j-javascript-driver#285]
Is there a way to do this? I kept running into an error
```
session
    .run('CREATE (cat:Category {props}) RETURN cat', { props: { id: uuidv4(), name: item } })
    .then(function (result) {
        session.close();
        callback();
    })
    .catch(function (error) {
        console.log(error);
        callback();
    });

**Comment by lutovich** [comment]
Hi @gpierrick,

Could you please explain a bit more about what you want to achieve and share the error?
Provided code works for me and creates a `Category` node.

**Comment by gpierrick** [comment]
You're right. I am not sure what I was doing wrong before.

However (unrelated to the driver itself) but I am getting this error message when using ```MERGE```

```
Neo4jError: Parameter maps cannot be used in MERGE patterns (use a literal map instead, eg. "{id: {param}.id}")
```
