### ISSUE TITLE
array parameters

### ISSUE THREAD

**Issue by joshreuben456** [neo4j/neo4j-javascript-driver#294]
is it possible using neo4j-javascript-driver to pass an array param (eg array of strings) for use in a Cypher IN [] WHERE clause ?
if so, how ?

**Comment by lutovich** [comment]
Hi @joshreuben456,

I believe it is possible:

```javascript
const neo4j = require('neo4j-driver').v1;
const driver = neo4j.driver('bolt://localhost', neo4j.auth.basic('neo4j', 'password'));
const session = driver.session();
const array = ['Hello', ' ', 'World', '!'];
session.run('UNWIND $xs AS x RETURN x', {xs: array}).then(result => {
    driver.close();
    console.log(result.records.map(record => record.get(0)).join(''));
});
```

outputs:

```
Hello World!
```

Both `Session#run()` and `Transaction#run()` take an optional second argument - object of parameters. Keys of this object should correspond to parameter names in the Cypher query.

Hope this helps.
