### ISSUE TITLE
[BUG] Errors propagate to other queries in the same session

### ISSUE THREAD

**Issue by swayam18** [neo4j/neo4j-javascript-driver#306]
If a query results in an error (such as a Constraint Violation exception), every future query in the same session also returns the initial error regardless of the correctness of the future query. 

I have written a sample script that replicates this behaviour. The database has a unique constraint on `pk`. In this script, I create two users but 'accidentally' insert the first user twice. The insertion of the first user blows up as expected. However, if I try to add the second user in the same session, I get another constraint violation exception, even though no constraint is actually violated.

Here is the script:

```js
const neo4j = require('neo4j-driver').v1;
const driver = neo4j.driver('bolt://localhost:7687', neo4j.auth.basic('neo4j', 'neo4j'));
const session = driver.session();

// UNIQUE CONSTRAINT on user.pk
session.run("CREATE (a:User {pk: 1 })", {}); // PASSES
session.run("CREATE (a:User {pk: 1 })", {}); // FAILS
session.run("CREATE (a:User {pk: 2 })") // SHOULD PASS BUT FAILS!
    .subscribe({
        onError: function (error) {
            console.log(error);
        }
    });

```

This is the error that is caught by console log:

```
{ Neo4jError: Node(39574) already exists with label `User` and property `pk` = 1
  ...
  code: 'Neo.ClientError.Schema.ConstraintValidationFailed',
  name: 'Neo4jError' }

```

Initally, I thought this is a feature, not a bug. But, If I try to insert the user after a delay of a few seconds, it seems to work:

```js
// UNIQUE CONSTRAINT on user.pk
session.run("CREATE (a:User {pk: 1 })", {}); // PASSES
session.run("CREATE (a:User {pk: 1 })", {}); // FAILS

setTimeout(function() {
    session.run("CREATE (a:User {pk: 2 })") // PASSES!
        .subscribe({
            onCompleted: function () {
                console.log('INSERTED!');
            },
        });
}, 1000);
```
Does anyone know what's going on? Am I missing something obvious?

**Comment by swayam18** [comment]
Here is what I am using:

Language: javascript
Neo4j: 3.3.0 Enterprise Edition (Single Machine)
Driver: neo4j-driver@1.5.0
OS: Ubuntu 16.04

**Comment by lutovich** [comment]
Hi @swayam18,

Thanks for reporting this problem.

Could you please try to chain all promises returned from `session#run()`? Code might look like this:

```javascript
const result = session.run("CREATE (a:User {pk: 1 })", {})
      .catch(error1 => console.log("first query failed ", error1))
      .then(() => session.run("CREATE (a:User {pk: 1 })", {})
        .catch(error2 => console.log("second query failed ", error2))
        .then(() => session.run("CREATE (a:User {pk: 2 })")
          .catch(error3 => console.log("third query failed ", error3))
          .then(() => console.log('queries finished'))));
```

I think in your example database receives all queries before running any of them. It then executes queries one by one and responds with `SUCCESS`, `FAILURE` and `IGNORED` messages correspondingly. Last `IGNORED` message makes driver propagate error from the previous `FAILURE`.

We will investigate more.

**Comment by swayam18** [comment]
Hi @lutovich thank you for getting back to me, and apologies for the delayed response.

I can confirm that chaining promises solves the problem. But if I chain the queries they are run sequentially and may not be as efficient. I have worked around the issue by creating a new session for every query but I am not sure if that is a good idea.

What do you think?

**Comment by lutovich** [comment]
It makes sense to create a session per query. Session is expected to only hold a single connection at a time. Multiple queries will be executed serially within a single session. So multiple sessions are required to parallelize queries.

**Comment by swayam18** [comment]
Thanks, @lutovich. I wonder if we should call this out in the documentation somewhere. The fact that a single session should only have one query running at any given time and one should create multiple sessions if they want to run parallel queries. It wasn't super obvious to me.

**Comment by zhenlineo** [comment]
We've improved [readme](https://github.com/neo4j/neo4j-javascript-driver#parallelization) and also [API docs](https://github.com/neo4j/neo4j-javascript-driver/commit/a6ed396a31c4c2e6420218792172fc5535b8e4e1).
