### ISSUE TITLE
Error creating javascript driver for Neo4j

### ISSUE THREAD

**Issue by prakharrke** [neo4j/neo4j-javascript-driver#312]
Neo4jError: Fatal: No compatible transport available. Need to run on a platform with the WebSocket API.

This is the error I receive when I try to create a driver in node.js

I am using Express server. I am trying to initiate the connection in index.js file of my express server.

**Comment by lutovich** [comment]
Hi @prakharrke,

Thanks for reporting this problem. Could you please provide a simple project to reproduce it?
Which node version are you using?

**Comment by prakharrke** [comment]
index.js

import express from 'express';
import path from 'path';

import webpack from 'webpack';
import webpackMiddleware from 'webpack-dev-middleware';
import webpackConfig from '../webpack.config.dev';

const bodyParser = require('body-parser');
const routes = require('./routes');


let app = express();

app.use(bodyParser.urlencoded({
  extended: true
}));

app.use(bodyParser.json());


app.use(webpackMiddleware(webpack(webpackConfig)));

// * INITIALISING CONNECTION WITH THE DATABASE HERE (initialising the driver)

var uri="bolt://localhost:7687";
var username = "neo4j";
var password = "root";

// * CREATING A REFERENCE TO NEO4J-DRIVER DEPENDENCY.
  const neo4j = require('neo4j-driver/lib/browser/neo4j-web.min.js').v1;

const driver = neo4j.driver("bolt://localhost:7687", neo4j.auth.basic("neo4j", "root"));
// * ROUTES TO routes
app.use('/',routes);


app.listen(3000, () => console.log('Running on localhost:3000'));

**Comment by lutovich** [comment]
Could you please try changing

```javascript
const neo4j = require('neo4j-driver/lib/browser/neo4j-web.min.js').v1;
```

to

```javascript
const neo4j = require('neo4j-driver').v1;
```
?

And also attach `package.json`, please.

**Comment by prakharrke** [comment]
I tried that and it worked. 
But could you please tell me why is that? Because when I create the driver from the client side, it requires const neo4j = require('neo4j-driver/lib/browser/neo4j-web.min.js').v1;

I am using react. When I call a method to create the driver in an onClick handler of some button, it requires me to the former one.

**Comment by lutovich** [comment]
This driver has the same codebase for browser version and NodeJS version. It tries to detect available features (like transport, in this case) at runtime. For transport, it first tries to see if NodeJS socket API is available and then if WebSocket API is available. Later is only present in web browsers, not in Node. I think minified web version of the bundle `neo4j-web.min.js` has the first check for NodeJS socket API stripped away because it never exists in browsers. Thus it only leaves the WebSocket check and `WebSocket` type does not exist in Node environment.

Hope this helps.

**Comment by prakharrke** [comment]
Thank you so much. Could you please help me understand what difference does it make if I make all my database transactions from the browser as opposed to making them from my server? 
Because while making it from the browser, I wait for the response from the database. While making it from the server also, I first make an Ajax call from the browser to the server and then from server to the database. So how are these two different?

**Comment by lutovich** [comment]
When you use driver on the client side (in browser) webpage and browser are the ones who establish WebSocket connections to the database, send queries and deserialize the results. JS code on the webpage is also the one who renders HTML based on the received response from Neo4j.

When server side uses driver it is the one doing all the work to connect and user driver. Server side can presumably have more resources and be better at converting data or processing a large result stream.

I **think** traditionally webpage would talk to a REST API, which is a Node server app. Later would be the one who connects to the database, performs all result processing, formatting, etc. and sends JSON back to the webpage. Architecture depends a lot on the use-case, functional, performance and operational requirements, so please take everything I wrote with with a grain of salt! :)

**Comment by prakharrke** [comment]
Oh, so making transactions from the browser might slow down the web app. That makes so much sense now. Thank you so much. I really appreciate your help.
