### ISSUE TITLE
Is it possible to add an object with key value pairs to a node as its attributes?

### ISSUE THREAD

**Issue by prakharrke** [neo4j/neo4j-javascript-driver#320]
Consider an object obj,
obj = {
name: "myName",
age:22
};
Is it possible to map all the key value pairs of obj to a node as attributes? Some thing like,
MERGE (a:User {obj}) return a;

I do not want to literally map the key value pairs of obj to User node.
The resulting attributes of User node should be:
name:"myName",
age:22

Is it possible to do so?

**Comment by lutovich** [comment]
Hi @prakharrke,

You basically want to set multiple node properties at the same time and supply them as an object/map, right? In this case you can use the `SET` Cypher clause like this:
`MATCH (n {name: 'Andres'}) SET n = $props RETURN n`.

More details can be found in the corresponding developer manual section [here](https://neo4j.com/docs/developer-manual/current/cypher/clauses/set/#set-set-all-properties-using-a-parameter).

Please let us know if this helps.

**Comment by prakharrke** [comment]
Yes this works perfectly. Never been disappointed here. Thank you so much!
