### ISSUE TITLE
Using `noAssert` and default offset

### ISSUE THREAD

**Issue by BridgeAR** [neo4j/neo4j-javascript-driver#336]
Hey, I tried to check if this code uses the `noAssert` argument when using the Node.js Buffer. I also tried to check if some `Buffer#read(U)Int` and `Buffer#write(U)Int` functions use the default offset (not passing through any offset will coerce undefined to zero).

The code was just not straight forward enough for me to determine this easily to open a fix if either would be the case.

If either is the case, please consider changing that. The support for those two dropped for the upcoming Node.js 10.x release.

Refs: https://github.com/nodejs/node/pull/18395

**Comment by lutovich** [comment]
Hi @BridgeAR,

Thanks a lot for the heads-up! We will verify `Buffer` methods usages.
I think relevant code should be in to `buf.js` file / `NodeBuffer` class and `utf8.js`.

**Comment by lutovich** [comment]
Looks like we do not use `noAssert` and always specify offset for write functions. Read/write functions are only used in `buf.js` file. Mentioned PR addresses another deprecation - `Buffer` constructor.

Thanks again for reporting this problem @BridgeAR!
