### ISSUE TITLE
READ ETIMEDOUT

### ISSUE THREAD

**Issue by volaka** [neo4j/neo4j-javascript-driver#337]
Hi there all, this is my first issue so first of all things, thank you for this great product and community support. It is amazing.
Before presenting the error, I would like to present my environment and tools that I use:

**Hosting Provider** 
 - Azure

**OS**
 - Linux #14-Ubuntu SMP Thu Feb 15 16:15:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux -- Ubuntu 16.04

**Docker**
 -  Docker version 17.12.1-ce, build 7390fc6

**Reverse-Proxy**
 - Only in api-server, with ssl 
 - proxy_connect_timeout  10s;
proxy_send_timeout    20s;
proxy_read_timeout      20s;

**Neo4j and Environment**
"Env": [
    "PATH=/var/lib/neo4j/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin",
    "LANG=C.UTF-8",
    "JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre",
    "JAVA_VERSION=8u151",
    "JAVA_ALPINE_VERSION=8.151.12-r0",
    "NEO4J_SHA256=a57be049906cc871b59d7a8283d265485b2c31de47b208ef18636901859232f9",
    "NEO4J_TARBALL=neo4j-community-3.3.3-unix.tar.gz",
    "NEO4J_EDITION=community"
]

**Received Error**
`{ Neo4jError: read ETIMEDOUT`
&nbsp;&nbsp;`at new Neo4jError ($PROJECT_DIRECTORY/node_modules/neo4j-driver/lib/v1/error.js:76:132)`
&nbsp;&nbsp;`at newError ($PROJECT_DIRECTORY/node_modules/neo4j-driver/lib/v1/error.js:66:`
&nbsp;&nbsp;`at NodeChannel._handleConnectionError ($PROJECT_DIRECTORY/node_modules/driver/lib/v1/internal/ch-node.js:330:41)`
&nbsp;&nbsp;`at TLSSocket.emit (events.js:185:15)`
&nbsp;&nbsp;`at TLSSocket.emit (domain.js:421:20)`
&nbsp;&nbsp;`at emitErrorNT (internal/streams/destroy.js:64:8)`
&nbsp;&nbsp;`at process._tickCallback (internal/process/next_tick.js:114:19) code: 'ServiceUnavailable', name: 'Neo4jError' }`

**Tried Solutions**

Added nginx timeout conf to API server, increased machines' specifications, added ulimit to neo4j.

- I have two separate machines. 1 for API-server, 1 for database
  - First I saw this error, my machine specifications was:
    - api-server: 1cpu - 2 gb ram
    - database: 1cpu - 3.75gb ram
    - with these configurations, I thought the problem was performance, so I updated both of these machines
  - Now specifications are:
    - api-server: 2cpu - 14gb ram
    - database: 2cpu - 14gb ram
    
I received the error even with the tried solutions.

It happens only at the first request. After the first request, this error never comes until some idle time passes. When the system was idle for a couple of hours, I receive this error in the first request again.

Thanks in advance,
Best regards.

**Comment by volaka** [comment]
Hi again,

I tried to make changes in config file : 

{
    connectionTimeout: 30000,
    maxConnectionPoolSize: 400,
    maxConnectionLifetime: 6 * 60 * 60 * 1000,
    connectionAcquisitionTimeout: 10 * 60 * 1000
}

haven't seen the error since then. I don't how to reproduce the error. just waiting for it to happen again.

**Edit**
I still receive the error.

**Comment by lutovich** [comment]
Hi @volaka,

Thanks for reporting this problem.

Do you explicitly configure or know if there exists an idle connection timeout in the reverse proxy?
If such timeout exists, I'd recommend setting `maxConnectionLifetime` to a value that is slightly lower than this timeout. Driver will then drop old connections that could potentially be killed by the proxy.

It is also possible to use transaction functions API via `Session#readTransaction()` and `Session#writeTransaction()` which retries on network errors. More details can be found in the [documentation](https://neo4j.com/docs/developer-manual/current/drivers/sessions-transactions/#driver-transactions-transaction-functions).

Hope this helps!

**Comment by volaka** [comment]
Hi @lutovich ,

I wanted to make an update.

First of all, I wasn't using transactions at all. I was using `session.run(query)` directly, and the `query` was a template string with variables inside.

after you mentioned it, I migrated all my backend to transactions and promises. Using read and write carefully, made configurations (that I will mention below) and left template strings and used tx.run(query, **parameters**)

For now, my database is free from ETIMEDOUT error, I have no idea which of the changes above made that error disappear but I am very glad. Thanks for directing me to use transactions, I feel much safer :)

my least configuration is :
{
        maxTransactionRetryTime: 60 * 1000,
        maxConnectionLifetime: 60 * 1000,
        maxConnectionPoolSize: 500,
        connectionAcquisitionTimeout: 10 * 1000
}

Thanks again, if anything changes and the error happens again, I will comment on this issue. :wave:

**Comment by swayam18** [comment]
@volaka We faced a similar problem when we migrated our Neo4j database from AWS to Azure. 

After spending half a day debugging, here is how we fixed it:

**The problem:**
Azure by default kills idle connections after 4 minutes, which is very aggressive as the linux OS default is 2 hours, giving no time for the linux to send KEEPALIVE packets. If you have connection pooling enabled, the pooled connections are no longer valid on Azure and this results in a ETIMEDOUT on the client.

**Solution:** 
On Azure, go to your machine's IP configuration settings and set the idle connection timeout to 30 minutes (the max allowed). Then, configure your server's keep alive settings to a number below 30 minutes. Here is our `sysctl.conf` configuration:

```
# cat /etc/sysctl.conf
# keepalive packets are sent every 10 minutes
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 60
net.ipv4.tcp_keepalive_probes = 10
```

The reason why moving everything to a transaction worked for you is that neo4j drivers automagically catch perceived intermittent network issues and rerun your query, hiding the problem under the rug. I hope this helps.
