### ISSUE TITLE
Unclear error on bad input

### ISSUE THREAD

**Issue by linusmartensson** [neo4j/neo4j-javascript-driver#340]
Hey guys! Love your work!

I was running a query and accidentally passed a string into the query parameters, rather than the actual parameters. Instead of a descriptive error message, all I got was "error: koa-onerror Neo4jError: Connection was closed by server" after a query timeout - which wasn't too helpful at 0430am. :dancer: 
Could we get an input type check and an "erroneous query parameter type" or something when passing bad input on the client side? :1st_place_medal:

**Comment by lutovich** [comment]
Hi @linusmartensson,

Thank you for raising this issue. It definitely makes sense to validate params in the driver. Otherwise, it's a protocol violation and database closes connection. We will most likely fix this problem for the upcoming 1.6 release.
