### ISSUE TITLE
Cannot connect to neo4j from node on Mac OS X?

### ISSUE THREAD

**Issue by blaasvaer** [neo4j/neo4j-javascript-driver#348]
I've installed the noe4j Desktop app (for Mac OS X) and created a database and a graph. In the process I'm asked to create a DB (defaults to `Database`) and a Password. Leaving the DB name at the default `Database` and setting the password to `root`, I would expect to be able to connect to the bugger using the following from :
```
var neo4j = require('neo4j-driver').v1;
var driver = neo4j.v1.driver("bolt://localhost", neo4j.v1.auth.basic("neo4j", "root"));
```
Since the default user, according to the docs, is `neo4j` and I set a different password (follow my logic?)

Now, since that didn't work I starting guessing wildly – which is not a recommended way of creating ANYTHING that should be somewhat useful.

First I thought, maybe try the default credentials that you see all over the docs:
```
var driver = neo4j.v1.driver("bolt://localhost", neo4j.v1.auth.basic("neo4j", "neo4j"));
```
That didn't work.

Then I thought, maybe it's the credentials I used to sign into the screen in the first place (my sign up credentials:
```
var driver = neo4j.v1.driver("bolt://localhost", neo4j.v1.auth.basic("my@email.here", "my_password_here"));
```
That didn't (of course) not work either.

Then I went to `http://localhost:7474` in my browser, and voilà (I thought) ... I did get an interface, something was running. But I was met with this screen:

![screen shot 2018-04-09 at 14 25 22](https://user-images.githubusercontent.com/1193257/38497581-e53c91c0-3c01-11e8-90cb-a159187aaa7a.png)

No matter what I put in here, nothing works!

Now, what the ... is going on here? How do I – in the simplest possible way, without making my head explode, or spend the rest of the week trying to guess my way through this – do I connect to neo4j from a node app ... ALL running on my local machine on localhost?

**Comment by lutovich** [comment]
Hi @blaasvaer,

Provided JS code is not quite correct. It should be:

```javascript
var neo4j = require('neo4j-driver').v1;
var driver = neo4j.driver("bolt://localhost", neo4j.auth.basic("neo4j", "root"));
```
notice absence of `v1` in the second line. You are correct saying that `neo4j` is the default username. So credentials `neo4j/root` should work for both driver and browser. I think you might've mistyped when setting the password in neo4j desktop if they don't.

I've followed all steps locally on Mac OS X and can connect to the database from browser and driver. Can you maybe drop and re-create the database in the desktop app?

**Comment by blaasvaer** [comment]
Thanks @lutovich, that's the danger of copy/pasting from various parts of the neo4j-driver docs ... to anyone else ... make sure you remove the v1 part if you first copy the `neo4j` part from the `Include module in Node.js application` and the `driver` part from `Include in web browser` ... thanks!

**Comment by alopezespino** [comment]
Hi @blaasvaer,

I was having the same problem and found the following solution:

1.  in the neo4j.conf file uncomment the following lines:

```
# Bolt connector
dbms.connector.bolt.enabled=true
dbms.connector.bolt.listen_address=:7687

# HTTP Connector. There must be exactly one HTTP connector.
dbms.connector.http.enabled=true
dbms.connector.http.listen_address=:7474

# HTTPS Connector. There can be zero or one HTTPS connectors.
dbms.connector.https.enabled=true
dbms.connector.https.listen_address=:7473
```


2.  Start the server. In the neo4j built-in terminal type:

`./bin/neo4j console`

3. Then I type the credentials as you did in the browser and everything worked fine.

While I don't fully understand why this works, it solved my problem. It would be great if someone else could provide some background to explain why is this working.
