### ISSUE TITLE
No Such File or Directory!

### ISSUE THREAD

**Issue by eayan** [neo4j/neo4j-javascript-driver#358]
Hi,

I have just tried to install the driver and copied the driver under installation folder but the ourput turnes like this: "npm WARN saveError ENOENT: no such file or directory, open open '/home/erdal/.config/Neo4j Desktop/Application/neo4jDatabases/database-d31d3349-07aa-4aca-9a75-c099128c6eef/installation-3.3.5/package.json'" How can I solve this problem?

Best...
Erdal Ayan, M.A.-M.Sc.

**Comment by lutovich** [comment]
Hi @eayan,

Could you please provide more details about how you want to use the driver and how does your project setup looks like?

It is a bit unclear what "installation folder" is and how Neo4j Desktop fits in the picture. Usually, driver is installed in a JavaScript project using npm command `npm install --save neo4j-driver` or included in a webpage with a `<script>` tag containing a CDN link.

**Comment by eayan** [comment]
Hi @lutovich,

thank you so much for your response. I have a dataset that I already imported into my neo4j server and I want to visualize it via a web application. Initially I thought the driver should be placed under installation or driver folder in no4j server and that's why I have just copied the files under installation. But I have recently figured it out that the script codes should be included outside the server. I was wondering where to begin; should I first the .js file and then .html file to embed javascript codes in? I have seen you have created examples but can you please clarify the process a little bit?

Best...

Erdal Ayan, M.A.-M.Sc.

**Comment by lutovich** [comment]
@eayan driver has to be used by your application. Simple application can consist of js and html files, as you say. You can check documentation [here](https://neo4j.com/developer/javascript/) and the "Get started" guide [here](https://neo4j.com/docs/developer-manual/current/drivers/get-started/) for more details. Simple example of a webpage would be:

```html
<html>
<head>
    <title>Neo4j JavaScript driver exmple</title>
    <script src="https://unpkg.com/neo4j-driver@1.5.3/lib/browser/neo4j-web.min.js" type="text/javascript"></script>
</head>
<body>
<script>
  function readTenNodesAndPrintThem() {
    // get hold of the html element to output data into
    var nodesDiv = document.getElementById('nodesDiv');

    // create driver using correct bolt url and credentials
    var driver = neo4j.v1.driver('bolt://localhost:7687', neo4j.v1.auth.basic('username', 'password'));

    // create session and run a query
    var session = driver.session();
    session.run('MATCH (n) RETURN n LIMIT 10')
      .then(function (result) {
        // nodes fetched successfully, output them
        var records = result.records;
        var resultString = 'Nodes:\n';
        for (var i = 0; i < records.length; i++) {
          var record = records[i];
          var node = record.get('n');
          resultString += node + '\n';
        }
        nodesDiv.innerText = resultString;
      })
      .catch(function (error) {
        // query failed, output the error
        nodesDiv.innerText = 'Error happened: ' + error.code + ' \'' + error.message + '\'';
      })
      .then(function () {
        // finally close both session and driver to cleanup resources
        session.close();
        driver.close();
      });
  }
</script>
<input type="button" onclick="readTenNodesAndPrintThem()" value="Click me to fetch ten nodes and display them"/>
<div id="nodesDiv"></div>
</body>
</html>
```

Hope this helps!

I'll close this issue now because it does not seem to highlight a problem with the JavaScript driver.
