### ISSUE TITLE
Unauthorized even having the right data

### ISSUE THREAD

**Issue by rochapablo** [neo4j/neo4j-javascript-driver#365]
Working with **Node.js** and **Neo4j Desktop**, besides having `n` database with different names `neo4j.driver` seems to read always the currently database _(that's running)_ no matter the name.

When I try to set the database name, I got:

```
Neo4jError: The client is unauthorized due to authentication failure.
```

```
at captureStacktrace (node_modules/neo4j-driver/lib/v1/result.js:200:15)
at new Result (node_modules/neo4j-driver/lib/v1/result.js:73:19)
at Session._run (node_modules/neo4j-driver/lib/v1/session.js:122:14)
at Session.run (node_modules/neo4j-driver/lib/v1/session.js:101:19)
```
```
// neo4j.username = root
// client.database = test123

public constructor(client?: IClient) {
  this.username = client.database || neo4j.username;
  // this.username = neo4j.username;
}

public async run(query, params) {
  try {
    const driver = neo4j.driver(neo4j.host, neo4j.auth.basic(this.username, neo4j.password));
    ...
}
```

```
"neo4j-driver": "^1.5.3",
```

**Comment by lutovich** [comment]
Hi @rochapablo,

JavaScript driver is not aware of the "database" concept. It only cares about the provided Bolt URL. Right now it is not possible to start multiple databases at the same time in Neo4j Desktop. That is why driver should connect to the active/running database.

Does this explain the observed behavior?

**Comment by rochapablo** [comment]
I believe it does,

Thank you.
