### ISSUE TITLE
Client-authenticated TLS connection

### ISSUE THREAD

**Issue by msemenistyi** [neo4j/neo4j-javascript-driver#377]
Hi! I'm struggling to understand if it is possible to connect to the Neo4j instance which has SSL configured and the `client_auth` option enabled.

From the source code  
https://github.com/neo4j/neo4j-javascript-driver/blob/1.7/src/v1/internal/ch-node.js
I see that the client certificates are never uploaded (https://nodejs.org/docs/latest-v8.x/api/tls.html#tls_tls_connect_options_callback - key and cert from the example) but maybe I am missing something?

Thanks.

**Comment by lutovich** [comment]
Hi @msemenistyi,

TLS with client authentication is currently not supported by the drivers. Thus the only supported value for `client_auth` is `NONE` in the SSL policy used for Bolt. We will most probably add this feature but I do not have any estimates.

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Client-authenticated TLS connection](https://trello.com/c/7VQ67xIs/380-client-authenticated-tls-connection)

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Client certificate support for TLS](https://trello.com/c/F7bzlSM6/266-client-certificate-support-for-tls)

**Comment by brainwave** [comment]
Hi, is there any update on this feature since?

**Comment by bigmontz** [comment]
Hi @brainwave, this feature is planned for the first half of this year.

**Comment by bigmontz** [comment]
It will be release at 5.19.0
