### ISSUE TITLE
Is this driver intended for cross-domain connections?

### ISSUE THREAD

**Issue by Alex0007** [neo4j/neo4j-javascript-driver#382]
Frontend is running on localhost, while Neo4j instance is hosted at graphenedb. Current problem is driver not connecting: 

```WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3```

```json
  "dependencies": {
    "neo4j-driver": "^1.6.1",
```

```js
import { v1 as neo4j } from "neo4j-driver/lib/browser/neo4j-web";

const driver = neo4j.driver(
  "bolt://hobby-ehfadfkfcpcngbkelbcffgbl.dbs.graphenedb.com:24786",
  neo4j.auth.basic("demo-user", "secret"),
  { encrypted: true }
);
```

Strange thing i've noticed it starts connecting to neo4j after i am launching Neo4j web browser. But it is not using credentials for user
![image](https://user-images.githubusercontent.com/1143226/40859573-af160cc4-65fb-11e8-9228-d37adefe8925.png)

After clearing browser data on Neo4j web browser page, it stop working again

**Comment by lutovich** [comment]
Hi @Alex0007,

It should be possible to connect to a database hosted on a different server. You can most probably see more details about the error in browser's developer console. Encryption would be my first suspect. Could you please try with `{encrypted: false}`?

**Comment by Alex0007** [comment]
@lutovich 
(i don't actually know what `encrypted` option does)

With `encrypted: false` it's not working even when you have that Neo4j Browser cookie:

![image](https://user-images.githubusercontent.com/1143226/40863798-993e1568-660a-11e8-989a-e97effd7dffb.png)

Here is websocket data when using `{encrypted: false}`

![image](https://user-images.githubusercontent.com/1143226/40863991-669ff954-660b-11e8-81bf-443bf70daf7c.png)

![image](https://user-images.githubusercontent.com/1143226/40864011-76aea822-660b-11e8-9fda-78b790c3f8cb.png)

**Comment by lutovich** [comment]
@Alex0007 this property tells driver to use secure WebSockets. I.e. it will use `wss://<host>:<port>` to connect instead of `ws://<host>:<port>`. I do not quite understand what is that cookie and why is it required. Driver does not rely on cookies, it never reads or writes them. It would be interesting to see errors from the "Console" tab.

Could you please run this code locally and paste its output:

```html
<html>
<head>
    <title>Neo4j JavaScript driver exmple</title>
    <script src="https://unpkg.com/neo4j-driver@1.6.1/lib/browser/neo4j-web.js" type="text/javascript"></script>
</head>
<body>
<script>
  function test() {
    var DATABASE_URL = 'bolt://localhost:7687';
    var USERNAME = 'neo4j';
    var PASSWORD = 'password';
    var encrypted = true;

    var outputDiv = document.getElementById('outputDiv');
    var driver = neo4j.v1.driver(DATABASE_URL, neo4j.v1.auth.basic(USERNAME, PASSWORD), {encrypted: encrypted});

    var session = driver.session();
    session.run('RETURN 42')
      .then(function (result) {
        outputDiv.innerText = 'Success: ' + result.records[0].get(0).toString();
      })
      .catch(function (error) {
        outputDiv.innerText = 'Failure: ' + error.code + ' \'' + error.message + '\'\nPlease see the developer console for more details';
      })
      .then(function () {
        // finally close both session and driver to cleanup resources
        session.close();
        driver.close();
      });
  }
</script>
<input type="button" onclick="test()" value="Click me to test the connection"/>
<div id="outputDiv"></div>
</body>
</html>
```

note the `DATABASE_URL`, `USERNAME`, `PASSWORD` and `ENCRYPTED` variables that need to be updated with the appropriate values. It would be valuable to see output when `ENCRYPTED` is both true and false. Errors in the developer console are the most iteresting part.

Looking forward to your reply!

**Comment by Alex0007** [comment]
@lutovich

Encrypted: true
![image](https://user-images.githubusercontent.com/1143226/41031911-5be0b164-699b-11e8-8a02-7c33a46b48ee.png)

Encrypted: false
![image](https://user-images.githubusercontent.com/1143226/41032019-a9f884e4-699b-11e8-81e4-f5c60672ec0c.png)

After visiting Neo4j web-browser it starts working:
![image](https://user-images.githubusercontent.com/1143226/41032271-403e73be-699c-11e8-8975-522c5db14197.png)

After removing this cookie in web-browser, it stops working.
![image](https://user-images.githubusercontent.com/1143226/41032366-8fbdb6b6-699c-11e8-8fac-47371238efdb.png)

So actually this brings no new information about this issue

I tried various browsers. Also i've tried to use VPN (i'm located in Russia, where censor has banned 80% of all AWS IP addresses). But result is the same.

It's free sandbox db of graphenedb.com. Is result for you is different?

**Comment by Alex0007** [comment]
I've set my own neo4j instance at AWS EC2. And example code works. 

So, i guess, issue can be closed (maybe something is wrong on GrapheneDB side)

**Comment by lutovich** [comment]
Glad it works with a standalone EC2 instance!
Not really sure what that `_graphenedb_token` cookie is about :(
I suspected that it might start working with `{encrypted: true}` if the self-signed certificate is accepted when accessing the browser on a page like:

![screen shot 2018-06-07 at 11 00 51](https://user-images.githubusercontent.com/1638145/41089439-1ce5d7f8-6a42-11e8-9afa-764fbf142a80.png)

this, however, does not explain why `{encrypted: false}` did not work.

It would be great if you could update this issue with more information if you happen to have it in future!
