### ISSUE TITLE
Should the session be closed each query?

### ISSUE THREAD

**Issue by antonioaltamura** [neo4j/neo4j-javascript-driver#384]
Sorry for the basic question:
as in title, should the session have to be closed each query?

```
session
  .run('MERGE (james:Person {name : {nameParam} }) RETURN james.name AS name', {nameParam: 'James'})
  .then(function (result) {
    result.records.forEach(function (record) {
      console.log(record.get('name'));
    });
    session.close();
  })
  .catch(function (error) {
    console.log(error);
  });
```

In sample project here https://github.com/neo4j-examples/neo4j-movies-template
I see some kind of unique session passed around as param of the functions doing queries.

**Comment by lutovich** [comment]
Hi @antonioaltamura,

It is recommended to close sessions when a logical unit of work, that requires a session, is finished. This can either be a single query or multiple queries that need to be executed sequentially. More information about this can be found in the [developer manual](https://neo4j.com/docs/developer-manual/current/drivers/sessions-transactions/#driver-sessions).

Sessions are lightweight and it is not expensive to create one. There is no reason to create and use a single session per application.

Hope this helps!

**Comment by antonioaltamura** [comment]
Thanks, so do you don't agree with that design choice of the sample project?
Another little question: I noticed if I open a READ session:
```
let neo4j = require('neo4j-driver').v1;
let driver = neo4j.driver("bolt://localhost:7687", neo4j.auth.basic("neo4j", "mypass"));
const session = driver.session(neo4j.session.READ);
```
I still can perform a write query, so what's the point of a READ session? There's something I'm missing?

**Comment by lutovich** [comment]
I think sample project does not do anything wrong per se. However, using a single session might have unwanted effects in a cluster setup. See [this section](https://neo4j.com/docs/developer-manual/current/drivers/sessions-transactions/#driver-transactions-causal-chaining) of the developer manual. Thus it is not the recommended approach.

Right now READ and WRITE access mode is only used for routing in a cluster setup. Driver needs a hint about which cluster member to talk to https://neo4j.com/docs/developer-manual/current/drivers/sessions-transactions/#driver-transactions-access-mode. We are planning to extend access mode to be used in the security context. This something for the future release.

**Comment by antonioaltamura** [comment]
thanks for the infos
