### ISSUE TITLE
Query logging - query.log file isn't getting generated. 

### ISSUE THREAD

**Issue by rjgmail88** [neo4j/neo4j-javascript-driver#391]
I have one issue open
 
[https://github.com/neo4j/neo4j-javascript-driver/issues/385](https://github.com/neo4j/neo4j-javascript-driver/issues/385)

in order to debug this issue I planned to get Query logging enable on neo4j vm.  I followed following document but not able to see query.log file getting generated. under following directory. I see only 
debug.log & neo4j.log

```
[cerner@neo4j-nonprod-vm neo4j]$ cd /var/log/neo4j/
[cerner@neo4j-nonprod-vm neo4j]$ ls
debug.log  debug.log.1  debug.log.2  debug.log.3  debug.log.bak  neo4j.log  neo4j.log.bak
```

[https://neo4j.com/docs/operations-manual/current/monitoring/logging/query-logging/](https://neo4j.com/docs/operations-manual/current/monitoring/logging/query-logging/)

**Comment by lutovich** [comment]
Hey @rjgmail88,

This question is not related to the JavaScript driver. It is better to raise issues/questions like this in the neo4j repository https://github.com/neo4j/neo4j/.

It should be enough to configure the following settings to enable logging of all queries:

```
dbms.logs.query.enabled=true
dbms.logs.query.threshold=0
```

and restart the database. Then logs should appear in the directory specified by the `dbms.directories.logs` setting.

Could you please paste the value of `dbms.directories.logs` setting and try restarting the database?

**Comment by rjgmail88** [comment]
Here is setting from conf file.

# Paths of directories in the installation.
dbms.directories.logs=/var/log/neo4j

so this confirms logs directory I 'm using is correct. I have restarted several times which didn't work.

**Comment by lutovich** [comment]
According to the debug log from the other issue, you are using neo4j-community. Query logging is only available in neo4j-enterprise. Query log file will not be generated in neo4j-community and all related settings are simply ignored. Sorry, I did not notice the community version right away.

Here is the relevant manual chapter: [link](https://neo4j.com/docs/operations-manual/current/configuration/file-locations/#file-locations-log-files)
