### ISSUE TITLE
Neo4jError: No current transaction to commit.

### ISSUE THREAD

**Issue by TheoLeanse** [neo4j/neo4j-javascript-driver#392]
`UnhandledPromiseRejectionWarning: Neo4jError: No current transaction to commit.`

Hi! I'm intermittently getting the above error when running the following code ~200k times, in parallel batches of 100:

```
const session = this.driver.session();

const tx = session.beginTransaction();

const result = await tx.run(
	query,
	params
);

if (isOK(result)) {
	tx.commit();
} else {
	tx.rollback();
}

session.close();
```

I am running this on my local machine with neo4j-driver@1.6.1, node@9.6.1, macOS@10.12.6, with a single Neo4j instance (using the 'bolt' URI scheme).

I do not experience issues using `session.run` rather than a transaction.

Any input on this would be very much appreciated, thanks!

**Comment by lutovich** [comment]
Hi @TheoLeanse,

Commit and rollback are also async operations and return a promise-like `Result` object just as `Transaction#run()` does. I think it might happen that `session.close()` jumps ahead of a commit/rollback and terminates the transaction. Then commit operation might fail. Could you please try awaiting for `tx.commit()` and `tx.rollback()` like this:

```javascript
const session = this.driver.session();

const tx = session.beginTransaction();

const result = await tx.run(
	query,
	params
);

if (isOK(result)) {
	await tx.commit();
} else {
	await tx.rollback();
}

session.close();
```

Is it possible for you to provide a small reproducer app which we can use to see the same error?

Thanks!

**Comment by TheoLeanse** [comment]
This is a great point, thanks very much for that. And yes, I will provide a reproducer app. Thanks!

**Comment by lutovich** [comment]
Hi @TheoLeanse,

Did you have a chance to try the modified code?

**Comment by TheoLeanse** [comment]
I did and it works for me - thanks very much. So I guess I can close this issue!
