### ISSUE TITLE
How to properly escape user input?

### ISSUE THREAD

**Issue by ivan-kleshnin** [neo4j/neo4j-javascript-driver#398]
I'm trying to implement filters for REST API. `Document` label will be small so I don't have to index each field and I guess this is ok:

```
let {records} = await req.db.session.run(`
  MATCH (parent:Document $filter)-[:CONTAINS]->(child:Document) 
  RETURN parent, child`, {filter})
```

Except for:

```
Parameter maps cannot be used in MATCH patterns
```

I understand this is a limitation of Cypher and why it's done like this.
So the next step is to dynamically build queries:

```
if (filter.url) {
  filterStr = `{url: "${filter}.url}"`
}
let {records} = await req.db.session.run(`
  MATCH (parent:Document ${filterStr})-[:CONTAINS]->(child:Document) 
  RETURN parent, child`)
```

which is totally exposed to injections so I need to **escape user input**.  
But how to do that properly? Which characters I have to handle? 

Is there any builtin function for that or maybe some guides on string escaping specific to Neo4j?
Surprisingly, I didn't find anything about that in docs, sources or StackOverflow :(

**Comment by lutovich** [comment]
Hi @ivan-kleshnin,

There are no built-in functions to escape Cypher values. I think you could still use query parameters like this:

1. Use `properties` function and compare all properties of a node with the given map of properties. Example:

    ```
    // Setup query:
    CREATE (:Document {url: "https://neo4j.com", age: 42})

    // Query with params to get the document:
    MATCH (d:Document) WHERE properties(d) = $props RETURN d, {props: {url: "https://neo4j.com", age: 42}}
    ```

2. Use `WITH` Cypher clause to "introduce" parameters into the query. Example:

    ```
    // Setup query:
    CREATE (:Document {url: "https://neo4j.com", age: 42})
    
    // Query with params to get the document:
    WITH $urlParam as url WITH $ageParam as age, url MATCH (d:Document) WHERE d.url = url and d.age = age RETURN d, {urlParam: "https://neo4j.com", ageParam: 42}
    ```

These approaches should remove the need to escape inputs. Second one still requires some dynamic query concatenation to create the `WITH`s prefix and `WHERE` suffix but actual values remain parameters.

Hope this helps!

**Comment by ivan-kleshnin** [comment]
Hi, Konstantin. Thanks for responding. 

1\) 

```
WHERE properties(d) = $props
```

this requires `$props` to contain all node fields which I don't think is practically reliable as `props$` will rather contain only filterable key-value pairs. 

2\) This one worked for me. For the record, it looks like this:

```
let records = await req.db.session.run(`
  WITH $filter as filter // can be introduced unconditionally, I think
  MATCH (doc)
  ${filter.url ? "WHERE doc.url = filter.url" : ""} 
  ... // other filters
  RETURN doc
`, {filter})
```
