### ISSUE TITLE
Read Transactions?

### ISSUE THREAD

**Issue by swayam18** [neo4j/neo4j-javascript-driver#404]
I have a question about `session.readTransactions` exposed by the Session object.

Other than retries of failures and auto-routing on clusters, are there other reasons we should use this over `session.run`? Does this write to the transaction log on the database?

**Comment by lutovich** [comment]
Hi @swayam18,

Transaction functions API `session.readTransaction()` and `session.writeTransaction()` perform automatic retries on transient errors. Routing in a causal cluster works for `session.run()` as well. It will use the access mode provided during session creation `driver.session(neo4j.session.READ)` or `driver.session(neo4j.session.WRITE)`. Transaction functions also allow you to run multiple statements in a single transaction. `session.run()` is just a single query in an auto-commit transaction.

Both `session.run()` and `session.[read|write]Transaction()` execute transactions against the database and are thus written to the transaction log.

You can find a bit more info about sessions and transactions in [this doc](https://neo4j.com/docs/developer-manual/current/drivers/sessions-transactions/).

Hope this helps!

**Comment by lutovich** [comment]
Hi @swayam18,

I'll close this issue now. Please feel free to update it if needed.
