### ISSUE TITLE
(1.6.3) DateTime is not yet supported as a return type in Bolt

### ISSUE THREAD

**Issue by alyxb** [neo4j/neo4j-javascript-driver#406]
- Driver version: 1.6.3
- Neo4j version: 3.4.6
- DB host: GrapheneDB

With neo4j-javascript-driver 1.6.3, getting this error when storing new `datetime()` property:

```
{ Neo4jError: DateTime is not yet supported as a return type in Bolt
    at captureStacktrace (/usr/src/org/node_modules/neo4j-driver/lib/v1/result.js:200:15)
    at new Result (/usr/src/org/node_modules/neo4j-driver/lib/v1/result.js:73:19)
    at Session._run (/usr/src/org/node_modules/neo4j-driver/lib/v1/session.js:116:14)
    at Session.run (/usr/src/org/node_modules/neo4j-driver/lib/v1/session.js:95:19)
    at upsertInfo (/usr/src/org/build/schema/database/persistence/service/InfoService.js:1:1)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) code: 'Neo.ClientError.Request.Invalid', name: 'Neo4jError' }
```

**Comment by lutovich** [comment]
Hi @jrbaldwin,

I'd expect this error to only happen when database supports `DateTime` type and driver does not, but attempts to use it. Such error is thrown when driver negotiates Bolt protocol version 1 with the database, which does not support temporal and spatial types. 1.6 driver should negotiate Bolt version 2 which supports all types.

Did you upgrade to 1.6.3 driver from some older version? Maybe `npm install` wasn't executed?

Could you please share a sample project that reproduces such error?

**Comment by alyxb** [comment]
Hi @lutovich thanks for the help, we just got word from GrapheneDB that it's an issue on their end which they're patching now. I'm closing the issue as it's not driver-related.

**Comment by bboure** [comment]
Hi @alyxb  do you know if this issue was solved?
I am getting the same error (also using GrapheneDB) and I don't know if it's an issue on my side or still on GrapheneDB.

Cheers

**Comment by alyxb** [comment]
@bboure we had to get GrapheneDB to manually upgrade our instance to latest - this was ~ 1 month ago, not sure if they're still upgrading

**Comment by bboure** [comment]
@alyxb yeah thanks, I already contacted them. They still have the issue apparently and they upgraded my instance. 
In the meantime, I also had made a clone of my DB and the new one did not have the issue.
