### ISSUE TITLE
Cannot use Point with TypeScript

### ISSUE THREAD

**Issue by sseppola** [neo4j/neo4j-javascript-driver#426]
I'm using this driver in a typescript-node project and came across this issue where TS prevents me from using the Point because the type is missing a signature for `new`.

`Cannot use 'new' with an expression whose type lacks a call or construct signature.`
![screen shot 2018-11-08 at 18 51 00](https://user-images.githubusercontent.com/4065840/48217273-41460c80-e387-11e8-9eda-7ec441de0826.png)

It's like it doesn't understand that it is a class. I solved the type issue, although hacky, by extending the Point type myself:
```
import { v1 as neo4j } from 'neo4j-driver';
import { Point as PointT } from 'neo4j-driver/types/v1/spatial-types';

const Point = neo4j.types.Point as PointT & {
  new (srid: number, x: number, y: number, z?: number): PointT;
};
```
![screen shot 2018-11-08 at 19 01 52](https://user-images.githubusercontent.com/4065840/48217851-cc73d200-e388-11e8-86c1-89f1617a487b.png)

This works and I'm now able to create Points. However, if I try to replicate the fix into `spatial-types.d.ts` with `new(srid: T, x: number, y: number, z?: number): Point;` it does not work. Would love to figure out how this can be fixed for everyone.

**Comment by lutovich** [comment]
Hi @sseppola,

Thanks for reporting the problem. It can be reproduced locally and we'll work on fixing it.

**Comment by lutovich** [comment]
Hi @sseppola,

Driver 1.7.2 with the mentioned fix is now released and available on NPM.
