### ISSUE TITLE
Incorrect offset format for DateTime

### ISSUE THREAD

**Issue by victorenator** [neo4j/neo4j-javascript-driver#427]
## Expected behaviour
`new Date().getTimezoneOffset()` returns -180 for UTC+3.
`DateTime.fromStandardDate(new Date()).toString()` should return the value `YYYY-MM-DDThh:mm:ss.ms+03:00`.

## Unexpected behaviour
`DateTime.fromStandardDate(new Date()).toString()` returns the value `YYYY-MM-DDThh:mm:ss.ms-03:00`.
 
JS [Date.getTimezoneOffset()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset#Description) returns a negative offset for the positive local timezone.

**Comment by lutovich** [comment]
Hi @victorenator,

Driver 1.7.2 with the mentioned fix is now released and available on NPM.
