### ISSUE TITLE
DB closes connection when submitting a Point

### ISSUE THREAD

**Issue by sseppola** [neo4j/neo4j-javascript-driver#431]
I'm trying to work with a 2d point, however the database does not accept it, rather it closes the connection without any more info, even if I just send a location without actually trying to insert it in the db.

Running:
neo4j-driver: v1.7.1
node.js: v8.11.3
Neo4j Community Edition 3.3.4

I tried to base my code around what is done in [the tests](https://github.com/neo4j/neo4j-javascript-driver/blob/1.7/test/v1/spatial-types.test.js#L152) and get the following:

![screen shot 2018-11-19 at 19 39 49](https://user-images.githubusercontent.com/4065840/48727692-3a46b600-ec33-11e8-8f2a-5c3bfd40f3ba.png)

I generate points using the following (in TypeScript):
```
import { v1 as neo4j } from 'neo4j-driver';
import { Point as PointT } from 'neo4j-driver/types/v1/spatial-types';

import { Neo4jIntegerT, Neo4jCompatibleIntT } from './neo4jTypes';
import { MinglRequest } from '../../types';

const Point = neo4j.types.Point as PointT & {
  new (srid: Neo4jIntegerT, x: number, y: number, z?: number): PointT;
};

const WGS84_CODE = 4326;
const WGS_84_2D_CRS_CODE = neo4j.int(WGS84_CODE);

export const createNeo4jPoint = (coords: {
  longitude: number;
  latitude: number;
}) => {
  return new Point(WGS_84_2D_CRS_CODE, coords.latitude, coords.longitude);
};
```

Then I send a batch of items and use UNWIND to iterate through and create relationships:
```
const testLocation = {
  latitude: 59.931856,
  longitude: 10.704327,
};

const testPoint = createNeo4jPoint(testLocation);
console.log(testPoint);

const scans = input.map(scan => {
  return {
    ...scan,
    Id: uuid(),
    createdAt: createNeo4jInt(scan.createdAt || Date.now()),
    location: testPoint,
  };
});

session.run(
` MATCH (user:User { Id: $viewerId })` +
  ` UNWIND $scans as scan` +
  ` MATCH (card:Card { Id: scan.cardId })` +
  ` MERGE (user)-[r:SCANNED { Id: scan.Id, createdAt: scan.createdAt }]->(card)` +
  ` RETURN r { .*, cardId: card.Id } as cardScan`,
{
  scans,
  viewerId,
})
```

Not clear what is going wrong here, please advise :)

**Comment by ali-ince** [comment]
Hi @sseppola,

Temporal and spatial (Point) types were introduced with server version 3.4.0 and can only be used with versions following. Previous server versions treat those unsupported types as protocol violations and they log a message and terminate the connection.

Please use a recent version of the server and it will work as expected. I'm closing the issue and feel free to re-open if you find any problems.

Thanks.

**Comment by sseppola** [comment]
I was not aware, thank you for the quick response :D
