### ISSUE TITLE
how to use a variable to define the length of relation ?

### ISSUE THREAD

**Issue by shaoerxixiao** [neo4j/neo4j-javascript-driver#436]
I want to use a variable to define the length of relation(for example, *..2, *..3), but obviously, this way doesn't work. Is there any solutions ?
```
const promise = session.writeTransaction(tx=>tx.run(
"MATCH (p1)-[r]-(p2) WHERE type(r)=$relation",
{
 relation: "FRIEND*..1"
}
  )
)
```

**Comment by lutovich** [comment]
Hi @shaoerxixiao,

Labels and relationship types can't be used as query parameters because they are used for query planning. I think the best option is to concatenate query strings in the application code.

Hope this helps!

**Comment by shaoerxixiao** [comment]
Hello,
Thanks for your response.
I've solved the problem with APOC.
Happy new year!

**Comment by lutovich** [comment]
Hey @shaoerxixiao!

Happy New Year! 🎄
Could you please share your APOC-based solution here for future reference?

Thanks in advance!

**Comment by shaoerxixiao** [comment]
OK, you have raison. I've used apoc.path.expand to make the relationship as parameter.
````
const statement = [
  'match (p1:Person {uid: $uid})',
  'call apoc.path.expand(p1, $directedRelationship,"Person",1,$nLayer) yield path as pp',
  'return pp'
  ]
params = {
  uid: "abc",
  directedRelationship: "KNOWS>",
  nLayer: 2
}

const session = driver.session()
const promiseResult = session.run(statement.join(' '), params)
```

**Comment by lutovich** [comment]
Thanks @shaoerxixiao!
