### ISSUE TITLE
Different results with calling neo4j function in neo4j browser V.S. neo4j driver via bolt

### ISSUE THREAD

**Issue by yuanzhou** [neo4j/neo4j-javascript-driver#441]
I'm using Neo4j version 3.5.1. 

When I call a neo4j function in neo4j broswer using `return functionName()` I get the JSON returned like this:

````
{
  "x": 20,
  "y": 34,
  "name": "myNode"
}
````

But when I call the same cypher query in neo4j js driver via bolt, I got the following:

````
{
  "x": {
    "low": 20,
    "high": 0
  },
  "y": {
    "low": 34,
    "high": 0
  },
  "name": "myNode"
}
````

Has anyone encountered this difference? I had to convert the integers to strings in my Java code when writing the neo4j user-defined functions to work around this. Does this imply the js driver doesn't handle integer properly?

**Comment by zhenlineo** [comment]
Hi @yuanzhou, you shall be able to find answers to all your questions [here](https://github.com/neo4j/neo4j-javascript-driver#a-note-on-numbers-and-the-integer-type).

**Comment by yuanzhou** [comment]
Thanks @zhenlineo, the documentation doesn't say clearly about what the internal integer type is represented in the JS neo4j driver. Is `{"low": n, "high": 0}` the internal integer type for the integer value n of the Neo4j type system?

It also sounds like when I use this driver, I'll need to know which value is an integer and explicitly parse it using `neo4j.integer.toNumber` ?
