### ISSUE TITLE
1.7 to 2.0 Using browser only module in Node.js code (ReferenceError: btoa is not defined)

### ISSUE THREAD

**Issue by AxolotlxWando** [neo4j/neo4j-javascript-driver#458]
### Summary
I connect to neo4j from a Node.js server, all access to neo4j are from within Node and a GraphQL interface built on top that clients access with. I use bolt connection usually but there were this one time that I **connect to the http REST endpoint from inside Node.js** and the query crashed on ReferenceError: btoa is not defined error.

### Cause
btoa() is browser only... reference to the global function btoa:
```
bash-4.4$ ack btoa
src/v1/internal/http/http-request-runner.js
126:  headers.append('Authorization', 'Basic ' + btoa(authToken.principal + ':' + authToken.credentials));
```

will fail with the reference error, it looks like the HTTP protocol part of the JavaScript driver is using the same code from the client side code :)

### Effected
- When using HTTP connection with JavaScript Driver
- From the 1.7 version I was using to current 2.0

### Environment
- Node.js v8.12
- Driver version: JavaScript driver 1.7
- Neo4j version: Community 
- Neo4j Mode: Single instance over docker on custom port 17474 and 17687
- Operating system: Fedora 28

**Comment by AxolotlxWando** [comment]
I've hacked my local copy by adding an community btoa module and a global definition.
It feels really wrong, anyone more experienced for to advice?

```
var _btoa = require('btoa');
if (typeof btoa === 'undefined') {
  global.btoa = _btoa;
}
```

**Comment by ali-ince** [comment]
Hi @ChingxWando,

Thanks for reporting this issue, however the HTTP endpoint support is an _undocumented_ and _unsupported_ feature which was basically introduced for use by our internal tools - and it was never intended to be used in a `node` environment. Furthermore, we can even remove it completely in upcoming releases.

We're not willing to add an additional runtime dependency for this feature and thus I'm closing the issue with a `wontfix`.
