### ISSUE TITLE
[Feature Request] support observable spec on Query Result

### ISSUE THREAD

**Issue by jameslaneconkling** [neo4j/neo4j-javascript-driver#468]
Would be nice if the the query result supported the current observable interface so that it is compatible with libraries like RxJS v5+ (RxJS v6 is the current stable version, and v7 is in beta).

E.g. in the following code, rxjs v6.5.2 throws `TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.`
```javascript
from(session.run(QUERY)).pipe(
  map((result) => { ... })
).subscribe({
  next: (data) => console.log(data),
  error: (err) => console.error(err),
  complete: () => console.log('complete')
})
```
and I assume other observable libraries like XStream, Most, etc, would have similar issues.

Looks like the current implementation is built against the older observable spec (e.g. uses the `onNext`/`onError`/`onComplete` handlers, see [here](https://github.com/ReactiveX/rxjs/blob/5.x/MIGRATION.md)).  [This library](https://github.com/benlesh/symbol-observable) can be useful in generating spec-compliant observables.

Also, looks like the subscribe method returns void, whereas to be spec compliant it should return a Subscription object with an `unsubscribe` method to close the stream and automatically clean up resources.

**Neo4j Version:** 3.5 Enterprise
**Neo4j Mode**: Single instance  
**Driver version**: JS driver 1.7.5
**Operating System:** N/A

**Comment by technige** [comment]
Reactive support will come later this year.

**Comment by zhenlineo** [comment]
Hi @jameslaneconkling ,

Thanks very much for your input. We've added the rxjs API in our latest 4.0.0-beta01 release. You are most welcome to try out our new API and give us your valuable inputs. The reactive API requires the latest 4.0 server too.

Cheers,
Zhen
