### ISSUE TITLE
[Feature Request] Record map

### ISSUE THREAD

**Issue by thebestnom** [neo4j/neo4j-javascript-driver#469]
hi, I would like to add a suggestion that Record will have a map function, it's already have forEach so I think its not too difference.
my use case is doing async stuff inside the forEach and I want to await there

``` javascript
const promises = recored.map(async (v) => {
   // ... stuff
   await stuff(v)
   //... more stuff
})
await Promise.all(promises)
``` 
which I cant do with forEach,
what I did instead for now is
``` javascript
const promises = Object.values(record.toObject()).map(async (v) => {
   // ... stuff
   await stuff(v)
   //... more stuff
})
await Promise.all(promises)
```

which is kinda hack

**Comment by zhenlineo** [comment]
Hi @thebestnom , thanks very much for you input. We've added this as a new feature in 4.0 drivers. You can try this feature out with our latest 4.0.0-beta01 and later drivers.
