### ISSUE TITLE
Why result is converted to Result type

### ISSUE THREAD

**Issue by duoduoObama** [neo4j/neo4j-javascript-driver#487]
The data requested by the interface and why it is converted to the data of the Result type, I want the original data after the interface request, how to get it, can you ask? Thank you

![image](https://user-images.githubusercontent.com/30836806/64601742-189c0280-d3f0-11e9-942c-943117392bda.png)
![image](https://user-images.githubusercontent.com/30836806/64601781-2782b500-d3f0-11e9-9a3a-e7a01602b36d.png)

**Comment by duoduoObama** [comment]
please help me ,Thank you very much for your answer.

**Comment by ali-ince** [comment]
Hi @duoduoObama,

Cloud providers usually expose a limitation on how long an idle connection should be kept alive. For this, we have `maxConnectionLifetime` setting that has the default value of `1h` and could be fine tuned to fit for your own infrastructure requirements. For more information on connection pool management and the related configuration options, please take a look at the documentation which is available [here](https://neo4j.com/docs/driver-manual/current/client-applications/#driver-config-connection-pool-management).

As another layer of protection, you can also make use of [transaction functions](https://neo4j.com/docs/driver-manual/current/sessions-transactions/#driver-transactions-transaction-functions) which provides built-in retry functionality for transient errors, such as connection failures.

**Comment by duoduoObama** [comment]
Hi @ali-ince ,My problem is to connect to the data network, the data is converted into the Records data entity, I want to get the raw data in the network, I did not find in the document,My problem is to connect to the data network, the data is converted into the Records data entity, I want to get the raw data in the network, I did not find in the document

**Comment by ali-ince** [comment]
Hi @duoduoObama, unfortunately I cannot follow your problem. 

Please clean-up the issue description above and describe your problem cleanly so that we can figure out what you're doing and what's your expectations are, preferably enriched with reproducable code blocks.

Besides, I can see that you're using our _internal_ and _experimental_ http driver support which is _not supported_ and already removed in upcoming 4.0 version.

**Comment by zhenlineo** [comment]
Hi @duoduoObama,

First this driver is built on top of our in-house binary protocol BOLT. It does not support connecting to server via HTTP endpoints such as `http://localhost:7474`. Instead you shall connect to driver via BOLT protocol `bolt://localhost:7687` instead. 

BOLT is a binary protocol, so if you want the raw format of the data, you will get binaries like 0101010101010000. I assuming you want the json format of the result. There are method called `Record#toObject` which will help you convert result to a map.


首先，该驱动程序建立在我们内部二进制协议BOLT之上。 它不支持通过HTTP端点（例如“http://localhost:7474” ）连接到服务器。 相反，您应该改为通过BOLT协议“bolt://localhost:7687”连接到驱动程序。

BOLT是一种二进制协议，因此，如果您想要数据的原始格式，则会得到类似于0101010101010000的二进制结果。我假设您想要结果的json格式，有一个 `Record#toObject` 的方法，可以帮助您将结果转换为map。

Read more https://neo4j.com/docs/driver-manual/current/get-started/

Cheers,
Zhen
