### ISSUE TITLE
Types missing for custom resolver

### ISSUE THREAD

**Issue by kimroen** [neo4j/neo4j-javascript-driver#489]
As [documented here](https://neo4j.com/docs/driver-manual/current/client-applications/#_cluster_bootstrap_address_resolution) and [added to this library here](https://github.com/neo4j/neo4j-javascript-driver/pull/418), when creating a driver you can pass in a custom resolver:

```ts
import neo4j from 'neo4j-driver';

const driver = neo4j.driver(
  'my-uri',
  neo4j.auth.basic('username', 'password'),
  {
    resolver: address => ['my', 'array', 'of', 'addresses'],
  },
);
```

With the current types, this doesn't work. You are told that `resolver` isn't a known property on `Config`.

This seems fair enough, because we can see that this is the case in the type definition here:

https://github.com/neo4j/neo4j-javascript-driver/blob/c8d2ad9db1e02b5c93a0325bf5bbbd998f35e076/types/v1/driver.d.ts#L50-L66

This `resolver` function isn't used immediately anywhere, it happens quite far away from the constructor. I'm guessing that the resolver referenced here is the one we're looking for:

https://github.com/neo4j/neo4j-javascript-driver/blob/d876a45a3fda80d9c8688771e892e0b758b9f701/src/internal/resolver/configured-custom-resolver.js#L30-L41

If so, the definition should be something like this, allowing either an array of strings or a promise resolving to an array of strings:

```ts
declare interface Config {
  ...
  resolver?: (address: string) => Promise<string[]> | string[]
}
```

Hope that's useful!

**Comment by zhenlineo** [comment]
Thanks very much for reporting this. We will plan a release to includes the fixes soon.
