### ISSUE TITLE
Types missing for config.connectionAcquisitionTimeout

### ISSUE THREAD

**Issue by owme** [neo4j/neo4j-javascript-driver#493]
Documented [here](https://neo4j.com/docs/driver-manual/current/client-applications/#driver-config-connection-pool-management), when creating a driver you can pass in a connectionAcquisitionTimeout property in your connection pool settings:
```javascript
import neo4j from neo4j-driver;

const driver = neo4j.driver(uri, neo4j.auth.basic(user, password), {
  ...
  connectionAcquisitionTimeout: 2 * 60 * 1000 // 120 seconds
})
```
Similarly to #489, the current types don't contain the `connectionAcquisitionTimeout` property in the Config interface of the driver.d.ts:
https://github.com/neo4j/neo4j-javascript-driver/blob/c8d2ad9db1e02b5c93a0325bf5bbbd998f35e076/types/v1/driver.d.ts#L50-L66

Here is the corresponding integration of `connectionAcquisitionTimeout`:
https://github.com/neo4j/neo4j-javascript-driver/blob/5a77aacd6fbcdbe44e525204ef171aab9ee5a549/src/internal/pool-config.js#L36-L49

The change should probably look like this:
```javascript
declare interface Config {
  ...
  connectionAcquisitionTimeout?: number
}
```
Hope this helps. :)

**Comment by martin-neotech** [comment]
```
30b689a7 types/driver.d.ts    (Zhen Li     2019-10-17 16:11:28 +0200  56)   connectionAcquisitionTimeout?: number
```

https://github.com/neo4j/neo4j-javascript-driver/commit/30b689a7167f010a455d6da9bd83e8414b55e2e8
