### ISSUE TITLE
[Feature Request] reactive back pressure signals

### ISSUE THREAD

**Issue by Diachk** [neo4j/neo4j-javascript-driver#505]
As a follow up on a previous issue #271 that has been closed.
The PR https://github.com/neo4j/neo4j-javascript-driver/pull/475 takes advantage of the back pressure mechanism exposed via bolt but does not expose it to the subscriber as a Controlled or Pausable observable neither does it produce a subscription interface described by the [reactive streams effort](https://github.com/reactive-streams/reactive-streams-js/).

The issue is clear about what interfaces are needed but the PR seems to resolve it partially, Is there any plan to implement those interfaces ?

**Comment by zhenlineo** [comment]
Hi @Diachk,

We expose our reactive API via [rxjs](https://github.com/ReactiveX/rxjs). It provides far more richer functions than the raw reactive API.

You can try out our reactive API with our rc1 release. You can get a reactive session via `driver.rxSession` method. We are still working on documentation at this moment, will let you know once the docs are ready.

Cheers,
Zhen
