### ISSUE TITLE
Can readTransaction and writeTransaction after a session.close()?

### ISSUE THREAD

**Issue by kevpogo** [neo4j/neo4j-javascript-driver#506]
With my NestJs application, I want to create a Session by request and close it at the end of client request of my API.
Unfortunately, I try this:
```
let session = this.neo4j.session();
session.close();
session.readTransaction(tx=>...);
```
And it works... I have my data. 
What is the mechanism behind all this? readTransaction and writeTransaction reopen the session? How can be sure to close really a session?
Regards.

**Neo4j Version:** 3.5.3
**Neo4j Mode**: Single instance  
**Driver version**: JS driver 1.7.6
**Operating System:** Linux Mint 19.2

### Steps to reproduce

1. Create a session
2. Close it
3. Run a query with readTransaction or writeTransaction
4. Look the result

### Expected behavior

Throw exception?

### Actual behavior

I don't know... I think readTransaction or writeTransaction reopen session.

**Comment by technige** [comment]
The `close` method will simply ensure that all open resources are correctly shut down and released, but there is no intention to set the session into a permanently unusable state thereafter. Typically, a client application may dispose of the session reference immediately after a close, but there is no hard requirement to do so, and if the session continues to be used, we will honour that.

**Comment by kevpogo** [comment]
Ok, so how do I do if I want to open a session in for every request from my API? Is it a good practice?

**Comment by zhenlineo** [comment]
Hi @kevpogo,

As @nigelsmall said that we did not give a clear definition of what happens after session is closed in 1.7. However in 4.0, we now defined that it is the end of the session. If you use the session after a session is closed, then you will get an error.

Currently we have no plan to backport this change into 1.7.

Zhen

**Comment by kevpogo** [comment]
Ok, thank's. So I have no certainty that the session is closed after calling ```session.close()``` (in 1.7)?

**Comment by zhenlineo** [comment]
Hi @kevpogo,
I would suggest to do `session = null` to enforce an error if this session is being used afterwords.

Also I would like to mention that session is very lightweight. If you do not run with a cluster and need causal consistency between two transactions, there is certainly no need to keep a session around for more than one transactions. You can just do create a new session on demand and then only return handled data from your functions.

Cheers,
Zhen

**Comment by mehdikwa** [comment]
Hello,

If the session is still alive after closing it, will it mean that the session keeps an opened slot in the pool of connections and affects number of threads used in the cluster ? We are experiencing this behavior in a sense where we open a connexion for every function and closing it after return. But seems threads on server keeps increasing till overloading CPU usage.

**Comment by zhenlineo** [comment]
Hi @mehdikwa,

In 1.7, if you give a callback in `session.close(callback)`, then once the callback is done, then all session resources (such as connections) are all released (return to a connection pool on driver).

The threads used on server is not strictly related to the connections the Neo4j server handles. Also the server has many thread pools besides the pool used by bolt server. If you want to change the default thread pool settings of bolt server, [here](https://neo4j.com/docs/operations-manual/current/performance/bolt-thread-pool-configuration/) are some instructions to change them.
