### ISSUE TITLE
Connecting to Aura in v4.0 not working with bolt+routing or neo4j or just bolt

### ISSUE THREAD

**Issue by sebastiangug** [neo4j/neo4j-javascript-driver#511]
If I try to connect with bolt, I'm hit with:

```
 Neo4jError: Connection was closed by server
``` 

with neo4j:
```
 Neo4jError: Could not perform discovery. No routing servers available
```

with bolt+routing:
```
Error: Unknown scheme: bolt+routing
```

With the previous version just days ago I had no issues connecting with bolt+routing. 

I've got no idea what I could possible try to get this to work.

**Comment by sebastiangug** [comment]
If I set the connection acquisition timeout in the driver config, it will connect but it will not let me write and will return an error saying it's a 'FOLLOWER' and cannot write to it.

**Comment by sebastiangug** [comment]
connecting with neo4j works, turns out it was the default encryption being set to off.

Correct connection string for anyone stumbling on this:

```
export const Neo4jConn = (): neo4j.Driver => {
  return neo4j.default.driver(
    process.env['neo4j-endpoint'],
    neo4j.auth.basic(
      process.env['neo4j-write-user'],
      process.env['neo4j-write-key'],
    ),
    {
      encrypted: true,
    },
  );
};

```

**Comment by zhenlineo** [comment]
Hi, you can have a look at our [break change section](https://www.npmjs.com/package/neo4j-driver#breaking-changes), you will find that the `bolt+routing` is now named `neo4j`.

**Comment by sebastiangug** [comment]
@zhenlineo  if you can have a look at my first comment, I mentioned how my issue was connecting with any of the mentioned protocols, as well as `neo4j` -- I thought I'd try the other ones as well just to be 100% sure.
