### ISSUE TITLE
Can we have a Changelog?

### ISSUE THREAD

**Issue by emregency** [neo4j/neo4j-javascript-driver#513]
Hey all,

Thanks for keeping the library up-to-date!

Is it possible to have some sort of a changelog? Even few words would be great. Otherwise, I need to go through the commits and the diffs before updating my packages.

**Comment by zhenlineo** [comment]
Hi @emregency,

Is this good enough?
[changelog](https://github.com/neo4j/neo4j-javascript-driver/wiki/4.0-changelog)
Also we have a very simple guide [what's new](https://github.com/neo4j/neo4j-javascript-driver#whats-new) and [breaking changes](https://github.com/neo4j/neo4j-javascript-driver#breaking-changes)

**Comment by emregency** [comment]
That’s amazing! I was just looking in release or a changelog.md 

I didn’t think to look into wiki sorry @zhenlineo
