### ISSUE TITLE
"Unknown Bolt protocol version: 0" when connecting to Neo4j 3.5.5 Community

### ISSUE THREAD

**Issue by ryanmeador** [neo4j/neo4j-javascript-driver#514]
**Neo4j Version:** 3.5.5 Community (provided via GrapheneDB Heroku addon)
**Neo4j Mode**: Single instance  
**Driver version**: JS driver 4.0.1
**Operating System:** Heroku (heroku-18)

### Steps to reproduce

1. Run the following test script via `heroku local:run node ./test.js`:
```javascript
const neo4j = require('neo4j-driver');

const graphenedbURL = process.env.GRAPHENEDB_BOLT_URL;
const graphenedbUser = process.env.GRAPHENEDB_BOLT_USER;
const graphenedbPass = process.env.GRAPHENEDB_BOLT_PASSWORD;

const options = {
  encrypted: true
};

const driver = neo4j.driver(graphenedbURL, neo4j.auth.basic(graphenedbUser, graphenedbPass), options);

driver.verifyConnectivity()
  .then((result) => {
    console.log("Verify success", result);
  })
  .catch((error) => {
    console.log("Verify error", error);
  });
````

### Expected behavior

It prints "Verify success"

### Actual behavior

```
Verify error { Neo4jError: Unknown Bolt protocol version: 0
    at newError (<redacted>/node_modules/neo4j-driver/lib/error.js:67:10)
    at ProtocolHandshaker._createProtocolWithVersion (<redacted>/node_modules/neo4j-driver/lib/internal/protocol-handshaker.js:120:37)
    at ProtocolHandshaker.createNegotiatedProtocol (<redacted>/node_modules/neo4j-driver/lib/internal/protocol-handshaker.js:93:19)
    at NodeChannel._this3._ch.onmessage (<redacted>/node_modules/neo4j-driver/lib/internal/connection-channel.js:184:51)
    at TLSSocket.<anonymous> (<redacted>/node_modules/neo4j-driver/lib/internal/node/node-channel.js:204:16)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17) code: 'N/A', name: 'Neo4jError' }
```

### Discussion

Is this driver version meant to work with this server version?  The main page says "A database driver for Neo4j 3.0.0+." so I believe it should work, but the nature of the error suggests otherwise.  I'm only a few point releases behind the latest (3.5.14) and I don't see anything about this in the release notes, so I'd rather not upgrade the database until I know it will solve this problem.

I have to use the `encrypted: true` option to connect to this server, otherwise I get "Connection was closed by server".

My understanding of the Bolt protocol indicates the [current version](https://boltprotocol.org/v1/#handshake) is 1.  I find it curious that this code exists in `protocol-handshaker.js` (cf. stack trace above):
```javascript
function newHandshakeBuffer() {
  var handshakeBuffer = (0, _node.alloc)(5 * 4); // magic preamble

  handshakeBuffer.writeInt32(BOLT_MAGIC_PREAMBLE); // proposed versions

  handshakeBuffer.writeInt32(4);
  handshakeBuffer.writeInt32(3);
  handshakeBuffer.writeInt32(2);
  handshakeBuffer.writeInt32(1); // reset the reader position

  handshakeBuffer.reset();
  return handshakeBuffer;
}
```

I think that means the driver is saying it supports versions 4, 3, 2, and 1.  But only version 1 exists, so how can it support the others?

Thank you for your assistance with this issue.

**Comment by zhenlineo** [comment]
Hi @ryanmeador,

The driver shall not have any problem to connect to a remote neo4j 3.5 server. We have full test coverage for 4.0 js driver to support Neo4j 4.0, 3.5, 3.4, 3.3. 

As a result, I would think it might be Heroku or GrapheneDB has some wrong settings to answer supported Bolt versions wrongly. As you pointed out in the code, the current js driver supports Bolt V4 to V1. For the server side, the supported highest Bolt versions are show as bellow:
Neo4j 3.5: Bolt V3
Neo4j 4.0: Bolt V4

However you receives 0 in the reply, which indicates that the remote server does not support any Bolt V4 to Bolt V1. A normal 3.5 Neo4j would have replied 3 as that is the highest supported Bolt version. It means either Heroku or GrapheneDB are parsing bolt messages and reply on behalf of a Neo4j server.

I would suggest you raise an issue with GrapheneDB or Heroku instead. Or you can have a look at  [Aura](https://neo4j.com/aura/).

**Comment by ryanmeador** [comment]
Thank you for your assistance.  I will raise the issue with them.

**Comment by ryanmeador** [comment]
Graphene support (contacted via Heroku support) was able to resolve the issue. They indicated it affected multiple (all?) servers and they deployed a fix for it today.
