### ISSUE TITLE
Cannot Query: "Could not perform discovery. No routing servers available."

### ISSUE THREAD

**Issue by Bestulo** [neo4j/neo4j-javascript-driver#516]
## Details

- Neo4j version: Community 3.5.13
- Neo4j Mode: Single instance
- Driver version: Nodejs driver 4.0.1
- Operating system: Debian 9

## My code:

```js
const config = {
  "neo4j": {
    "url": "neo4j://localhost",
    "authUser": "neo4j",
    "authKey": "adminPassword"
  }
}
const neo4j = require("neo4j-driver");
const driver = neo4j.driver(
  config.neo4j.url,
  neo4j.auth.basic(config.neo4j.authUser, config.neo4j.authKey)
);

session
  .run(`CREATE (user:User { username: "@bestulo" })`)
  .then(r => {
    console.log("r: ", r);
    session.close();
    driver.close();
  })
  .catch(console.error);
```

## The error:

```js
{ Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1577163952726, routers=[], readers=[], writers=[]]

    at captureStacktrace (/home/nim/projects/node/doggo/node_modules/neo4j-driver/lib/result.js:263:15)
    at new Result (/home/nim/projects/node/doggo/node_modules/neo4j-driver/lib/result.js:68:19)
    at Session._run (/home/nim/projects/node/doggo/node_modules/neo4j-driver/lib/session.js:172:14)
    at Session.run (/home/nim/projects/node/doggo/node_modules/neo4j-driver/lib/session.js:135:19)
    at Object.<anonymous> (/home/nim/projects/node/doggo/index.js:24:4)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12) code: 'ServiceUnavailable', name: 'Neo4jError' }
```

**Comment by gjmwoods** [comment]
Hi @Bestulo, Thanks for the issue and for providing all the details.

The issue is compatibility between the `neo4j://` scheme and v3 of the server. `neo4j://` was introduced in v4 as a service level abstraction URI and replacement for `bolt+routing://`. Since routing is not needed for a single instance, v3 of the server doesn't return this routing information.

There are a couple of ways to fix this:

1) You can use the `bolt://` scheme. 
2) Upgrading the server to v4

We will make this compatibility issue clearer in the documentation for v4.

Cheers
Greg

**Comment by dryhurst** [comment]
hi. it's 2022 and i am getting `Could not perform discovery. No routing servers available.` issue using nest-neo4j when trying to connect to Aura with this connection string: 

```ts
@Module({
  imports: [
    Neo4jModule.forRoot({
      scheme: 'neo4j',
      host: 'neo4j+s://<REDACTED>.databases.neo4j.io',
      port: 7687,
      username: 'neo4j',
      password: '<REDACTED>',
    }),
  ],
  controllers: [IncidentsController],
  providers: [IncidentsService],
})
```

what should i do about this?

**Comment by timurgen** [comment]
Same issue while using Aura 
`Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1646215135971, routers=[], readers=[], writers=[]]` 
It just happens sometimes

**Comment by gjmwoods** [comment]
@dryhurst I see that you were successful in reaching out in the nest-neo4j repo for this issue: https://github.com/adam-cowley/nest-neo4j/issues/9. Please let us know, by openning a separate ticket, if you need further help.

@timurgen Please open a separate ticket on the repository with all the requested information.

**Comment by MaximCamilleri** [comment]
> Same issue while using Aura `Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1646215135971, routers=[], readers=[], writers=[]]` It just happens sometimes

hi, i am having this exact issue. Was this ever expanded upon?

**Comment by rthennan** [comment]
> Same issue while using Aura `Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1646215135971, routers=[], readers=[], writers=[]]` It just happens sometimes

For Aura, please check ['Could not perform discovery. No routing servers available' while connecting to an Aura DB instance from Neo4j browser'](https://aura.support.neo4j.com/hc/en-us/articles/5290730835859--Could-not-perform-discovery-No-routing-servers-available-while-connecting-to-an-Aura-DB-instance-from-Neo4j-browser)

**Comment by roshanis** [comment]
Same issue on a brand new aura instance for a simple csv import.

**Comment by gjmwoods** [comment]
Hi @roshanis. Please open a new ticket with the requested information. The issue you are experiencing may not be the same as the one originally opened and we need to know all those details to help get to the bottom of it.

**Comment by Nesqui** [comment]
> 

![image](https://user-images.githubusercontent.com/41809155/179762786-43469309-2c93-4102-9cb5-ea8f7c650304.png)

Some popular package use this string for neo4j driver

Try this, thats solve my same problem

![image](https://user-images.githubusercontent.com/41809155/179763210-1f7f97c4-6551-4104-9dc4-b4de145c1d5f.png)

**Comment by 123Peter789** [comment]
> Hi @Bestulo, Thanks for the issue and for providing all the details.
> 
> The issue is compatibility between the `neo4j://` scheme and v3 of the server. `neo4j://` was introduced in v4 as a service level abstraction URI and replacement for `bolt+routing://`. Since routing is not needed for a single instance, v3 of the server doesn't return this routing information.
> 
> There are a couple of ways to fix this:
> 
> 1. You can use the `bolt://` scheme.
> 2. Upgrading the server to v4
> 
> We will make this compatibility issue clearer in the documentation for v4.
> 
> Cheers Greg

Thanks @gjmwoods for pointing to that topic with only one instance. For me it helped to use `bolt+s` instead of `neo4j+s` like mentioned here: [https://aura.support.neo4j.com/hc/en-us/articles/3600...](https://aura.support.neo4j.com/hc/en-us/articles/360041294913-Error-when-connecting-to-Neo4j-Aura-Error-code-ServiceUnavailable-name-Neo4jError-). 

![image](https://user-images.githubusercontent.com/16413100/184629362-b2ae3a25-47ad-4b7b-b219-51142fba0ba9.png)
