### ISSUE TITLE
Neo4j list of ID to Javascipt integer array

### ISSUE THREAD

**Issue by LeMoussel** [neo4j/neo4j-javascript-driver#518]
Hi,

With Neo4j [pattern comprehension](https://neo4j.com/docs/cypher-manual/current/syntax/lists/#cypher-pattern-comprehension), I got a list of ID based on matchings of a pattern. 

**Example based on the movies dataset:**
```
MATCH (p:Person)
WHERE p.name = "Jessica Thompson"
RETURN [(s)<--(t) | ID(t)] as inNeighbors, [(s)-->(t) | ID(t)] as outNeighbors
```

**Exported JSON result in Neo4j Browser:**
> [
>   {
>     "inNeighbors": [
>       1418,
>       884,
>       63,
>       198,
>       84,
>       884,
>       1089,
>       198,
>       198,
>       848,
>  .....
>     ],
>     "outNeighbors": [
>       1627,
>       253,
>       62,
>       73,
>       419,
>       1065,
>       1398,
>       414,
>       1386,
>       1370,
>       371,
> .....
>     ]
>   }
> ]

`record.get('inNeighbors')`
>Array() [{ low: 1418, high: 0 }, { low: 884, high: 0 }, .... ]

In JS, How Can I get an array of Integers?
Do I make a foreach loop on inNeighbors array with use of [toNumber()](https://github.com/neo4j/neo4j-javascript-driver#reading-integers) to get each values as integer?

**Comment by martin-neotech** [comment]
> Example 4.1. Map Neo4j types to native language types - JavaScript

> * JavaScript has no native integer type so a custom type is provided. For convenience, this can be disabled through configuration so that the native Number type is used instead. Note that this can lead to a loss of precision.

https://neo4j.com/docs/driver-manual/1.7/cypher-values/#driver-neo4j-type-system

**toInt() is not mentioned in** https://github.com/neo4j/neo4j-javascript-driver/tree/1.7#read-integers

```
toInt(): numberConverts the Integer to an exact javascript Number, assuming it is a 32 bit integer. 

toNumber(): numberConverts the Integer to a the nearest floating-point representation of this value (double, 53 bit mantissa). |  

toString(radix: number=): stringConverts the Integer to a string written in the specified radix.
```

**JavaScript API:** https://neo4j.com/docs/api/javascript-driver/1.7/class/src/v1/integer.js~Integer.html

```
var x = [neo4j.int(1), neo4j.int(2), neo4j.int(3)]

for(var i=0; i < x.length; i++){
  console.log(x[i]);
  console.log(x[i].toInt());
}
```

```
y = neo4j.int(123)
> Integer {low: 123, high: 0}

y.toInt()
> 123
```
```
x = neo4j.int(Number.MAX_SAFE_INTEGER+123)
> Integer {low: 122, high: 2097152}

x.toInt()
> 122

x.toNumber()
> 9007199254741114
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number

So depending on what data ranges of Integers you are working on you can choose using the native representation or the neo4j.int
