### ISSUE TITLE
Runaway Promises on session.writeTransaction()

### ISSUE THREAD

**Issue by Kefa7y** [neo4j/neo4j-javascript-driver#526]
When using the Bluebird package as a the global Promise engine, I keep on getting Runaway Promise warning on session.writeTransaction(). I have recently upgraded from Neo4j v3.5 to v4.0, so I had to upgrade the Neo4j driver as well. This issue does not occur with session.run() nor with session.beginTransaction().

### System Info
- Neo4j version: Enterprise 4.0.0
- Neo4j Mode: Single instance
- Driver version: Javascript lanaguage driver 4.0.1
- Operating system: Ubuntu 18.04 on local machine (laptop)
- Bluebird.js version: 3.5.5

### Steps to reproduce

1. Start the dockerized Neo4j conrainer 
2. Setup a Node.js server
3. Install Bluebird.js and use it as the global promise engine (instructions on their website)
4. Install the Neo4j javascript driver v4.0.1
5. Run a MERGE/SET query with the session.writeTransaction() function

### Stacktrace
`Warning: a promise was created in a handler at domain.js:131:23 but was not returned from it, see http://goo.gl/rRqMUw
    at Promise.then (<redacted>/node_modules/bluebird/js/release/promise.js:154:17)`

**Comment by timsaval** [comment]
Any update on this? It prevents us from upgrading to neo v4.0.0
@lutovich maybe you can fast track this? Thanks!

**Comment by lutovich** [comment]
Hi @timsaval,

Sorry, I will not be able to help because I no longer work on this driver.
@nigelsmall would be the best point of contact regarding this problem.

Cheers!

**Comment by timsaval** [comment]
@lutovich thank you either way!

**Comment by a-tokyo** [comment]
Any news on this? 🚀 

@nigelsmall Would really appreciate your help!

**Comment by martin-neotech** [comment]
**Please submit a code snippet for the step 5. Run a MERGE/SET query with the session.writeTransaction() function**

https://neo4j.com/docs/api/javascript-driver/4.0/class/src/session.js~Session.html

http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

I guess that you are not returning anything in your transaction function.

Example that returns a Promise:

```
// Create a person node
function addPerson (tx, name) {
  result = tx.run('CREATE (a:Person {name: $name})', { name: name })
  return result.keys()  # return a Promise
}
session.writeTransaction(tx => addPerson(tx, 'Alice')))
```

**Comment by Kefa7y** [comment]
@martin-neotech We are actually returning results from our functions. Furthermore, this issue only appeared when upgrading to the neo4j js driver v4.0.1. It used to work just fine without errors for multiple older driver versions.

Here is a (slightly modified) code snippet that is pulled from our code:
```js
function getUserCount() {
  const session = driver.session();
  const statement = `
    MATCH (user: User)
    RETURN COUNT(user)`;

  return session
    .readTransaction((tx) => tx.run(statement))
    .then((result) => {
      session.close();
      const count = result.records[0]._fields[0];
      return count;
    })
    .finally(() => session.close());
}
```
As you can see, we do not leave runaway promises with our code, not even in insert functions. I firmly believe that this is an issue in the driver itself that started with the v 4.x updates. Could you please investigate into the matter?

**Comment by martin-neotech** [comment]
@Kefa7y The changelog https://github.com/neo4j/neo4j-javascript-driver/wiki/4.0-changelog#400-alpha04 mentions that

> Updated `driver.close()` and `session.close()` to return Promises rather than relying on callbacks

try something like this:

```
function getUserCount() {
  const session = driver.session();
  const statement = `MATCH (user: User) RETURN COUNT(user)`;

  return session
    .readTransaction((tx) => tx.run(statement))
    .then((result) => {
      const count = result.records[0]._fields[0];
      session.close(); // close the session after the result have been consumed
      return count;
    })
    .catch((err) => {
      console.error(error);
      session.close();
      return -1;
     });
}
```

**Comment by bigmontz** [comment]
Closing issue due inactivity. Please, re-open the issue if the issue persists.
