### ISSUE TITLE
Not compatible with your operating system or architecture: fsevents@1.2.11

### ISSUE THREAD

**Issue by himanshush200599** [neo4j/neo4j-javascript-driver#527]
Not compatible with your operating system or architecture: fsevents@1.2.11 showing this error when i am trying to install neo4j-driver using npm.
I am running the command -  npm install neo4j-driver

I am using ubuntu 18.04 LTS  with laptop dell 3542 
logs are - 

>  npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.11
> npm WARN devconnector@1.0.0 No repository field.

**Comment by oskarhane** [comment]
What node version are you using @himanshush200599 ?

**Comment by himanshush200599** [comment]
@oskarhane I am using node version v8.10.0.

**Comment by oskarhane** [comment]
@himanshush200599 Try using at least version 10 and see if that works better.
