### ISSUE TITLE
RxResult's summary method is not there

### ISSUE THREAD

**Issue by snurby7** [neo4j/neo4j-javascript-driver#531]
I'm trying to run a simple delete query using the latest reactive session API with `neo4j-driver@4.0.1` using node 12.12.0. 

Example of the query I am trying to run 

```
MATCH (n)
DETACH DELETE n
```

The way I'm running this is the following. I'm getting an RxSession from the driver

```js
rxSession.writeTransaction(trx =>
  trx
    .run(statement)
    .summary() // fails on this line
    .pipe(
       map(result => ({ message: `Deleted ${result.counters.updates().nodesDeleted || 0} record(s)` })),
       tap(mappedResult => console.log(mappedResult.message)),
    ),
)
```

The exported types from `result-rx.d.ts` seem to indicate there is a summary() which gives back an observable of the result summary. Didn't find anything in `result-rx.js` but did find a `_summary`  tied to a ReplaySubject.

My stacktrace looks like this right now if it helps 

```bash
TypeError: trx.run(...).summary is not a function
    at <project_directory>\dist\worker\worker.service.js:53:14
    at <project_directory>\node_modules\neo4j-driver\lib\session-rx.js:219:20
    at Observable._subscribe (<project_directory>\node_modules\rxjs\internal\observable\defer.js:10:21)
    at Observable._trySubscribe (<project_directory>\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (<project_directory>\node_modules\rxjs\internal\Observable.js:30:22)
    at CatchOperator.call (<project_directory>\node_modules\rxjs\internal\operators\catchError.js:32:23)
    at Observable.subscribe (<project_directory>\node_modules\rxjs\internal\Observable.js:25:31)
    at Object.subscribeToResult (<project_directory>\node_modules\rxjs\internal\util\subscribeToResult.js:12:23)
    at MergeMapSubscriber._innerSub (<project_directory>\node_modules\rxjs\internal\operators\mergeMap.js:82:53)
    at MergeMapSubscriber._tryNext (<project_directory>\node_modules\rxjs\internal\operators\mergeMap.js:76:14)
```

**Comment by zhenlineo** [comment]
Thanks for reporting this bug to us. It is named `consume` instead of summary now. We need to update our ts file.

**Comment by snurby7** [comment]
Awesome! Thanks, I'll make the switch to that. Mind me asking why the change over putting it in summary? Does it have more details in there?

**Comment by zhenlineo** [comment]
Hi @snurby7,

Nice observation. Yes, the summary is changed to consume to stress that the calling of `consume` will result in the drop of unconsumed records. So if you want to do something with the records, you shall do so before calling `consume`. Once a result is "consumed", then it cannot be reused.

> A result can only be consumed once.
> A result is consumed if either the query result has been discarded by invoking Result#consume, and/or the outer scope where the result is created, such as a transaction or a session, has been closed. Attempts to access consumed results will be responded with a ResultConsumedException.

Nice to read our [driver migration guide](https://neo4j.com/docs/migration-guide/4.0/upgrade-driver/#upgrade-driver-breakingchanges) if you are moving from 1.7 driver to 4.0 driver.

**Comment by snurby7** [comment]
Thanks @zhenlineo, consume worked exactly like I expected after telling TypeScript to let me do my thing and thank you again for the link, must have missed that when upgrading to 4.x

**Comment by martin-neotech** [comment]
https://neo4j.com/docs/api/javascript-driver/4.1/class/src/result-rx.js~RxResult.html#instance-method-consume
