### ISSUE TITLE
`DateTime` is not exported by package

### ISSUE THREAD

**Issue by asyarb** [neo4j/neo4j-javascript-driver#535]
### General Information

**Neo4j Version:** 4.0.1 Community  
**Neo4j Mode**: Single instance  
**Driver version**: JS driver 4.0.1  
**Operating System:** Official Docker image

The NodeJS driver package doesn't seem to export `DateTime`.

### Steps to reproduce

```ts
import { DateTime } from 'neo4j-driver'

// => undefined
console.log(DateTime)

// => Cannot read property 'fromStandardDate' of undefined
DateTime.fromStandardDate(new Date())
```

### Expected behavior

`DateTime` is defined.

### Proposed Solution

Quickly glancing at `index.js`, it looks like `DateTime` currently isn't being exported. Probably just need to include it here:

https://github.com/neo4j/neo4j-javascript-driver/blob/f11494cb25b063489a387bbf6d6785c9355bf58e/src/index.js#L362-L382

Let me know if I can provide any additional information! 👍🏽

**Comment by jharris4** [comment]
The types are exported as `types`.

I think what you're looking for is:

```
import { types } from 'neo4j-driver'

const { DateTime } = types
```

**Comment by asyarb** [comment]
Thanks @jharris4! Getting it that way works perfectly.

It looks like the types defined in `index.d.ts` currently define `DateTime` as a named top level export. Not a huge deal, but something that may end up tripping up other TS users 👍🏼.

https://github.com/neo4j/neo4j-javascript-driver/blob/f11494cb25b063489a387bbf6d6785c9355bf58e/types/index.d.ts#L248

Thanks again!

**Comment by jharris4** [comment]
@asyarb It looks you are correct, the TypeScript type definition seems to be out of date.

Thanks for pointing it out! I've opened a corresponding issue, and we'll see if we can get that fixed.
