### ISSUE TITLE
[Feature Request] - Flow types definitions

### ISSUE THREAD

**Issue by dmiranda2791** [neo4j/neo4j-javascript-driver#540]
Is there any on going initiative to add flow types to the repository?

We use flow types in our projects backend and it'd useful for us to have the definitions. I'd be glad to help with this.

**Comment by technige** [comment]
@dmiranda2791 Can you be more specific please? We're not sure exactly what you're asking for here.

**Comment by jharris4** [comment]
@technige Flow is an alternative to TypeScript (developed by Facebook) so I think he's asking for parallel type definitions, as described [here](https://flow.org/en/docs/libdefs/)

**Comment by dmiranda2791** [comment]
That's correct. 

@technige, as @jharris4 said, Flow is an alternative typing system for javascript. 

https://flow.org/

**Comment by technige** [comment]
@dmiranda2791 Thank you for your request, but after some internal discussion, we have decided not to provide support for Flow at this stage.
