### ISSUE TITLE
Cannot execute Example from website. Requests Fail

### ISSUE THREAD

**Issue by contra-bit** [neo4j/neo4j-javascript-driver#546]
### Cannot connect to Database

- Neo4j version: Community 4.0.1
- Neo4j Mode: Single instance using Docker
- Operating system: Arch Linux: 5.5.9-arch1-2
- **Steps to reproduce**

Setup for js (see https://neo4j.com/developer/javascript/)
``` bash
npm install --save neo4j neo4j-driver 
```
 Minimal Setup for testing Neo4j, the password has been replaced with password
``` js

// npm install --save neo4j
var neo4j = require('neo4j');
var db = new neo4j.GraphDatabase('http://neo4j:password@localhost:7474');


var insertQuery =
  "UNWIND {pairs} as pair \
   MERGE (p1:Person {name:pair[0]}) \
   MERGE (p2:Person {name:pair[1]}) \
   MERGE (p1)-[:KNOWS]-(p2)";

var foafQuery =
 "MATCH (person:Person)-[:KNOWS]-(friend)-[:KNOWS]-(foaf) \
  WHERE person.name = {name} \
   AND NOT (person)-[:KNOWS]-(foaf) \
  RETURN foaf.name AS name";

var commonFriendsQuery =
"MATCH (user:Person)-[:KNOWS]-(friend)-[:KNOWS]-(foaf:Person) \
 WHERE user.name = {name1} AND foaf.name = {name2} \
 RETURN friend.name AS friend";

var connectingPathsQuery =
"MATCH path = shortestPath((p1:Person)-[:KNOWS*..6]-(p2:Person)) \
 WHERE p1.name = {name1} AND p2.name = {name2} \
 RETURN [n IN nodes(path) | n.name] as names";

var data = [["Jim","Mike"],["Jim","Billy"],["Anna","Jim"],
            ["Anna","Mike"],["Sally","Anna"],["Joe","Sally"],
            ["Joe","Bob"],["Bob","Sally"]];

function query(query, params, column, cb) {
    function callback(err, results) {
        if (err || !results) throw err;
        if (!column) cb(results)
        else results.forEach(function(row) { cb(row[column]) });
    };
    db.cypher({ query: query, params: params}, callback);
}

query(insertQuery, {pairs: data}, null, function () {
    query(foafQuery, {name: "Joe"},"name", console.log);
    query(commonFriendsQuery, {name1: "Joe", name2:"Sally"},"friend",console.log);
    query(connectingPathsQuery, {name1: "Joe", name2:"Billy"}, "names",
          function(res) { console.log(res)});
});

```
Docker was setup in the way the dockhub tutorial says:
``` bash
docker run \                                                                                                         ✘ 130 
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/Code/Learn/neo4j/data:/data \
    neo4j
```

The default password was changed.
Neo4J Browser outputs 

You are connected as user neo4j
to neo4j://0.0.0.0:7687

After I have connected to the database i import the movie data with 
```
:play movies
```

Example Movie Queries are now possible
### Expected behavior
Neo4j js  executes the queries with succes

- Actual behavior
To test the js driver we execute example.js and get this Stacktrace
``` bash
node example.js
/home/s0/Code/Learn/neo4jja/node_modules/neo4j/lib-new/errors.js:20
      Error.captureStackTrace(this, this.constructor);
            ^

TypeError: Error.captureStackTrace is not a function
    at ClientError.Error [as constructor] (/home/s0/Code/Learn/neo4jja/node_modules/neo4j/lib-new/errors.js:20:13)
    at new ClientError (/home/s0/Code/Learn/neo4jja/node_modules/neo4j/lib-new/errors.js:81:48)
    at Function.Error.Error._fromObject (/home/s0/Code/Learn/neo4jja/node_modules/neo4j/lib-new/errors.js:70:14)
    at /home/s0/Code/Learn/neo4jja/node_modules/neo4j/lib-new/GraphDatabase.js:299:25
    at Request._callback (/home/s0/Code/Learn/neo4jja/node_modules/neo4j/lib-new/GraphDatabase.js:92:20)
    at Request.self.callback (/home/s0/Code/Learn/neo4jja/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/s0/Code/Learn/neo4jja/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/s0/Code/Learn/neo4jja/node_modules/request/request.js:1076:12)

```

I guess this error has do with a deprecation of tls. Could it be possible, that bolt or the js driver uses a outdated ssl or tls driver?

What can I do to fix this
Thank you a lot and stay healthy

**Comment by technige** [comment]
@contra-bit I'm confused. You mention both JS and Python here. Which driver are you using?

**Comment by contra-bit** [comment]
Excuse the confusion. I also made an Issue for the Python driver but this Issue is for the Javascript driver. I Clarified the comment

**Comment by contra-bit** [comment]
This is the Solution:
https://github.com/neo4j/neo4j-python-driver/issues/372#issuecomment-602470820 for the python driver

how can I deactivate the encryption for the test environment as explained in this answer?

**Comment by technige** [comment]
Firstly, note that you will not be able to connect with the driver over HTTP (your URI says `http://neo4j:password@localhost:7474`). The driver is for Bolt access only.

Once in Bolt mode though, you can switch on encryption as per the examples here:
https://neo4j.com/docs/driver-manual/4.0/client-applications/#driver-configuration-examples

**Comment by alete89** [comment]
> Firstly, note that you will not be able to connect with the driver over HTTP (your URI says `http://neo4j:password@localhost:7474`). The driver is for Bolt access only.

is it? I've tried with success using http to connect and run queries 😕

**Comment by alete89** [comment]
> Firstly, note that you will not be able to connect with the driver over HTTP (your URI says `http://neo4j:password@localhost:7474`). The driver is for Bolt access only.
> 
> Once in Bolt mode though, you can switch on encryption as per the examples here:
> https://neo4j.com/docs/driver-manual/4.0/client-applications/#driver-configuration-examples

I'm not OP, but I've been digging around this. does `neo4j://localhost:7687` or even `neo4j://localhost` connect against bolt?

**Comment by martin-neotech** [comment]
```
// Create a driver instance, for the user neo4j with password neo4j.
// It should be enough to have a single driver per database per application.
var driver = neo4j.driver(
  'neo4j://localhost',
  neo4j.auth.basic('neo4j', 'password')
)

// Close the driver when application exits.
// This closes all used network connections.
await driver.close()
```

source: https://github.com/neo4j/neo4j-javascript-driver#constructing-a-driver

see the drivers manual for uri schemes, https://neo4j.com/docs/driver-manual/current/client-applications/#driver-connection-uris

The official drivers uses the Bolt Protocol to communicate with the Neo4j server.

The different URI schemes available for the drivers are to specify connection settings.
