### ISSUE TITLE
Question: How to create multiple constraints through code?

### ISSUE THREAD

**Issue by prashantgupta24** [neo4j/neo4j-javascript-driver#562]
### Issue

Not able to create multiple constraints through code.

- Neo4j version: Community 4.0.3
- Neo4j Mode: Single instance
- Driver version: Javascript : "4.0.0", 
- Operating system:  Mac OS

### **Steps to reproduce**

I am creating some constraint statements for my neo4j DB through code, and I loop through all of them and create the respective cypher statements:
```

//loop through constraints
const statement = `CREATE CONSTRAINT ON (${name}:${type}) ASSERT ${name}.${parameter} IS UNIQUE`

 runConstraint(driver, statement)
```

```
function runConstraint(driver, constraintStatement) {
  var session = driver.session()
  return session
    .run(constraintStatement)
    .then((result) => {
      session.close()
      console.log('result : ', result)
    })
    .catch((error) => {
      session.close()
      console.log('error : ', error)
    })
}
```

### Expected behavior

The code should create all the constraints one by one.

### Actual behavior

```error :  Neo4jError: Database constraints have changed (txId=26) after this transaction (txId=1) started, which is not yet supported. Please retry your transaction to ensure all constraints are executed.```

**Comment by martin-neotech** [comment]
@prashantgupta24 

When creating a constraint, for example

```
CREATE CONSTRAINT ON (n:ZipCode) ASSERT n.name IS UNIQUE
```

this will require a lock on all nodes with the label the constraint is being created for, in this case ZipCode

If you have another transaction which was opened prior to the CREATE CONSTRAINT Cypher statement and it has a lock on the same Node label, for example

```
CREATE (n:ZipCode {name:'94401'}) RETURN n
```
then the CREATE CONSTRAINT will not progress until the open transaction is comitted/rolled back.

**source:**

https://neo4j.com/developer/kb/why-does-my-create-constraint-take-so-long-to-complete/


So when you are running queries containing `CREATE CONSTRAINT ON` make sure that they finish before running next query.
