### ISSUE TITLE
lastBookmark signature is different in session.d.ts and session.js

### ISSUE THREAD

**Issue by kevpogo** [neo4j/neo4j-javascript-driver#565]
Hello,

In session.js, lastBookmark() returns an array of string, in session.d.ts lastBookmark() signature returns string or null.
Is that an error?

**Comment by martin-neotech** [comment]
@kevpogo yes the session.d.ts lastBookmark() return signature is wrong.

https://github.com/neo4j/neo4j-javascript-driver/pull/605/commits/705bf94a24004d7d2781595d9d3e1b328586fc54

**Comment by bigmontz** [comment]
Hi @kevpogo, thanks for the reporting. The fix for this issue will be release on the 4.3 version.
