### ISSUE TITLE
Unable to create node with sample code

### ISSUE THREAD

**Issue by mikefontaine** [neo4j/neo4j-javascript-driver#567]
- Neo4j version: Neo4j Desktop 1.2.8 DB version 4.0.3 Community
- Neo4j Mode: Single instance
- Driver version: neo4j@4.0.0-RC2
- Operating system: Windows 10

**Steps to reproduce**

1. Start neo4j on local machine

2. add test code to node JS page 

3. start node 

4. execute test code code

```
router.post("/pushneo", function(req, res) {
  var driver = neo4j.driver("bolt://localhost:7687", neo4j.auth.basic(
    'toolbox', 'Qwerty123!'), {
    maxTransactionRetryTime: 30000
  });
  var session = driver.session();
  console.log("session start");
  session
    .run(
      'MERGE (alice:Person {name : $nameParam}) RETURN alice.name AS name', {
        nameParam: 'Alice'
      })
    .subscribe({
      onKeys: keys => {
        console.log(keys)
      },
      onNext: record => {
        console.log(record.get('name'))
      },
      onCompleted: () => {
        session.close() // returns a Promise
        console.log("session closed")
      },
      onError: error => {
        console.log(error)
      }
    })
  driver.close();
  console.log("driver closed")
});
```

- Expected behavior
Execute cypher and create PERSON Node named Alice
- Actual behavior: 
No node created and no error 
`session start
driver closed`

[query.log](https://github.com/neo4j/neo4j-javascript-driver/files/4647231/query.log)
[security.log](https://github.com/neo4j/neo4j-javascript-driver/files/4647232/security.log)
[debug.log](https://github.com/neo4j/neo4j-javascript-driver/files/4647233/debug.log)
[neo4j.log](https://github.com/neo4j/neo4j-javascript-driver/files/4647235/neo4j.log)

**Comment by michael-simons** [comment]
Would you please try the latest final release? 

https://github.com/neo4j/neo4j-javascript-driver/releases/tag/4.0.0

The 2.0.0 version has been renamed to 4.0.0 to align with the product itself.
