### ISSUE TITLE
Please decouple the reactive API

### ISSUE THREAD

**Issue by mprast** [neo4j/neo4j-javascript-driver#577]
I am not using the reactive API on this driver and I have no plans to. Since rxjs is a mandatory dependency right now, that means I basically have an extra ~5MB  of dead code. It'd really be a huge help if rxjs was declared as an optional (or [pseudo-optional](https://github.com/npm/npm/issues/3066#issuecomment-154161544) as the case may be) peer dependency - or, better yet, if the reactive API could be split off into its own package. A very cursory look at the source seems to suggest this can be done since all the reactive stuff appears to be neatly tucked into `*-rx.js` files. Also happy to help this process along with a PR if feasible. Thank you!

**Comment by gfarrell** [comment]
I would agree with this, bundling RxJS in here dilutes the single-responsibility principle -- this library should really handle connecting to and querying a Neo4J instance, it's not a necessary part of its job to make this reactive. If someone wants a reactive wrapper it should either be a separate library or they can do it themselves if the API is sensible.

**Comment by jamespedid** [comment]
I also feel that this is overkill. At least make rxJS a peer dependency that can be opted in. It would be highly preferable to use only components that are native to node JS: streaming interface and possibly async iterators comes to mind.

**Comment by bigmontz** [comment]
We released a new version of the driver which does not have the reactive API. Apart of reactive part, the interface should the same methods and behaviour.  

https://www.npmjs.com/package/neo4j-driver-lite

Thanks for the suggestion.

**Comment by mprast** [comment]
@bigmontz this is awesome; thank you!
