### ISSUE TITLE
[Typing] Integer toString parameter should be optional

### ISSUE THREAD

**Issue by A-ZC-Lau** [neo4j/neo4j-javascript-driver#585]
In the file `types/integer.d.ts` the `toString` method has a mandatory radix field i.e. 

```toString(radix: number): string```

This should not be the case as the `toString` function in `src/integer.js` defaults to 10

i.e.

```radix = radix || 10```

Can we update the declaration to

```toString(radix?: number): string```

**Comment by bigmontz** [comment]
Hi @A-ZC-Lau , the patch for this issue was created and it will be released on the version 4.3 of the driver. 

Thanks for the report.
