### ISSUE TITLE
RxSession Type Declaration missing

### ISSUE THREAD

**Issue by MatthiasBrandt** [neo4j/neo4j-javascript-driver#587]
`RxSession` cannot be used using Typescript as it's missing in the export declaration in `/types/index.d.ts`

**Steps to reproduce:**
`import { RxSession } from 'neo4j-driver' // fails`

**Comment by martin-neotech** [comment]
@MatthiasBrandt Hi thanks for contributing,

We require all source code that is hosted on the Neo4j infrastructure to be contributed through the Neo4j Contributor License Agreement (CLA).

https://neo4j.com/developer/cla/

**Comment by bigmontz** [comment]
It will be solved in 4.3
