### ISSUE TITLE
Issue with initiating driver connection to GrapheneDB Instance

### ISSUE THREAD

**Issue by iambenkay** [neo4j/neo4j-javascript-driver#589]
I got UnhandledPromiseRejectionWarning: Neo4jError: Unknown Bolt protocol version: 0

**Neo4j Community Edition 3.5.17**
**Neo4j Mode**: Single instance  
**Driver version**: JS driver 4.1.0
**Operating System:** Ubuntu 20.04 on Local computer

### Steps to reproduce

1. Create a grapheneDB instance
2. Try instantiating a connection from JS driver

### Expected behaviour

The program does not crash and proceeds to run session query

### Actual behaviour
The program crashes and also crashes the neo4j database instance (database restart required afterwards)

I rolled back to v4.0.2 and the error changed to "Internal Server Error" until I restarted the database so I strongly think this bug crashes the database too.

**Comment by technige** [comment]
Hi @iambenkay. If you think your database is crashing, you probably need to speak to GrapheneDB themselves about this issue. We don't routinely check against third party services, but for a standard installation, this driver should definitely work with Neo4j 3.5. Will leave this issue open in case you are able to get more info back from GrapheneDB.

**Comment by iambenkay** [comment]
@technige when I opened this issue, it was not because my database was crashing, It was because v4.1.0 of the driver couldn't connect to my Graphene Instance which runs Neo4j Community Edition 3.5.17, but when I downgraded to v4.0.2 it was working well. This is probably an issue of the driver version being incompatible with that version of the database.

**Comment by iambenkay** [comment]
I have been using the v4.0.2 of the driver in my project but one of my builds kept failing and when I took a closer look, I suspected that the problem could only arise from not locking my package version (A mistake I am never making again) so when the npm install ran, it fetched v4.1.0 instead hence the failing builds. I initially didn't feel obligated to report this and thought it would be a problem with my graphene instance but when I rolled back and it worked with v4.0.2, it settled my doubts.

**Comment by ryanmeador** [comment]
I had a nearly identical issue, #514, about six months ago.  It turned out to be a problem on the GrapheneDB side, and their support team was able to fix it for me.  I'm still using 4.0.2 on my project so I haven't seen this yet.  Thank you for bringing it to my attention.  I hope you contact Graphene about it.

**Comment by Judit** [comment]
Hello, I'm Judit from the GrapheneDB team. We are working on supporting Neo4j 4.1 drivers.
Please use 4.0 in the meantime. I'll post here when we are ready to support 4.1.

Thanks!

**Comment by technige** [comment]
@Judit I suggest transferring this issue from this repository to your in-house issue-tracking systems. And as such, I'll close the issue here.

**Comment by kennethaasan** [comment]
Hi @Judit , any updates on this?

**Comment by Judit** [comment]
Hello, we have already released our new offering. Neo4j 4.0 and 4.1 are now available and full compatible with the drivers.

I'm closing this ticket now. Thank you for your patience!

**Comment by kennethaasan** [comment]
4.0 works for me, but not 4.1. I get "Unknown Bolt protocol version: 0". I will contact your support.
