### ISSUE TITLE
Guidance on bolt protocol

### ISSUE THREAD

**Issue by jhechtf** [neo4j/neo4j-javascript-driver#591]
This isn't an issue per-se, but a request.

I'm looking to create a set of Neo4J drivers for Deno, but I'm sort of new to the raw communications. I know that Neo4J uses the bolt protocol, and I got some information through randomly searching, but I'd like to know if there are any other resources that I can use to create a custom set of drivers? I will admit that I looked on the website, but a lot of what I saw was information on how to use the already provided or community made drivers, and not a lot about how to make your own.

Any help is appreciated, and I'm sorry but I couldn't figure out where else to reach out for help.

**Comment by technige** [comment]
Hi @jhechtf 

We don't (yet) publish any detailed Bolt specs, although we do work directly with some community authors. Please drop an email to @jexp (michael at neo4j dot com) and me (nigel at neo4j dot com) with details of your plans and we can talk to you about joining those sessions.

in the meantime, the source code for the existing drivers is a good place to start.
