### ISSUE TITLE
README examples don't seem to be reflective of how Neo4J returns data

### ISSUE THREAD

**Issue by gfarrell** [neo4j/neo4j-javascript-driver#592]
## Details

- Neo4j version: Community 4.0.6
- Neo4j Mode: Single instance (docker)
- Driver version: Javascript driver (running in Typescript)  4.1.0
- Operating system: PopOS (Ubuntu derivative) 20.04

## Steps to reproduce

1. Create node

```typescript
import { types } from "neo4j-driver";
await session.run(
  "CREATE (a:MyNode { name: $name, date: $date })",
  { name: "Bugsy Manode", date: types.DateTime.fromStandardDate(new Date()) }
);
```
2. Try to retrieve node

```typescript
const result = await session.run("MATCH (n:MyNode) RETURN n");
result.records.forEach((record) => {
  console.log("Got me a node!", record.get("name")
});
```

## Expected behaviour

Should see the following in the console:
```
Got me a node! Bugsy Manode
```

## Actual behaviour

Get an error saying:
```(node:55962) UnhandledPromiseRejectionWarning: Neo4jError: This record has no field with key 'name', available key are: [n].```

**Comment by 2hdddg** [comment]
Hi @gfarrell which example are you referring to? There are several similair examples but as far as I can see they all return n.name which makes it possible to use record.get("name"), in your code you return the node not the name property of the node.

**Comment by gfarrell** [comment]
@2hdddg I see, perhaps I have misunderstood the examples. How do I return all the properties of the node (the equivalent of `select * from nodes` in SQL)?

**Comment by 2hdddg** [comment]
@gfarrell Not sure if you mean that you want all nodes or all properties of a node. Your ""MATCH (n:MyNode) RETURN n" returns all nodes with label MyNode and the each node has it's properties carried along with them so with this you get both.  
node = record.get(0)
name = node.properties["name"]

**Comment by gfarrell** [comment]
@2hdddg I mean to get all the properties for the matched nodes such that `record.get(prop)` will work as I would expect it to.

I'll close this for now as it's not actually a bug, now that I realise what the misunderstanding is, but would love to know the answer to the above question.

**Comment by gfarrell** [comment]
@2hdddg ok, so I have to get the 0th "property" basically, for each record:

```typescript
const names = result.records.map((record) => record.get(0).properties["name"]);
```

**Comment by 2hdddg** [comment]
Yes but instead of iterating from the values in the record you can as well iterate through the properties of the node
