### ISSUE TITLE
Error: Unknown Bolt protocol version: 0 since Neo4j-Driver 4.1.0

### ISSUE THREAD

**Issue by jessedobbelaere** [neo4j/neo4j-javascript-driver#595]
I'm running Neo4j 3.2.5 in a Docker container. I have a NodeJS app running `"neo4j-driver": "4.0.2"` perfectly. When I upgraded to neo4j-driver v4.1.0 today, the error rate went up because it's throwing `Unknown Bolt protocol version: 0` when executing something like `await session.run("RETURN 1")`

I went through the 4.1.0 changelog and the `4.1.0..4.0.2` compare on github, but didn't see what could be a breaking change. 
Also read:

> We have full test coverage for 4.0 js driver to support Neo4j 4.0, 3.5, 3.4, 3.3.

Does this mean that Neo4j 3.2.5 is not supported anymore by the new versions of this driver? 

I saw a few related issues but none that mentions a possible solution: https://github.com/neo4j/neo4j-javascript-driver/issues/589 and https://github.com/neo4j/neo4j-javascript-driver/issues/514#issuecomment-567424703

**Neo4j Version:** 3.2.5 Community  (`neo4j:3.2.5` docker image)
**Neo4j Mode**: Single instance  
**Driver version**: JS driver 4.2.1
**Operating System:** Node-alpine Docker

### Steps to reproduce

1. Start Neo4j 3.2.5 (docker container) with hostname `neo4j`
2. Run a query with the driver v4.1.0, e.g. `await session.run("RETURN 1")`. Connecting the driver to `neo4j://neo4j:7687` 
3. Error is thrown `Unknown Bolt protocol version: 0`

### Expected behavior

Queries run fine against Neo4j 3.2.5 with driver v4.1.0 just like they did in the previous version (v.4.0.2)

### Actual behavior
Errors are thrown when running queries with driver 4.1.0.

**Comment by gjmwoods** [comment]
Hi @jessedobbelaere.

Yes, the reason for this error is that `v4.1` of the driver supports Bolt versions 2+, and Neo4j 3.2.X only uses Bolt v1. Apologies as we should have included this in the changelog.

You have a couple of options. You could upgrade your Neo4j version to 3.3.X, or ideally, 3.5 since the last version in the 3 series will benefit from long term support. Or simply keep using the `4.0.X` drivers series which is still supported.

**Comment by jessedobbelaere** [comment]
Thanks for the insight! I was not aware that 3.2 was still Bolt v1. Will attempt the upgrade
