### ISSUE TITLE
[Feature Request] OpenTelemetry instrumentation

### ISSUE THREAD

**Issue by chrisdostert** [neo4j/neo4j-javascript-driver#604]
I would like to request opentelemetry instrumentation for nodejs

**Comment by technige** [comment]
Hi @chrisdostert. In order for us to consider this request, please could you add more detail.

In particular, can you supply more information about the the third party system you mention (what it does and how it fits in to the JS ecosystem) as well as how big the user base is for this product.

Thanks

**Comment by chrisdostert** [comment]
I think https://opentelemetry.io/ covers it. In short it's a cloud native foundation backed initiative to provide one instrumentation standard across the whole industry.

**Comment by chrisdostert** [comment]
@technige any update on this? All major cloud providers now generally have opentelemetry support; seems to be taking off in a major way. There are out of the box plugins for [many data stores like mysql, mongodb, redis, postgres](https://github.com/open-telemetry/opentelemetry-js-contrib) etc... would be amazing to have neo4j included.

**Comment by nirsky** [comment]
Hey! We ([Aspecto](https://www.aspecto.io)) just released a new library for instrumenting neo4j using opentelemetry.
Go check it out!
https://github.com/aspecto-io/opentelemetry-ext-js

We'd appreciate any feedback or PRs.

**Comment by bokjo** [comment]
> Hey! We ([Aspecto](https://www.aspecto.io)) just released a new library for instrumenting neo4j using opentelemetry.
> Go check it out!
> https://github.com/aspecto-io/opentelemetry-ext-js
> 
> We'd appreciate any feedback or PRs.

Hello @nirsky,

Thanks for sharing the plugin, now testing it!

I have a bug report for you already :)

**Comment by technige** [comment]
We do not plan to add support for this at this stage.
