### ISSUE TITLE
1.7.7 release can't run queries against 3.5.0

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/neo4j-javascript-driver#606]
First of all, v1.7.7. it's missing from the release log so I wasted a really long time trying to identify the cause of the bug as it wasn't apparent that the code had changed recently - would be good to address that 

**Neo4j Version:** 3.5.0 Community  
**Neo4j Mode**: Single instance  
**Driver version**: JS driver 1.7.7
**Operating System:** Linux and OSX - OS agnostic

### Steps to reproduce

1. Start Neo4j
2. Run any query using any of a valid session's query execution methods

### Expected behavior

Query should run (it does in 1.7.6)

### Actual behaviour

```
error: DB init failed error_message=You cannot run more transactions on a closed session., error_name=Neo4jError, error_stack=Neo4jError: You cannot run more transactions on a closed session.

    at captureStacktrace (/Users/wheresrhys/Projects/treecreeper/node_modules/neo4j-driver/lib/v1/result.js:199:15)
    at new Result (/Users/wheresrhys/Projects/treecreeper/node_modules/neo4j-driver/lib/v1/result.js:65:19)
    at Session._run (/Users/wheresrhys/Projects/treecreeper/node_modules/neo4j-driver/lib/v1/session.js:154:14)
    at Session.run (/Users/wheresrhys/Projects/treecreeper/node_modules/neo4j-driver/lib/v1/session.js:130:19)
    at runner (/Users/wheresrhys/Projects/treecreeper/packages/tc-api-db-manager/db-connection.js:71:30)
```

**Comment by martin-neotech** [comment]
@wheresrhys Hi what **_release log_** are you referring to?

https://github.com/neo4j/neo4j-javascript-driver/wiki/1.7-changelog#177

**Comment by martin-neotech** [comment]
https://github.com/neo4j/neo4j-javascript-driver/tags yes the tag of the patch **1.7.7** was never set, this is fixed now

**Comment by martin-neotech** [comment]
on npm the tag was correctly set https://www.npmjs.com/package/neo4j-driver/v/1.7.7

**Comment by martin-neotech** [comment]
@wheresrhys can you please add a code snippet that can reproduce the issue?

**Comment by wheresrhys** [comment]
It's something to do with how we instrument the driver to collect metrics I guess (I've trimmed out most of the cruft in the code below):

```js
const neo4j = require('neo4j-driver').v1;

const driver = neo4j.driver(
	process.env.NEO4J_BOLT_URL,
	neo4j.auth.basic(
		process.env.NEO4J_BOLT_USER,
		process.env.NEO4J_BOLT_PASSWORD,
	),
	{ disableLosslessIntegers: true },
);

const runQueryWithMetrics = async ({
	session,
	runner,
	isTransaction = false,
}) => {
	try {
		return runner();
	} finally {
		if (!isTransaction) {
			session.close();
		}
	}
};

const originalSession = driver.session;

driver.session = (...sessionArgs) => {
	const session = originalSession.apply(driver, sessionArgs);
	const originalRun = session.run;

	session.run = async (...runArgs) =>
		runQueryWithMetrics({
			session,
			runner: () => originalRun.apply(session, runArgs),
		});

	return session;
};

driver.session().run('CALL db.constraints')
	.then(console.log)
```

I can see a potential fix - I think I need to `return await runner()`. I'm surprised it ever worked. I suppose this issue is then some behaviour we were accidentally relying on - I don't know whether you want to treat that as a regression or not, but 🤞 this issue is resolved for me

**Comment by wheresrhys** [comment]
Though looking at the unsimplified code possibly the above doesn't capture an important difference. I'll have another look tomorrow

**Comment by wheresrhys** [comment]
Guess it's related to this line https://github.com/neo4j/neo4j-javascript-driver/compare/1.7.6...1.7.7#diff-d7ba25dbf602b727463ba72302ad62dbR100

**Comment by technige** [comment]
Hi @wheresrhys - are you still seeing an issue here?

**Comment by wheresrhys** [comment]
No this is resolved for us.
