### ISSUE TITLE
Incorrect typing on RxResult

### ISSUE THREAD

**Issue by snurby7** [neo4j/neo4j-javascript-driver#610]
https://github.com/neo4j/neo4j-javascript-driver/blob/938930fbf197cb32dfa24316f26696c3f3456b79/types/result-rx.d.ts#L28

Per the docs, this should be `consume` to match what is presented in the docs here. Summary type causes my query to fail on v4.1.1.

https://neo4j.com/docs/api/javascript-driver/4.1/class/src/result-rx.js~RxResult.html#instance-method-consume

**Comment by bigmontz** [comment]
Thanks, @snurby7 . This issue will be fixed at 4.3
