### ISSUE TITLE
Inconsistent prerelease version number casing confuses npm

### ISSUE THREAD

**Issue by cybersam** [neo4j/neo4j-javascript-driver#62]
I noticed that some prerelease version numbers are lowercased (e.g., “-alpha.1”), and some are uppercased (e.g., “-M01” and “-RC1”).

This causes problems/confusion for node.js clients because `npm`, the node.js package manager, orders prerelease versions alphabetically (with uppercase letters coming before lowercase letters).

So, npm believes the `alpha` versions are more recent than the `M` and `RC` versions.

Can neo4j's node.js packages start using lowercasing for all prerelease version numbers, to avoid this in the future? If the possible prerelease version prefixes are, say (in order of freshness): "alpha", "beta", "m", and "rc", this would be a way to solve this issue.

For example, if the next RC version were to be "1.0.0-rc3", then npm would properly consider it (and not "1.0.0-alpha7") to be the highest prerelease version for 1.0.0.

**Comment by pontusmelke** [comment]
Thanks for pointing this out, we'll make sure to be more consistent about casing in upcoming releases...

**Comment by pontusmelke** [comment]
We will take this into account going forward
