### ISSUE TITLE
feature: support query as json 

### ISSUE THREAD

**Issue by hpl002** [neo4j/neo4j-javascript-driver#757]
As far as i can see the driver expects a cypher query, would be neat if it could also accept this query as a JSON object.

I suspect that this is supported, but fail to find documentation or related issues on the subject. Feel free to correct me.

Thanks!

**Comment by oskarhane** [comment]
Hi @hpl002! I'm not working on the drivers team at Neo4j, but this feature request made me curious.
Could you show examples of what you mean?

**Comment by bigmontz** [comment]
Hi @hpl002, 

Could you elaborate a bit more about this feature adding a bit more context?

**Comment by hpl002** [comment]
This issue was opened based on a misunderstanding whilst i was getting started with cypher and neo4j. 

Sorry for not getting back to you sooner, and kudos for the community engagement!

Thanks
