### ISSUE TITLE
Replace text-encoding-utf-8 with a new library that has license 

### ISSUE THREAD

**Issue by yaominator** [neo4j/neo4j-javascript-driver#764]
Can we change the dependencies text-encoding-utf-8 for neo4j-driver-bolt-connection to a new npm package? text-encoding-utf-8 license is null. In my org, we cannot use an npm library that uses null icense

**Comment by bigmontz** [comment]
Hi @yaominator, 

thanks for notice this dependency issue. We added this dependency removal in our backlog.

**Comment by bigmontz** [comment]
Hi @yaominator, the fix will be release in version `4.4.1`. I will ping here when it's delivered.

**Comment by bigmontz** [comment]
Hi @yaominator , the fix was released in `4.4.1`. Thanks for reporting.

**Comment by yaominator** [comment]
Thanks a lot for helping!!! Now I could use the latest version.
