### ISSUE TITLE
typescript definition file

### ISSUE THREAD

**Issue by ADringer** [neo4j/neo4j-javascript-driver#77]
Hi,

Is it possible to get a typescript definition file so this could be used in an Angular2 project?

Thanks

Alex

**Comment by pontusmelke** [comment]
Hi Alex,
We don't have one at the moment, but it is a good suggestion. We will look into it.

Regards,
Pontus

**Comment by sittingbool** [comment]
+1

**Comment by ghost** [comment]
+1 (and in nodeJS with TypeScript projects too...)

**Comment by Mithgroth** [comment]
+1 please.

**Comment by marijneken** [comment]
+1 Any progress on this? Has no one created one externally?

**Comment by dpxxdp** [comment]
+1. Would really love this!

**Comment by mcgml** [comment]
+1 please

**Comment by smspasha** [comment]
+1

**Comment by ngasst** [comment]
I have written a (very) rough first draft of definitions for the driver. Have a look here. I plan on publishing them to DefinitelyTyped once they are fully ready, but for now they work for the project I'm working on.
Feel free to contribute.
[https://github.com/ngasst/neo4j-driver-definitions](https://github.com/ngasst/neo4j-driver-definitions)

**Comment by marijneken** [comment]
That's great news ngasst. The URL you're pointing to is wrong though. The text has the correct location, but the actual href is pointing somewhere else.

**Comment by ngasst** [comment]
Cheers @marijneken. Just corrected that. Thanks for pointing it out.

**Comment by zhenlineo** [comment]
https://github.com/neo4j/neo4j-javascript-driver/pull/183

**Comment by vnermolaev** [comment]
+1

**Comment by lutovich** [comment]
Pre-release version 1.4.0-beta01 is now available on npm, please feel free to try it out, give feedback and contribute. It can be installed via `npm install --save neo4j-driver@next`.
