### ISSUE TITLE
No inputs were found in the config file tsconfig.json

### ISSUE THREAD

**Issue by linojon** [neo4j/neo4j-javascript-driver#779]
I just started getting the following error in my project. I dont know why nor if its your issue or mine. I've not modified your file.
Using  
"neo4j-driver": "^4.3.3"

{
	"resource": "/d:/Documents/JavascriptProjects/expertnuggets/node_modules/neo4j-driver-core/tsconfig.json",
	"owner": "typescript",
	"severity": 8,
	"message": "No inputs were found in config file 'd:/Documents/JavascriptProjects/expertnuggets/node_modules/neo4j-driver-core/tsconfig.json'. Specified 'include' paths were '[\"src/**/*.ts\"]' and 'exclude' paths were '[\"lib\",\"types\"]'.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}

tsconfig.json:
```
{
  "compilerOptions": {
    "target": "ES5",
    "lib": ["ES6"],
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "downlevelIteration": true,
    "outDir": "lib",
    "declaration": true,
    "declarationDir": "types"
  },
  "include": ["src/**/*.ts"]
}
```

**Comment by linojon** [comment]
well i restarted vscode and the issue is gone, for now

**Comment by alxdram** [comment]
> well i restarted vscode and the issue is gone, for now

You don't know how many hours I spent on this one, thank you so much!
