### ISSUE TITLE
Errors leaking to other queries on the same session

### ISSUE THREAD

**Issue by legraphista** [neo4j/neo4j-javascript-driver#79]
Having the following code:

``` javascript
var neo4j = require('neo4j-driver').v1;
var driver = neo4j.driver(
    'bolt://localhost',
    neo4j.auth.basic(
        'neo4j',
        'password'
    )
);

var session = driver.session();

session
    .run('bad query')
    .then(console.log)
    .catch(console.error);

session
    .run('return 1')
    .then(console.log)
    .catch(console.error);
```

will generate the following output

```
Structure {
  signature: 127,
  fields: 
   [ { code: 'Neo.ClientError.Statement.SyntaxError',
       message: 'Invalid input \'b\': expected <init> (line 1, column 1 (offset: 0))\n"bad query"\n ^' } ] }
Structure {
  signature: 127,
  fields: 
   [ { code: 'Neo.ClientError.Statement.SyntaxError',
       message: 'Invalid input \'b\': expected <init> (line 1, column 1 (offset: 0))\n"bad query"\n ^' } ] }
```

and the error seems to leak to the second query. Is this intended behaviour? 

From my understanding, a session is a connection to the database, is it better to have one and run all the queries through it or have a different session for each and every query?

Note: the same effect will not happen if the first query has finished / errored before the start of the second query

**Comment by legraphista** [comment]
Same issue with `subscribe`:

``` javascript

session
    .run('bad query')
    .subscribe({
        onError: console.error,
        onNext: console.log,
        onFinish: console.log
    });

session
    .run('return 1')
    .subscribe({
        onError: console.error,
        onNext: console.log,
        onFinish: console.log
    });
```

Both throwing the same error even though the second query is valid

**Comment by pontusmelke** [comment]
The `session` can be shortlived but it is important to call `close` on the session once you are done with the session. 

The driver is asynchronous so if you want to run two queries in the same session after on another you'll have to do

```
session
    .run('bad query')
    .then(function (res) {
        session.run("another query")...
     })
    .catch(console.error);
```

or you if the order doesn't matter it is better to run queries in two different session, making sure to call `session.close` in either 'then' or in `onCompleted` (note that it `onCompleted` and not `onFinish` as in your example).

Best Regards,
Pontus

**Comment by legraphista** [comment]
I know the driver is asynchronous, in the example I wanted to have 2 queries run in parallel.

The problem that I wanted to point out is that query run instances are not isolated, so that if you pipe multiple queries through the same session and one dies, all error callbacks/promises of non-finished queries fire, and if that's intended behaviour, it is really weird.

**Comment by pontusmelke** [comment]
If you want them to run in parallel you should use two different sessions. 

Think of a session as a connection to the database with associated callbacks, when you run a query you put a request on the network queue. When that request has made it to the database and back: `onError` will be called if something went wrong with the request and if you have made multiple requests like in your example subsequent requests will never run.

The driver maintains a pool of sessions/connections so asking the driver for new sessions is really cheap as long as you make sure you call close on the session, which puts the session back in the pool.

**Comment by legraphista** [comment]
Ok, so since there's a pool and it is cheap to get another session after you've created a couple, the correct coding pattern here is to acquire a session, run your queries that need to be run in series and then close it, then it goes back in the pool. For other _parallel_ queries, just acquire another session.

I believe you should probably specify that somewhere 😄
