### ISSUE TITLE
Checking if a value exists in a Record

### ISSUE THREAD

**Issue by legraphista** [neo4j/neo4j-javascript-driver#82]
There is no _"proper"_ way to check if a value exists or not in a Record without trying to access and catching for errors.

Take this oversimplified example:

``` javascript
const queries = [
   'MATCH (a:Apple) RETURN COUNT(a) AS apples' ,
   'MATCH (a:Apple), (o:Orange) RETURN COUNT(a) AS apples, COUNT(o) AS oranges'
];

const query = queries[Math.random() > .5 ? 1 : 0];

session.run(query).then((data) => {
    console.log(data[0].get('apples'));

    // will throw if first query is chosen
    console.log(data[0].get('oranges')); 
});
```

There should be a way of checking for fields before trying to use them:

``` javascript
session.run(query).then((data) => {
    console.log(data[0].get('apples'));

    // will throw if first query is chosen
    if(data[0].has('oranges')) {
        console.log(data[0].get('oranges')); 
    }
});
```

**Comment by legraphista** [comment]
I've made a pull request with the necessary code and tests to implement `Record.has(key)` here https://github.com/neo4j/neo4j-javascript-driver/pull/83

**Comment by pontusmelke** [comment]
I agree this is missing in the driver, and I am happy to use your PR.
