### ISSUE TITLE
tilde fuzzy matching does not work with variables, only string literals

### ISSUE THREAD

**Issue by mtrx1337** [neo4j/neo4j-javascript-driver#820]
- Neo4j version: 4.3.7
- Neo4j Mode: single instance
- Driver version: node.js 4.3.3
- Operating system: MacOS Monterey

## Expected behavior

In the following code example we defined a fulltext search query. `searchQuery` is a string. The expected behaviour would be, that our search result contains fuzzy matched results for the value of our `searchQuery`.

```
const query = ['CALL db.index.fulltext.queryNodes('allNodes', $searchQuery~) YIELD node, score',
    'MATCH (Tag)-[rel:TAGS]-(n)',
    'RETURN node, COUNT(rel) as tagRels',
].join('\n');
const searchResult = await tx.run(query, { searchQuery }).then(createSearchDTO);
```

## Actual behavior
When using a variable the `~` fuzzy match operator does not work. The example above causes a syntax error. It only works when using literal strings.

```
(node:38801) UnhandledPromiseRejectionWarning: Neo4jError: Invalid input '~': expected an identifier character, whitespace, '.', node labels or rel types, '[', '^', '*', '/', '%', '+', '-', "=~", IN, STARTS, ENDS, CONTAINS, IS, '=', "<>", "!=", '<', '>', "<=", ">=", AND, XOR, OR, ',' or ')' (line 1, column 59 (offset: 58))
"CALL db.index.fulltext.queryNodes('allNodes', $searchQuery~) YIELD node, score"
                                                           ^
: 
    at captureStacktrace (/node_modules/neo4j-driver-core/lib/result.js:239:17)
    at new Result (/node_modules/neo4j-driver-core/lib/result.js:59:23)
    at finishTransaction (/node_modules/neo4j-driver-core/lib/transaction.js:357:12)
    at Object.commit (/node_modules/neo4j-driver-core/lib/transaction.js:192:25)
    at Transaction.commit (/node_modules/neo4j-driver-core/lib/transaction.js:117:37)
    at Object.searchNodes (/src/api/search/search.controller.ts:58:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
(the paths have been redacted)

**Comment by fbiville** [comment]
The error you shared comes from the server, the syntax you are trying to use is not supported by the Cypher engine.
I think you are misusing `db.index.fulltext.queryNodes` here.

**Comment by mtrx1337** [comment]
If `~` is supported with string literals on `queryNodes`, why is using variables instead of a string literal considered misusing `queryNodes`? What function should I use instead?

**Comment by fbiville** [comment]
I think the `~` should either be concatenated to or part of the value of the `searchQuery` variable.

**Comment by mtrx1337** [comment]
That worked. Thank you. 

query:
`CALL db.index.fulltext.queryNodes('allNodes', $searchQuery) YIELD node, score`

fuzzSearchQuery value:
`query~`

query execution
`tx.run(query, { searchQuery: fuzzySearchQuery })`
