### ISSUE TITLE
New docs location?

### ISSUE THREAD

**Issue by MerrickClark** [neo4j/neo4j-javascript-driver#87]
http://alpha.neohq.net/docs/javascript-driver/ seems down, or has moved?

Excited about using bolt! 👍

**Comment by technige** [comment]
The API docs can be found here -> http://neo4j.com/docs/api/javascript-driver/current/

The alpha website was an internal resource not intended for general use. It has now been taken down.

**Comment by ankursmooth** [comment]
please update links of API here https://neo4j.com/developer/javascript/ and here https://github.com/neo4j/neo4j-javascript-driver/blob/1.1/README.md
Thanks
