### ISSUE TITLE
Cannot Connect to AuraDB database "No routing servers available"

### ISSUE THREAD

**Issue by MaximCamilleri** [neo4j/neo4j-javascript-driver#899]
## Problem:
I am running an AuraDB server on version 4.4-aura. I am trying to connect to the server using the code bellow. When trying to connect the program gives the following error.

## Error:
```
Neo4jError: Could not perform discovery. No routing servers available. 
Known routing table: RoutingTable[database=default database, 
expirationTime=0, currentTime=1647009955517, routers=[], readers=[], writers=[]]
```

## Code: 
```javaScript
    var viz; 

    function draw() {
        var config = {
            container_id: "viz",
            server_url: "neo4j://101fd6b7.databases.neo4j.io",
            server_user: "neo4j",
            server_password: "<REDACTED>",
            labels: {

            },
            relationships: {
                "INTERACTS": {
                    "thickness": "weight",
                    "caption": false
                }
            },
            initial_cypher: "MATCH (n)-[:CommonRecipes]-(b) WHERE n.name = 'onion' RETURN b"
        };
        viz = new NeoVis.default(config);
        viz.render();
    }
```

**Comment by bigmontz** [comment]
Hi @MaximCamilleri, you should use `neo4j+s` to connect to Aura. So, you should use `           server_url: "neo4j+s://101fd6b7.databases.neo4j.io",`

**Comment by MaximCamilleri** [comment]
> 
Hi @bigmontz, unfortunately changing the url to neo4j+s gives another error. I had originally removed the +s to deal with this error.

```
Uncaught Error: Encryption/trust can only be configured either through URL or config, not both
```

**Comment by bigmontz** [comment]
The NeoVis defining the property `encrypted` in the driver, so that's why it's not possible to use `neo4j+s`. 

You should configure your url using `neo4j` and add the configuration param `encrypted: 'ENCRYPTION_ON'`. More detail in [the Neo4jVis docs](https://github.com/neo4j-contrib/neovis.js/#configencrypted).

**Comment by MaximCamilleri** [comment]
Sorry for the late reply.  I have made updates as you instructed and i am still getting the same error:
``` Uncaught Error: Encryption/trust can only be configured either through URL or config, not both ```

**Comment by bigmontz** [comment]
You should configure `server_url: "neo4j://101fd6b7.databases.neo4j.io"` and configure `encrypted: 'ENCRYPTION_ON'`. 

The Neo4jVis doesn't support the ssl configuration using the `url scheme`, unfortunately.
