### ISSUE TITLE
Huge increase of open filedescriptors

### ISSUE THREAD

**Issue by timoweiss** [neo4j/neo4j-javascript-driver#96]
- Neo4j version: 3.0.1
- Language: Javascript (NodeJS v4.4.4)
- OS: Ubuntu 14.04.3 LTS
- Single Machine

Hello,

I have one machine running neo4j and another one running a node process.
I'm using neo4j-driver 1.0.1.
When neo4j throws a OOM exception and the node process tries to open a session to this instance, the machine running nodejs runs out of file-descriptors.
counting the open files to the neo4j instance shows numbers around the 30000.

Is there a way to limit the connections of the neo4j driver?

Many thanks in advance!

Timo

**Comment by pontusmelke** [comment]
Sorry for not getting back to you on this. We haven't been able to reproduce the issue, but we will get back to you once we have a fix. If you have code you can share it would be great?

Regards,
Pontus

**Comment by technige** [comment]
Closing issue. Please reopen if you can provide more info on how to recreate.
